update public.quiz_questions
set situation = case block_id
  when 'quimica-materia' then $q$En la Institución Educativa Técnica La Esperanza, un docente de Química de grado décimo revisa los resultados de una prueba diagnóstica aplicada al iniciar el periodo. Aunque la mayoría de estudiantes identifica nombres de sustancias de uso cotidiano, presentan dificultades para explicar por qué unas conducen la electricidad, otras se disuelven en agua y otras tienen puntos de fusión muy diferentes. En la clase anterior varios estudiantes afirmaron que "todas las sustancias están hechas de moléculas", que "si una sustancia se disuelve deja de existir" y que "un metal conduce porque está caliente".

Para responder a esta situación, el docente organiza una secuencia de indagación con cuatro estaciones: sal común sólida y disuelta, agua, dióxido de carbono representado con modelos moleculares y una lámina metálica. En cada estación los estudiantes deben observar una propiedad macroscópica, proponer una explicación microscópica, contrastarla con el modelo de enlace correspondiente y registrar una conclusión. La coordinación académica solicita que la actividad no se limite a memorizar definiciones, sino que permita evidenciar si el estudiante puede relacionar estructura, enlace, polaridad, interacciones y propiedades observables. El docente debe seleccionar las mejores intervenciones, preguntas y criterios de evaluación para orientar el aprendizaje sin reemplazar el razonamiento de los estudiantes por respuestas dictadas.$q$
  when 'quimica-reacciones' then $q$En grado décimo, el docente de Química prepara una unidad sobre conservación de la masa, balanceo y relaciones estequiométricas a partir de un problema contextual: la combustión de gas natural en hogares del municipio. En el diagnóstico inicial detecta que varios estudiantes balancean ecuaciones cambiando subíndices, confunden coeficientes con cargas eléctricas y creen que el reactivo con mayor masa siempre produce mayor cantidad de producto. Además, al resolver ejercicios numéricos, algunos aplican reglas de tres sin interpretar la ecuación química ni revisar unidades.

Para evitar una clase puramente procedimental, el docente plantea una situación de aula: comparar una combustión completa representada por una ecuación, identificar proporciones molares, discutir qué ocurre cuando el oxígeno es insuficiente y justificar por qué se conserva el número de átomos aunque las sustancias cambien. Los estudiantes trabajan en grupos con tarjetas de átomos, modelos de moléculas y una tabla de datos sencilla. Al final deben presentar una explicación que conecte conservación, balanceo, reactivo limitante y cantidad de producto. La institución espera que la evaluación valore tanto el procedimiento como la argumentación, porque el concurso docente suele presentar casos donde el aspirante debe elegir la intervención más coherente ante errores conceptuales frecuentes.$q$
  when 'quimica-soluciones' then $q$La Institución Educativa San Rafael desarrolla un proyecto ambiental sobre la calidad del agua de una quebrada cercana. El docente de Química recibe muestras recolectadas por estudiantes de diferentes sedes y observa que los registros iniciales son inconsistentes: algunos grupos reportan pH sin indicar el método, otros confunden concentración con cantidad total de soluto, y varios consideran que una muestra "se ve limpia" aunque presente olor o valores atípicos. La rectoría pide que el proyecto se use para fortalecer competencias científicas, no solo para elaborar una cartelera ambiental.

El docente diseña una secuencia en la que los estudiantes preparan soluciones patrón, revisan el concepto de molaridad, usan indicador universal, comparan valores de pH y discuten posibles equilibrios asociados a acidez, basicidad y contaminación. Para mejorar la calidad de los datos, define protocolos de rotulado, limpieza, volumen de muestra, registro de unidades e identificación de posibles fuentes de error. También pide que cada equipo argumente sus conclusiones con evidencia y que no declare una muestra como segura o contaminada sin contrastar datos con criterios. Las preguntas del simulacro se basan en esta situación y evalúan lectura química de datos, control de variables, interpretación de pH, concentración y toma de decisiones pedagógicas.$q$
  when 'quimica-organica' then $q$En una institución urbana, el área de Ciencias Naturales desarrolla una unidad sobre materiales de uso cotidiano. El docente de Química propone que los estudiantes analicen etiquetas de alcohol antiséptico, vinagre, envases plásticos, combustibles y productos de limpieza. En la discusión inicial encuentra errores frecuentes: algunos creen que "orgánico" significa necesariamente saludable, otros asocian todos los polímeros con sustancias idénticas, y varios no logran relacionar grupos funcionales con propiedades o riesgos de uso.

Para abordar estas dificultades, el docente organiza una actividad con modelos moleculares, lectura de etiquetas, fichas de seguridad simplificadas y comparación de estructuras. El propósito es que los estudiantes reconozcan alcoholes, ácidos carboxílicos, polímeros y combustibles, pero también que expliquen por qué una estructura química puede influir en solubilidad, inflamabilidad, olor, impacto ambiental o forma de disposición final. La evaluación solicita justificar respuestas, no solo nombrar grupos funcionales. La coordinación sugiere que la unidad incluya alfabetización científica: interpretar información comercial, diferenciar evidencia de publicidad y tomar decisiones responsables frente al consumo y manejo de materiales. Las preguntas valoran comprensión conceptual, didáctica del contexto y uso de modelos.$q$
  when 'quimica-aula' then $q$El docente de Química debe planear una práctica experimental con recursos limitados y estudiantes de diferentes ritmos de aprendizaje. La institución cuenta con materiales de bajo riesgo, pocos instrumentos de medición y grupos numerosos. En experiencias anteriores, varios estudiantes siguieron instrucciones mecánicamente sin formular hipótesis, omitieron controles, copiaron datos de otros equipos y entregaron conclusiones que no correspondían a sus resultados. La coordinación académica le pide al docente transformar el laboratorio en una actividad de indagación guiada y evaluación formativa.

El docente propone estudiar factores que afectan la velocidad de disolución usando sal, agua, recipientes transparentes, termómetro y cronómetro. Antes de iniciar, los estudiantes deben formular una pregunta investigable, reconocer variables, acordar normas de seguridad, definir una tabla de registro y anticipar posibles fuentes de error. Durante el desarrollo, el docente circula por los equipos, pregunta por la relación entre datos y conclusiones, solicita revisar unidades y orienta a quienes presentan dificultades de representación gráfica. Al cierre, cada grupo debe explicar qué cambió, qué controló, qué evidencia obtuvo y cómo mejoraría el procedimiento. Las preguntas evalúan decisiones de planeación, seguridad, control experimental, retroalimentación y uso pedagógico del error.$q$
  when 'quimica-termodinamica' then $q$En una secuencia sobre energía química, el docente observa que sus estudiantes usan de manera indistinta expresiones como calor, temperatura, energía de activación y velocidad de reacción. Algunos creen que una reacción exotérmica siempre ocurre instantáneamente, otros piensan que un catalizador aumenta la cantidad final de producto y varios interpretan las gráficas de energía como dibujos decorativos sin variables. Para atender estas dificultades, el docente diseña una clase basada en fenómenos: una bolsa fría instantánea, una reacción que libera calor y una simulación de choques moleculares.

La actividad se organiza en tres momentos. Primero, los estudiantes describen cambios observables y registran temperatura antes y después del proceso. Luego, interpretan diagramas de energía para comparar reactivos, productos y energía de activación. Finalmente, analizan cómo temperatura, concentración, superficie de contacto y catalizadores pueden modificar la velocidad sin cambiar la ley de conservación de la masa. El docente quiere que las respuestas no se limiten a definiciones, sino que expliquen mecanismos, condiciones y evidencias. En la evaluación, cada pregunta exige decidir qué intervención, explicación o representación ayuda mejor a superar un error conceptual frecuente en química escolar.$q$
  when 'quimica-redox' then $q$En una institución técnica, el docente de Química articula una unidad sobre electroquímica con problemas cotidianos del entorno: corrosión de rejas, disposición de pilas usadas y funcionamiento de una celda galvánica sencilla. En el diagnóstico, los estudiantes reconocen que el hierro "se oxida", pero no pueden explicar la transferencia de electrones ni diferenciar agente oxidante y agente reductor. También consideran que las pilas producen electricidad porque "guardan corriente", sin relacionar el proceso con una reacción química espontánea.

El docente propone analizar muestras de metal corroído, construir un esquema de media celda, identificar cambios en números de oxidación y discutir riesgos ambientales asociados a residuos de pilas. La clase busca integrar saber disciplinar, uso de modelos y responsabilidad ciudadana. Para ello, los estudiantes deben representar qué especie pierde electrones, cuál se reduce, cómo se genera el flujo de electrones y por qué la disposición inadecuada de baterías puede liberar contaminantes. La evaluación se diseña con casos de decisión, no con preguntas aisladas de memoria, porque se espera que el futuro docente pueda explicar fenómenos, prevenir errores conceptuales y vincular la química con situaciones ambientales reales.$q$
  when 'quimica-ambiental' then $q$La institución participa en un proyecto municipal de educación ambiental después de que la comunidad reporta olores fuertes cerca de una quebrada y episodios de humo por quema de residuos. El docente de Química recibe el encargo de orientar a estudiantes de media para analizar la situación con criterios científicos. En las primeras conversaciones aparecen afirmaciones poco sustentadas: algunos culpan a una sola familia sin evidencia, otros piensan que si el agua es transparente es potable, y otros creen que la contaminación atmosférica no tiene relación con moléculas ni reacciones.

El docente plantea una investigación escolar responsable: revisar posibles fuentes de contaminantes, medir pH de muestras, analizar información sobre nitratos, discutir lluvia ácida, estudiar gases de efecto invernadero y contrastar datos con fuentes confiables. También aclara que la escuela no reemplaza a la autoridad ambiental, pero sí puede formar pensamiento crítico, prevención y participación informada. Los estudiantes deben diferenciar observaciones, inferencias, mediciones y conclusiones; además, deben proponer acciones viables sin manipular sustancias peligrosas ni señalar responsables sin verificación. Las preguntas evalúan química ambiental, lectura de datos, argumentación y decisiones pedagógicas seguras.$q$
  when 'quimica-evaluacion' then $q$El jefe de área solicita al docente de Química revisar sus instrumentos de evaluación porque los resultados muestran una brecha: los estudiantes obtienen buenos puntajes cuando se les pregunta por definiciones, pero fallan al resolver situaciones contextualizadas. En una reunión de área se identifica que varias pruebas solo piden repetir nombres de compuestos, fórmulas o pasos de algoritmos, sin exigir interpretación de datos, justificación de procedimientos ni análisis de errores. La institución quiere preparar mejor a los estudiantes y, al mismo tiempo, fortalecer la calidad de los instrumentos docentes.

El docente propone rediseñar preguntas para que incluyan contexto, información suficiente, distractores plausibles y criterios alineados con competencias científicas. También plantea que los resultados se usen para retroalimentar la enseñanza: si muchos estudiantes fallan molaridad, balanceo o nomenclatura, el problema no se resuelve repitiendo la misma prueba, sino analizando el tipo de error y diseñando nuevas mediaciones. La coordinación espera que el docente distinga evaluación memorística, evaluación formativa y evaluación por competencias. Las preguntas de este bloque se centran en cómo construir, seleccionar e interpretar ítems de química con validez pedagógica.$q$

  when 'naturales-ecosistemas' then $q$La Institución Educativa Rural El Cedro desarrolla un proyecto de investigación escolar sobre una microcuenca que abastece parte de la vereda. Los estudiantes han observado disminución de insectos polinizadores, acumulación de residuos en algunas orillas y cambios en la presencia de peces durante épocas de lluvia. En la socialización inicial surgen explicaciones simples: unos estudiantes atribuyen todos los cambios a "mala suerte", otros creen que una sola especie no afecta al ecosistema y algunos confunden población, comunidad y ecosistema.

El docente de Ciencias Naturales organiza salidas de observación, registro de variables ambientales, construcción de redes tróficas y análisis de posibles relaciones entre uso del suelo, calidad del agua y biodiversidad. La actividad debe permitir que los estudiantes formulen preguntas, reconozcan niveles de organización ecológica, interpreten interacciones y propongan acciones de conservación con base en evidencia. La rectoría pide que el proyecto no se quede en mensajes generales de cuidado ambiental, sino que fortalezca pensamiento científico y participación responsable. Las preguntas del bloque evalúan comprensión de relaciones ecológicas, indicadores ambientales, toma de decisiones y didáctica contextualizada.$q$
  when 'naturales-celula' then $q$En una secuencia de biología para grado noveno, el docente detecta que varios estudiantes memorizan nombres de organelos, pero no logran relacionarlos con procesos vitales. También confunden mitosis y meiosis, creen que los rasgos heredados aparecen por decisión de los individuos y tienen dificultades para interpretar cuadros de Punnett sencillos. En una evaluación diagnóstica, algunos explican enfermedades hereditarias como castigos o accidentes sin base biológica, lo que preocupa al área por sus implicaciones en alfabetización científica.

El docente diseña una unidad que conecta estructura celular, división celular, herencia y salud. Utiliza modelos de célula, esquemas de cromosomas, análisis de casos familiares ficticios y discusión sobre el uso responsable de información genética. El propósito es que los estudiantes construyan explicaciones: cómo una célula obtiene energía, por qué la mitosis conserva información, cómo se segregan alelos y qué significa hablar de probabilidad genética. Las actividades deben ser respetuosas y evitar determinismos o estigmatización. Las preguntas del simulacro evalúan tanto conocimiento biológico como decisiones pedagógicas para promover argumentación, modelación y comprensión de conceptos abstractos.$q$
  when 'naturales-fisica' then $q$En una clase integrada de Ciencias Naturales, el docente usa una bicicleta como situación problema para abordar movimiento, fuerzas, energía y transferencia de calor. Al iniciar, los estudiantes afirman que "si algo se mueve, necesariamente hay una fuerza neta hacia adelante", que "calor y temperatura son lo mismo" y que la energía se gasta o desaparece cuando hay rozamiento. El docente decide convertir estas ideas previas en punto de partida de una secuencia experimental y argumentativa.

La clase incluye registro de posiciones en intervalos de tiempo, análisis de gráficas, discusión sobre fuerza neta, comparación entre masa y peso, y explicación de la transformación de energía durante una bajada. También se revisa por qué el rozamiento puede aumentar la temperatura de algunas partes del sistema sin destruir la energía. El docente busca que los estudiantes pasen de respuestas intuitivas a explicaciones apoyadas en modelos físicos escolares. Para evaluar, plantea preguntas en las que el aspirante debe seleccionar la intervención más adecuada, la representación más útil o la explicación científicamente coherente para un fenómeno cotidiano.$q$
  when 'naturales-indagacion' then $q$El área de Ciencias Naturales organiza una feria investigativa institucional. En años anteriores, muchos proyectos se limitaron a carteleras llamativas, maquetas copiadas de internet o experimentos demostrativos sin pregunta investigable. La coordinación académica solicita que esta versión fortalezca competencias de indagación: formular preguntas, plantear hipótesis, controlar variables, registrar datos, interpretar resultados, reconocer limitaciones y comunicar conclusiones con responsabilidad ética.

El docente acompaña a varios equipos. Un grupo quiere estudiar el crecimiento de plantas con diferente exposición a la luz; otro analiza contaminación por residuos en patios; un tercero pretende trabajar con seres vivos y requiere normas de cuidado. El reto docente consiste en convertir intereses generales en diseños viables, seguros y evaluables. Además, debe usar rúbricas claras, retroalimentación durante el proceso y criterios que valoren evidencia, no solo presentación final. Las preguntas del bloque ubican al aspirante en decisiones reales de aula: qué hipótesis es investigable, qué variable debe controlarse, cómo evaluar conclusiones, cuándo intervenir por razones éticas y cómo hacer de la evaluación un proceso formativo.$q$
  when 'naturales-cuerpo' then $q$En educación básica, la institución desarrolla una campaña de salud escolar después de identificar hábitos alimentarios poco variados, baja actividad física y circulación de información no verificada sobre vacunas y enfermedades. El docente de Ciencias Naturales debe abordar sistemas del cuerpo humano, nutrición, prevención y toma de decisiones saludables sin convertir la clase en una lista de prohibiciones ni en una charla moralizante. En el diagnóstico, algunos estudiantes confunden digestión con respiración, creen que todos los alimentos procesados son iguales y usan redes sociales como fuente principal de información sanitaria.

El docente diseña actividades de análisis de etiquetas nutricionales, modelos de sistemas corporales, rutas de transmisión de enfermedades y lectura crítica de fuentes. También decide involucrar a las familias mediante orientaciones respetuosas y remisión a fuentes sanitarias confiables cuando surgen dudas sensibles. La evaluación exige que los estudiantes expliquen relaciones entre sistemas, interpreten información, justifiquen decisiones y reconozcan límites del rol docente. Las preguntas del bloque valoran conocimiento biológico, educación para la salud y manejo pedagógico de creencias familiares desde respeto, evidencia y responsabilidad institucional.$q$
  when 'naturales-evolucion' then $q$En una clase sobre biodiversidad colombiana, el docente observa que los estudiantes describen muchas especies, pero presentan dificultades para explicar por qué existen adaptaciones y cómo actúa la selección natural. Algunos dicen que los organismos cambian porque "quieren mejorar", otros piensan que evolución significa progreso obligatorio y varios no relacionan pérdida de hábitat con disminución de biodiversidad. El docente decide trabajar con casos de ecosistemas locales para evitar explicaciones finalistas y promover pensamiento evolutivo.

La secuencia parte de variaciones observables en una población ficticia, presiones ambientales, disponibilidad de recursos y éxito reproductivo diferencial. Luego se conecta con amenazas reales como deforestación, fragmentación de hábitat y reducción de corredores biológicos. Los estudiantes deben distinguir aprendizaje individual de adaptación evolutiva, reconocer la importancia de la variación heredable y argumentar por qué conservar hábitats protege relaciones ecológicas y diversidad genética. Las preguntas del bloque evalúan comprensión de evolución, biodiversidad y conservación, así como decisiones didácticas para corregir ideas previas sin ridiculizar a los estudiantes.$q$
  when 'naturales-tierra' then $q$El área de Ciencias Naturales participa en la actualización del plan escolar de gestión del riesgo. En el municipio se han presentado temporadas de sequía, lluvias intensas, deslizamientos en zonas de pendiente y dificultades de abastecimiento de agua. Durante las clases, algunos estudiantes confunden tiempo atmosférico con clima, interpretan un día caluroso como prueba suficiente de cambio climático y desconocen cómo la cobertura vegetal influye en erosión e infiltración.

El docente propone un proyecto interdisciplinar con registro de precipitación, análisis de mapas, observación de suelos, revisión de series históricas y diseño de acciones de adaptación escolar. El propósito es que los estudiantes usen datos, distingan escalas temporales, comprendan el ciclo del agua y reconozcan amenazas y vulnerabilidades del territorio. La institución espera que las conclusiones no sean alarmistas ni negacionistas, sino argumentadas con evidencia. Las preguntas del bloque exigen seleccionar datos pertinentes, interpretar fenómenos de Tierra y clima, y tomar decisiones pedagógicas que conecten ciencia escolar con prevención y cuidado del entorno.$q$
  when 'naturales-quimica-integrada' then $q$En una unidad integrada, el equipo de Ciencias Naturales busca articular química, física y biología alrededor de una pregunta: ¿cómo se transforman la materia y la energía en los seres vivos y en actividades humanas? En clases anteriores los estudiantes estudiaron fotosíntesis, respiración, combustión y cadenas alimentarias como temas separados, por lo que no logran explicar relaciones entre procesos. Algunos creen que la energía se recicla igual que la materia, otros afirman que la glucosa desaparece durante la respiración y varios no distinguen transferencia de energía de transformación de sustancias.

El docente diseña una secuencia con modelos de flujo de energía, ecuaciones simplificadas, análisis de combustibles y discusión sobre calidad del aire. Los estudiantes deben representar entradas y salidas de materia, describir transformaciones energéticas y reconocer pérdidas de energía útil como calor en sistemas biológicos y físicos. La evaluación se centra en la capacidad de integrar disciplinas sin perder rigor conceptual: usar química para hablar de sustancias, física para hablar de energía y biología para hablar de organismos y ecosistemas. Las preguntas miden modelación, interdisciplinariedad y explicación de fenómenos complejos.$q$
  when 'naturales-pedagogia-ciencias' then $q$El equipo de Ciencias Naturales revisa su plan de área después de observar que algunos estudiantes participan poco en prácticas de laboratorio, otros presentan dificultades de lectura de gráficas y varios no logran argumentar conclusiones con evidencia. Además, los docentes reconocen que sus evaluaciones han privilegiado productos finales y asistencia, pero no siempre recogen avances del proceso, calidad de la indagación ni mejora después de la retroalimentación. La coordinación pide ajustar el plan para fortalecer inclusión, pensamiento científico y evaluación formativa.

El equipo propone alinear estándares, preguntas orientadoras, actividades de indagación, criterios de evaluación y apoyos para estudiantes con diferentes ritmos. Se acuerda diversificar formas de representación: observación directa, modelos, textos breves, gráficas, debates y explicaciones orales. También se decide que el error experimental se use como oportunidad para revisar variables y que las rúbricas sean conocidas antes de la entrega. Las preguntas del bloque sitúan al aspirante ante decisiones curriculares y didácticas: cómo incluir sin bajar expectativas, cómo valorar argumentación científica, cómo retroalimentar errores y cómo asegurar coherencia entre propósitos, actividades y evidencias.$q$
end
where test_id in ('generado-quimica-01', 'generado-naturales-01')
  and block_id in (
    'quimica-materia', 'quimica-reacciones', 'quimica-soluciones', 'quimica-organica',
    'quimica-aula', 'quimica-termodinamica', 'quimica-redox', 'quimica-ambiental',
    'quimica-evaluacion', 'naturales-ecosistemas', 'naturales-celula', 'naturales-fisica',
    'naturales-indagacion', 'naturales-cuerpo', 'naturales-evolucion', 'naturales-tierra',
    'naturales-quimica-integrada', 'naturales-pedagogia-ciencias'
  );
