alter table public.quiz_questions
  drop constraint if exists quiz_questions_category_check;

alter table public.quiz_questions
  add constraint quiz_questions_category_check
  check (category in ('pedagogica', 'especificos', 'razonamiento', 'ofimatica'));

with base_sequence as (
  select coalesce(max(sequence), 0) + 1000 as value
  from public.quiz_questions
),
new_questions (
  position, external_id, block_id, block_range, topic, situation, question_number,
  prompt, options, correct_answer, explanation, option_feedback
) as (
  values
  (1, 'ofi-01', 'ofimatica-documentos', '1-6', 'Procesador de texto: estructura y colaboracion',
   $q$Una institución educativa prepara un informe de seguimiento académico para entregar a coordinación y familias. El documento debe reunir portada, tabla de contenido, capítulos con títulos jerarquizados, evidencias de avance, comentarios de revisión y una versión final en PDF. Varios docentes editan el archivo de manera simultánea y se requiere conservar trazabilidad de cambios sin perder formato.$q$,
   1, $q$¿Qué acción organiza mejor el documento para generar una tabla de contenido automática?$q$,
   jsonb_build_array($q$Aplicar estilos de título a las secciones y actualizar la tabla de contenido.$q$, $q$Aumentar manualmente el tamaño de letra de cada encabezado.$q$, $q$Escribir la tabla de contenido a mano al terminar el informe.$q$),
   0, $q$Los estilos jerárquicos permiten que el procesador de texto reconozca la estructura y genere índices actualizables.$q$,
   jsonb_build_array($q$Correcta: usa una función estructural y evita reprocesos.$q$, $q$Incorrecta: el tamaño visual no crea jerarquía semántica.$q$, $q$Incorrecta: una tabla manual se desactualiza con facilidad.$q$)),
  (2, 'ofi-02', 'ofimatica-documentos', '1-6', 'Procesador de texto: estructura y colaboracion',
   $q$Una institución educativa prepara un informe de seguimiento académico para entregar a coordinación y familias. El documento debe reunir portada, tabla de contenido, capítulos con títulos jerarquizados, evidencias de avance, comentarios de revisión y una versión final en PDF. Varios docentes editan el archivo de manera simultánea y se requiere conservar trazabilidad de cambios sin perder formato.$q$,
   2, $q$Si tres docentes deben revisar el informe sin sobrescribir aportes, ¿qué opción es más adecuada?$q$,
   jsonb_build_array($q$Activar control de cambios y usar comentarios vinculados a fragmentos específicos.$q$, $q$Enviar copias separadas por correo para unirlas manualmente al final.$q$, $q$Pedir que todos escriban en color distinto sin registrar revisiones.$q$),
   0, $q$El control de cambios y los comentarios conservan autoría, discusión y decisiones de edición.$q$,
   jsonb_build_array($q$Correcta: facilita trazabilidad y revisión ordenada.$q$, $q$Incorrecta: multiplica versiones y aumenta errores.$q$, $q$Incorrecta: el color no reemplaza registro ni aceptación de cambios.$q$)),
  (3, 'ofi-03', 'ofimatica-documentos', '1-6', 'Procesador de texto: estructura y colaboracion',
   $q$Una institución educativa prepara un informe de seguimiento académico para entregar a coordinación y familias. El documento debe reunir portada, tabla de contenido, capítulos con títulos jerarquizados, evidencias de avance, comentarios de revisión y una versión final en PDF. Varios docentes editan el archivo de manera simultánea y se requiere conservar trazabilidad de cambios sin perder formato.$q$,
   3, $q$¿Cuál práctica mejora la accesibilidad de una guía digital para estudiantes con lectores de pantalla?$q$,
   jsonb_build_array($q$Usar encabezados reales, texto alternativo en imágenes y enlaces descriptivos.$q$, $q$Convertir todo el contenido en una imagen para conservar el diseño.$q$, $q$Usar únicamente colores para indicar información importante.$q$),
   0, $q$La accesibilidad exige estructura, alternativas textuales y señales que no dependan solo de percepción visual.$q$,
   jsonb_build_array($q$Correcta: mejora navegación y comprensión con apoyos tecnológicos.$q$, $q$Incorrecta: una imagen bloquea lectura y búsqueda del texto.$q$, $q$Incorrecta: el color por sí solo excluye a algunos usuarios.$q$)),
  (4, 'ofi-04', 'ofimatica-documentos', '1-6', 'Procesador de texto: estructura y colaboracion',
   $q$Una institución educativa prepara un informe de seguimiento académico para entregar a coordinación y familias. El documento debe reunir portada, tabla de contenido, capítulos con títulos jerarquizados, evidencias de avance, comentarios de revisión y una versión final en PDF. Varios docentes editan el archivo de manera simultánea y se requiere conservar trazabilidad de cambios sin perder formato.$q$,
   4, $q$Antes de enviar el informe final a familias, ¿qué formato reduce cambios accidentales de diseño?$q$,
   jsonb_build_array($q$Exportar una copia en PDF para distribución.$q$, $q$Enviar el archivo editable original a todos los destinatarios.$q$, $q$Pegar capturas de pantalla del documento en el correo.$q$),
   0, $q$El PDF conserva presentación y limita ediciones no intencionales durante la distribución.$q$,
   jsonb_build_array($q$Correcta: es adecuado para publicación final.$q$, $q$Incorrecta: el editable se altera fácilmente.$q$, $q$Incorrecta: las capturas dificultan búsqueda y accesibilidad.$q$)),
  (5, 'ofi-05', 'ofimatica-documentos', '1-6', 'Procesador de texto: estructura y colaboracion',
   $q$Una institución educativa prepara un informe de seguimiento académico para entregar a coordinación y familias. El documento debe reunir portada, tabla de contenido, capítulos con títulos jerarquizados, evidencias de avance, comentarios de revisión y una versión final en PDF. Varios docentes editan el archivo de manera simultánea y se requiere conservar trazabilidad de cambios sin perder formato.$q$,
   5, $q$¿Qué decisión es más adecuada para citar fuentes usadas en una guía docente?$q$,
   jsonb_build_array($q$Usar referencias consistentes e indicar autor, año, título y fuente consultada.$q$, $q$Copiar fragmentos de internet sin referencia si son educativos.$q$, $q$Poner solo el enlace principal al final sin relacionarlo con las ideas usadas.$q$),
   0, $q$La citación protege derechos de autor y permite verificar la procedencia de la información.$q$,
   jsonb_build_array($q$Correcta: cumple criterios de trazabilidad académica.$q$, $q$Incorrecta: el uso educativo no elimina la obligación de citar.$q$, $q$Incorrecta: un enlace aislado no documenta cada fuente usada.$q$)),
  (6, 'ofi-06', 'ofimatica-documentos', '1-6', 'Procesador de texto: estructura y colaboracion',
   $q$Una institución educativa prepara un informe de seguimiento académico para entregar a coordinación y familias. El documento debe reunir portada, tabla de contenido, capítulos con títulos jerarquizados, evidencias de avance, comentarios de revisión y una versión final en PDF. Varios docentes editan el archivo de manera simultánea y se requiere conservar trazabilidad de cambios sin perder formato.$q$,
   6, $q$Si el documento tiene saltos inesperados de página, ¿qué revisión inicial es más pertinente?$q$,
   jsonb_build_array($q$Mostrar marcas de formato y revisar saltos de sección, párrafo y página.$q$, $q$Borrar todo el documento y volver a copiarlo sin formato.$q$, $q$Cambiar la fuente completa hasta que el salto desaparezca.$q$),
   0, $q$Las marcas de formato permiten identificar elementos invisibles que afectan la maquetación.$q$,
   jsonb_build_array($q$Correcta: diagnostica la causa del problema.$q$, $q$Incorrecta: puede eliminar estructura útil.$q$, $q$Incorrecta: cambia apariencia sin resolver la causa.$q$)),
  (7, 'ofi-07', 'ofimatica-hojas', '7-16', 'Hojas de calculo: datos, formulas y graficos',
   $q$La coordinación académica consolida una hoja de cálculo con asistencia, calificaciones, entregas de actividades y observaciones por grupo. El objetivo es identificar estudiantes con riesgo, calcular porcentajes, filtrar información por sede y generar gráficos comprensibles para el consejo académico. Algunos docentes han escrito números como texto, mezclado nombres de columnas y duplicado registros.$q$,
   7, $q$Para calcular el porcentaje de asistencia de un estudiante, ¿qué fórmula representa mejor la relación?$q$,
   jsonb_build_array($q$Clases asistidas dividido entre clases programadas, con formato de porcentaje.$q$, $q$Clases programadas menos clases asistidas, con formato de moneda.$q$, $q$Promedio de nombres y observaciones de la fila.$q$),
   0, $q$Un porcentaje expresa la parte asistida respecto del total programado.$q$,
   jsonb_build_array($q$Correcta: usa una relación proporcional.$q$, $q$Incorrecta: calcula ausencias, no porcentaje de asistencia.$q$, $q$Incorrecta: texto no se promedia para este indicador.$q$)),
  (8, 'ofi-08', 'ofimatica-hojas', '7-16', 'Hojas de calculo: datos, formulas y graficos',
   $q$La coordinación académica consolida una hoja de cálculo con asistencia, calificaciones, entregas de actividades y observaciones por grupo. El objetivo es identificar estudiantes con riesgo, calcular porcentajes, filtrar información por sede y generar gráficos comprensibles para el consejo académico. Algunos docentes han escrito números como texto, mezclado nombres de columnas y duplicado registros.$q$,
   8, $q$¿Qué función permite sumar valores que cumplen una condición, por ejemplo ausencias del grado sexto?$q$,
   jsonb_build_array($q$SUMAR.SI o SUMIFS, según la cantidad de criterios.$q$, $q$CONCATENAR, porque une textos de varias celdas.$q$, $q$MAYUSC, porque transforma texto en mayúsculas.$q$),
   0, $q$Las funciones condicionales agregan datos filtrados por uno o varios criterios.$q$,
   jsonb_build_array($q$Correcta: responde al cálculo condicionado.$q$, $q$Incorrecta: concatenar no suma valores.$q$, $q$Incorrecta: cambiar mayúsculas no analiza datos.$q$)),
  (9, 'ofi-09', 'ofimatica-hojas', '7-16', 'Hojas de calculo: datos, formulas y graficos',
   $q$La coordinación académica consolida una hoja de cálculo con asistencia, calificaciones, entregas de actividades y observaciones por grupo. El objetivo es identificar estudiantes con riesgo, calcular porcentajes, filtrar información por sede y generar gráficos comprensibles para el consejo académico. Algunos docentes han escrito números como texto, mezclado nombres de columnas y duplicado registros.$q$,
   9, $q$Si una fórmula debe copiarse hacia abajo conservando fija la celda del porcentaje mínimo, ¿qué referencia conviene usar?$q$,
   jsonb_build_array($q$Referencia absoluta, por ejemplo $B$2.$q$, $q$Referencia relativa sin signos de dólar en todos los casos.$q$, $q$Una celda combinada para que la fórmula no cambie.$q$),
   0, $q$La referencia absoluta mantiene fija una celda al copiar fórmulas.$q$,
   jsonb_build_array($q$Correcta: evita desplazamientos no deseados.$q$, $q$Incorrecta: la referencia relativa cambia al copiar.$q$, $q$Incorrecta: combinar celdas no controla referencias.$q$)),
  (10, 'ofi-10', 'ofimatica-hojas', '7-16', 'Hojas de calculo: datos, formulas y graficos',
   $q$La coordinación académica consolida una hoja de cálculo con asistencia, calificaciones, entregas de actividades y observaciones por grupo. El objetivo es identificar estudiantes con riesgo, calcular porcentajes, filtrar información por sede y generar gráficos comprensibles para el consejo académico. Algunos docentes han escrito números como texto, mezclado nombres de columnas y duplicado registros.$q$,
   10, $q$¿Qué procedimiento ayuda a detectar registros duplicados de estudiantes?$q$,
   jsonb_build_array($q$Usar una herramienta de quitar duplicados o formato condicional sobre el identificador.$q$, $q$Ordenar por color de fuente sin revisar identificadores.$q$, $q$Cambiar el ancho de columnas para ver más nombres.$q$),
   0, $q$Los duplicados deben buscarse con campos clave como documento, código o correo institucional.$q$,
   jsonb_build_array($q$Correcta: identifica repeticiones con criterio verificable.$q$, $q$Incorrecta: el color no define duplicidad.$q$, $q$Incorrecta: ver más texto no garantiza detección.$q$)),
  (11, 'ofi-11', 'ofimatica-hojas', '7-16', 'Hojas de calculo: datos, formulas y graficos',
   $q$La coordinación académica consolida una hoja de cálculo con asistencia, calificaciones, entregas de actividades y observaciones por grupo. El objetivo es identificar estudiantes con riesgo, calcular porcentajes, filtrar información por sede y generar gráficos comprensibles para el consejo académico. Algunos docentes han escrito números como texto, mezclado nombres de columnas y duplicado registros.$q$,
   11, $q$¿Qué gráfico es más adecuado para comparar el porcentaje de asistencia entre cursos?$q$,
   jsonb_build_array($q$Gráfico de barras o columnas con escala clara y etiquetas pertinentes.$q$, $q$Gráfico circular con demasiadas categorías y porcentajes pequeños.$q$, $q$Imagen decorativa sin eje ni valores.$q$),
   0, $q$Las barras facilitan comparación entre categorías discretas como cursos.$q$,
   jsonb_build_array($q$Correcta: permite comparar valores de forma directa.$q$, $q$Incorrecta: muchos sectores dificultan lectura.$q$, $q$Incorrecta: una imagen sin datos no comunica evidencia.$q$)),
  (12, 'ofi-12', 'ofimatica-hojas', '7-16', 'Hojas de calculo: datos, formulas y graficos',
   $q$La coordinación académica consolida una hoja de cálculo con asistencia, calificaciones, entregas de actividades y observaciones por grupo. El objetivo es identificar estudiantes con riesgo, calcular porcentajes, filtrar información por sede y generar gráficos comprensibles para el consejo académico. Algunos docentes han escrito números como texto, mezclado nombres de columnas y duplicado registros.$q$,
   12, $q$Si las notas aparecen alineadas a la izquierda y no se calculan, ¿qué causa es probable?$q$,
   jsonb_build_array($q$Los números fueron ingresados como texto y deben convertirse a formato numérico.$q$, $q$La hoja no permite operaciones matemáticas en ninguna celda.$q$, $q$El problema se resuelve cambiando el color de relleno.$q$),
   0, $q$Cuando los números se guardan como texto, las operaciones pueden fallar o producir resultados incorrectos.$q$,
   jsonb_build_array($q$Correcta: identifica un problema frecuente de tipo de dato.$q$, $q$Incorrecta: las hojas sí calculan datos numéricos.$q$, $q$Incorrecta: el color no cambia el tipo de dato.$q$)),
  (13, 'ofi-13', 'ofimatica-hojas', '7-16', 'Hojas de calculo: datos, formulas y graficos',
   $q$La coordinación académica consolida una hoja de cálculo con asistencia, calificaciones, entregas de actividades y observaciones por grupo. El objetivo es identificar estudiantes con riesgo, calcular porcentajes, filtrar información por sede y generar gráficos comprensibles para el consejo académico. Algunos docentes han escrito números como texto, mezclado nombres de columnas y duplicado registros.$q$,
   13, $q$¿Qué herramienta permite ver solo estudiantes con asistencia inferior al 80 % sin borrar datos?$q$,
   jsonb_build_array($q$Aplicar filtros sobre la columna de asistencia.$q$, $q$Eliminar todas las filas con asistencia alta.$q$, $q$Ocultar la hoja completa para protegerla.$q$),
   0, $q$Los filtros muestran subconjuntos de datos sin modificar la tabla original.$q$,
   jsonb_build_array($q$Correcta: permite análisis reversible.$q$, $q$Incorrecta: borrar filas destruye información.$q$, $q$Incorrecta: ocultar la hoja no analiza registros.$q$)),
  (14, 'ofi-14', 'ofimatica-hojas', '7-16', 'Hojas de calculo: datos, formulas y graficos',
   $q$La coordinación académica consolida una hoja de cálculo con asistencia, calificaciones, entregas de actividades y observaciones por grupo. El objetivo es identificar estudiantes con riesgo, calcular porcentajes, filtrar información por sede y generar gráficos comprensibles para el consejo académico. Algunos docentes han escrito números como texto, mezclado nombres de columnas y duplicado registros.$q$,
   14, $q$¿Cuál es una buena práctica antes de compartir una hoja con datos estudiantiles?$q$,
   jsonb_build_array($q$Revisar permisos, ocultar o anonimizar datos sensibles y compartir solo con quienes lo requieren.$q$, $q$Publicarla con enlace abierto para ahorrar solicitudes de acceso.$q$, $q$Enviar capturas por mensajería personal a cualquier acudiente.$q$),
   0, $q$La información educativa requiere control de acceso y minimización de datos personales.$q$,
   jsonb_build_array($q$Correcta: protege confidencialidad institucional.$q$, $q$Incorrecta: un enlace abierto expone datos sensibles.$q$, $q$Incorrecta: canales personales aumentan riesgos de privacidad.$q$)),
  (15, 'ofi-15', 'ofimatica-hojas', '7-16', 'Hojas de calculo: datos, formulas y graficos',
   $q$La coordinación académica consolida una hoja de cálculo con asistencia, calificaciones, entregas de actividades y observaciones por grupo. El objetivo es identificar estudiantes con riesgo, calcular porcentajes, filtrar información por sede y generar gráficos comprensibles para el consejo académico. Algunos docentes han escrito números como texto, mezclado nombres de columnas y duplicado registros.$q$,
   15, $q$¿Qué uso de tabla dinámica es pertinente para el consejo académico?$q$,
   jsonb_build_array($q$Resumir promedios o conteos por curso, sede o nivel sin alterar los datos fuente.$q$, $q$Reemplazar todos los registros individuales por una sola imagen.$q$, $q$Evitar cualquier agrupación y revisar fila por fila siempre.$q$),
   0, $q$Las tablas dinámicas resumen grandes conjuntos de datos por categorías relevantes.$q$,
   jsonb_build_array($q$Correcta: permite análisis agregado y flexible.$q$, $q$Incorrecta: una imagen no conserva análisis dinámico.$q$, $q$Incorrecta: revisar fila por fila es poco eficiente.$q$)),
  (16, 'ofi-16', 'ofimatica-hojas', '7-16', 'Hojas de calculo: datos, formulas y graficos',
   $q$La coordinación académica consolida una hoja de cálculo con asistencia, calificaciones, entregas de actividades y observaciones por grupo. El objetivo es identificar estudiantes con riesgo, calcular porcentajes, filtrar información por sede y generar gráficos comprensibles para el consejo académico. Algunos docentes han escrito números como texto, mezclado nombres de columnas y duplicado registros.$q$,
   16, $q$¿Qué validación de datos reduce errores al registrar el grado de un estudiante?$q$,
   jsonb_build_array($q$Crear una lista desplegable con los grados permitidos.$q$, $q$Permitir texto libre sin revisión para ahorrar tiempo.$q$, $q$Combinar todas las celdas de grado en una sola.$q$),
   0, $q$La validación mediante listas limita entradas inconsistentes y facilita filtros posteriores.$q$,
   jsonb_build_array($q$Correcta: estandariza los valores capturados.$q$, $q$Incorrecta: el texto libre produce variaciones difíciles de analizar.$q$, $q$Incorrecta: combinar celdas dificulta el registro por fila.$q$)),
  (17, 'ofi-17', 'ofimatica-presentaciones', '17-24', 'Presentaciones: comunicacion visual y exposicion',
   $q$Un docente debe presentar al consejo de padres los resultados de un proyecto pedagógico. Tiene quince minutos, datos de asistencia, fotografías de actividades y conclusiones preliminares. La presentación debe ser clara, sobria y comprensible para familias con distintos niveles de familiaridad tecnológica, evitando saturación de texto y respetando privacidad de estudiantes.$q$,
   17, $q$¿Qué principio mejora la claridad de una diapositiva con resultados?$q$,
   jsonb_build_array($q$Presentar una idea principal por diapositiva, con datos legibles y texto breve.$q$, $q$Incluir todos los párrafos del informe para no omitir información.$q$, $q$Usar muchas animaciones para mantener atención aunque distraigan.$q$),
   0, $q$Una presentación apoya la exposición; no debe reemplazarla con texto excesivo.$q$,
   jsonb_build_array($q$Correcta: facilita comprensión y exposición oral.$q$, $q$Incorrecta: saturar texto dificulta lectura.$q$, $q$Incorrecta: animaciones excesivas reducen foco.$q$)),
  (18, 'ofi-18', 'ofimatica-presentaciones', '17-24', 'Presentaciones: comunicacion visual y exposicion',
   $q$Un docente debe presentar al consejo de padres los resultados de un proyecto pedagógico. Tiene quince minutos, datos de asistencia, fotografías de actividades y conclusiones preliminares. La presentación debe ser clara, sobria y comprensible para familias con distintos niveles de familiaridad tecnológica, evitando saturación de texto y respetando privacidad de estudiantes.$q$,
   18, $q$¿Qué gráfico conviene insertar si se comparan porcentajes de participación por grado?$q$,
   jsonb_build_array($q$Un gráfico de barras con rótulos claros y fuente de datos indicada.$q$, $q$Un collage de imágenes sin escala numérica.$q$, $q$Una tabla con todos los registros individuales de estudiantes.$q$),
   0, $q$Las barras permiten comparar porcentajes por categorías de forma rápida.$q$,
   jsonb_build_array($q$Correcta: comunica comparación y evidencia.$q$, $q$Incorrecta: las imágenes no muestran proporciones.$q$, $q$Incorrecta: exponer registros individuales puede vulnerar privacidad.$q$)),
  (19, 'ofi-19', 'ofimatica-presentaciones', '17-24', 'Presentaciones: comunicacion visual y exposicion',
   $q$Un docente debe presentar al consejo de padres los resultados de un proyecto pedagógico. Tiene quince minutos, datos de asistencia, fotografías de actividades y conclusiones preliminares. La presentación debe ser clara, sobria y comprensible para familias con distintos niveles de familiaridad tecnológica, evitando saturación de texto y respetando privacidad de estudiantes.$q$,
   19, $q$¿Qué decisión protege mejor la identidad de estudiantes en fotografías?$q$,
   jsonb_build_array($q$Usar imágenes autorizadas o planos donde no se identifique a menores sin permiso.$q$, $q$Publicar todas las fotos porque fueron tomadas en la escuela.$q$, $q$Agregar el nombre completo de cada estudiante para dar contexto.$q$),
   0, $q$Las imágenes de menores requieren autorización y tratamiento responsable de datos personales.$q$,
   jsonb_build_array($q$Correcta: respeta privacidad y consentimiento.$q$, $q$Incorrecta: el contexto escolar no elimina requisitos de protección.$q$, $q$Incorrecta: nombres completos aumentan exposición.$q$)),
  (20, 'ofi-20', 'ofimatica-presentaciones', '17-24', 'Presentaciones: comunicacion visual y exposicion',
   $q$Un docente debe presentar al consejo de padres los resultados de un proyecto pedagógico. Tiene quince minutos, datos de asistencia, fotografías de actividades y conclusiones preliminares. La presentación debe ser clara, sobria y comprensible para familias con distintos niveles de familiaridad tecnológica, evitando saturación de texto y respetando privacidad de estudiantes.$q$,
   20, $q$¿Cuál práctica mejora la legibilidad del texto proyectado?$q$,
   jsonb_build_array($q$Usar contraste suficiente, tamaño de letra legible y pocas líneas por diapositiva.$q$, $q$Usar letra muy pequeña para incluir todo el contenido.$q$, $q$Poner texto claro sobre fondo claro para que se vea elegante.$q$),
   0, $q$La legibilidad depende de tamaño, contraste y cantidad de información visible.$q$,
   jsonb_build_array($q$Correcta: considera condiciones reales de proyección.$q$, $q$Incorrecta: la letra pequeña excluye a parte del público.$q$, $q$Incorrecta: bajo contraste dificulta lectura.$q$)),
  (21, 'ofi-21', 'ofimatica-presentaciones', '17-24', 'Presentaciones: comunicacion visual y exposicion',
   $q$Un docente debe presentar al consejo de padres los resultados de un proyecto pedagógico. Tiene quince minutos, datos de asistencia, fotografías de actividades y conclusiones preliminares. La presentación debe ser clara, sobria y comprensible para familias con distintos niveles de familiaridad tecnológica, evitando saturación de texto y respetando privacidad de estudiantes.$q$,
   21, $q$Si debe entregar la presentación para consulta posterior, ¿qué opción es más apropiada?$q$,
   jsonb_build_array($q$Exportar una versión PDF y compartirla por canal institucional con permisos adecuados.$q$, $q$Compartir el archivo editable públicamente en redes sociales.$q$, $q$Enviar solo una foto borrosa de cada diapositiva.$q$),
   0, $q$El PDF facilita lectura y reduce modificaciones, mientras los permisos controlan acceso.$q$,
   jsonb_build_array($q$Correcta: combina disponibilidad y control.$q$, $q$Incorrecta: acceso público expone información.$q$, $q$Incorrecta: fotos borrosas no son material consultable.$q$)),
  (22, 'ofi-22', 'ofimatica-presentaciones', '17-24', 'Presentaciones: comunicacion visual y exposicion',
   $q$Un docente debe presentar al consejo de padres los resultados de un proyecto pedagógico. Tiene quince minutos, datos de asistencia, fotografías de actividades y conclusiones preliminares. La presentación debe ser clara, sobria y comprensible para familias con distintos niveles de familiaridad tecnológica, evitando saturación de texto y respetando privacidad de estudiantes.$q$,
   22, $q$¿Qué recurso ayuda a explicar una tendencia sin exagerar conclusiones?$q$,
   jsonb_build_array($q$Mostrar el gráfico con periodo, muestra y limitaciones de los datos.$q$, $q$Eliminar datos que no apoyan la conclusión deseada.$q$, $q$Cambiar la escala para que una diferencia pequeña parezca enorme.$q$),
   0, $q$La comunicación responsable presenta evidencia, contexto y límites de interpretación.$q$,
   jsonb_build_array($q$Correcta: evita lecturas engañosas.$q$, $q$Incorrecta: omitir datos distorsiona resultados.$q$, $q$Incorrecta: manipular escala puede inducir error.$q$)),
  (23, 'ofi-23', 'ofimatica-presentaciones', '17-24', 'Presentaciones: comunicacion visual y exposicion',
   $q$Un docente debe presentar al consejo de padres los resultados de un proyecto pedagógico. Tiene quince minutos, datos de asistencia, fotografías de actividades y conclusiones preliminares. La presentación debe ser clara, sobria y comprensible para familias con distintos niveles de familiaridad tecnológica, evitando saturación de texto y respetando privacidad de estudiantes.$q$,
   23, $q$¿Cómo debe usarse una plantilla institucional de diapositivas?$q$,
   jsonb_build_array($q$Manteniendo identidad visual, consistencia y adaptación al propósito de la exposición.$q$, $q$Cambiando cada diapositiva a colores distintos sin criterio.$q$, $q$Usándola para reemplazar el análisis por decoración.$q$),
   0, $q$Las plantillas dan coherencia visual, pero el contenido debe seguir siendo pertinente.$q$,
   jsonb_build_array($q$Correcta: equilibra identidad y comunicación.$q$, $q$Incorrecta: la inconsistencia distrae.$q$, $q$Incorrecta: el diseño no sustituye evidencia.$q$)),
  (24, 'ofi-24', 'ofimatica-presentaciones', '17-24', 'Presentaciones: comunicacion visual y exposicion',
   $q$Un docente debe presentar al consejo de padres los resultados de un proyecto pedagógico. Tiene quince minutos, datos de asistencia, fotografías de actividades y conclusiones preliminares. La presentación debe ser clara, sobria y comprensible para familias con distintos niveles de familiaridad tecnológica, evitando saturación de texto y respetando privacidad de estudiantes.$q$,
   24, $q$¿Qué acción favorece una exposición ajustada al tiempo disponible?$q$,
   jsonb_build_array($q$Ensayar, priorizar ideas clave y dejar anexos para detalles secundarios.$q$, $q$Leer todas las diapositivas completas sin omitir nada.$q$, $q$Agregar más diapositivas para cubrir cualquier posible pregunta.$q$),
   0, $q$La gestión del tiempo exige seleccionar información esencial y prever material complementario.$q$,
   jsonb_build_array($q$Correcta: organiza comunicación eficaz.$q$, $q$Incorrecta: leer todo suele exceder el tiempo.$q$, $q$Incorrecta: más diapositivas no garantizan claridad.$q$)),
  (25, 'ofi-25', 'ofimatica-correo', '25-32', 'Correo, calendario y colaboracion institucional',
   $q$La institución adopta un correo institucional y una plataforma colaborativa para enviar citaciones, programar reuniones, compartir actas y coordinar tareas de área. Han surgido problemas por mensajes duplicados, archivos adjuntos pesados, invitaciones sin agenda, respuestas enviadas a destinatarios equivocados y documentos compartidos con permisos excesivos.$q$,
   25, $q$¿Qué práctica mejora una citación enviada por correo institucional?$q$,
   jsonb_build_array($q$Asunto claro, fecha, hora, propósito, enlace o lugar y responsables definidos.$q$, $q$Asunto genérico como “Importante” sin información adicional.$q$, $q$Enviar varios mensajes incompletos para recordar detalles por separado.$q$),
   0, $q$Una comunicación institucional debe ser precisa y accionable para sus destinatarios.$q$,
   jsonb_build_array($q$Correcta: reduce confusiones y reprocesos.$q$, $q$Incorrecta: un asunto ambiguo dificulta priorización.$q$, $q$Incorrecta: fragmentar información aumenta errores.$q$)),
  (26, 'ofi-26', 'ofimatica-correo', '25-32', 'Correo, calendario y colaboracion institucional',
   $q$La institución adopta un correo institucional y una plataforma colaborativa para enviar citaciones, programar reuniones, compartir actas y coordinar tareas de área. Han surgido problemas por mensajes duplicados, archivos adjuntos pesados, invitaciones sin agenda, respuestas enviadas a destinatarios equivocados y documentos compartidos con permisos excesivos.$q$,
   26, $q$¿Cuándo es preferible usar CCO en un correo masivo a familias?$q$,
   jsonb_build_array($q$Cuando se requiere proteger direcciones de correo de los destinatarios entre sí.$q$, $q$Cuando se busca que todos respondan a toda la lista.$q$, $q$Cuando se quiere ocultar el mensaje al remitente principal.$q$),
   0, $q$CCO protege la privacidad de destinatarios en envíos masivos.$q$,
   jsonb_build_array($q$Correcta: evita exposición innecesaria de correos.$q$, $q$Incorrecta: responder a todos puede saturar y exponer datos.$q$, $q$Incorrecta: el remitente conserva el envío.$q$)),
  (27, 'ofi-27', 'ofimatica-correo', '25-32', 'Correo, calendario y colaboracion institucional',
   $q$La institución adopta un correo institucional y una plataforma colaborativa para enviar citaciones, programar reuniones, compartir actas y coordinar tareas de área. Han surgido problemas por mensajes duplicados, archivos adjuntos pesados, invitaciones sin agenda, respuestas enviadas a destinatarios equivocados y documentos compartidos con permisos excesivos.$q$,
   27, $q$Para coordinar una reunión virtual, ¿qué elemento debe incluir la invitación de calendario?$q$,
   jsonb_build_array($q$Fecha, hora, zona horaria si aplica, enlace, agenda y participantes requeridos.$q$, $q$Solo un mensaje informal indicando que se conecten cuando puedan.$q$, $q$Un archivo adjunto sin hora ni enlace de ingreso.$q$),
   0, $q$Una invitación completa permite planear asistencia y preparar la reunión.$q$,
   jsonb_build_array($q$Correcta: contiene información operativa y propósito.$q$, $q$Incorrecta: no permite coordinación real.$q$, $q$Incorrecta: falta información básica de conexión.$q$)),
  (28, 'ofi-28', 'ofimatica-correo', '25-32', 'Correo, calendario y colaboracion institucional',
   $q$La institución adopta un correo institucional y una plataforma colaborativa para enviar citaciones, programar reuniones, compartir actas y coordinar tareas de área. Han surgido problemas por mensajes duplicados, archivos adjuntos pesados, invitaciones sin agenda, respuestas enviadas a destinatarios equivocados y documentos compartidos con permisos excesivos.$q$,
   28, $q$Si un acta debe ser revisada por el equipo sin permitir edición accidental de otros, ¿qué permiso conviene asignar?$q$,
   jsonb_build_array($q$Permiso de comentar o sugerir, según la plataforma.$q$, $q$Permiso público de edición para cualquier persona con enlace.$q$, $q$Enviar contraseña por el mismo correo a destinatarios desconocidos.$q$),
   0, $q$Los permisos deben corresponder al rol de cada participante en el documento.$q$,
   jsonb_build_array($q$Correcta: permite retroalimentar sin alterar el original.$q$, $q$Incorrecta: edición pública genera riesgo de pérdida o exposición.$q$, $q$Incorrecta: compartir credenciales inseguras vulnera acceso.$q$)),
  (29, 'ofi-29', 'ofimatica-correo', '25-32', 'Correo, calendario y colaboracion institucional',
   $q$La institución adopta un correo institucional y una plataforma colaborativa para enviar citaciones, programar reuniones, compartir actas y coordinar tareas de área. Han surgido problemas por mensajes duplicados, archivos adjuntos pesados, invitaciones sin agenda, respuestas enviadas a destinatarios equivocados y documentos compartidos con permisos excesivos.$q$,
   29, $q$¿Qué acción es más adecuada ante un archivo adjunto muy pesado?$q$,
   jsonb_build_array($q$Subirlo al repositorio institucional y compartir enlace con permisos controlados.$q$, $q$Dividirlo en muchos correos sin identificar versiones.$q$, $q$Usar una cuenta personal pública para alojar datos sensibles.$q$),
   0, $q$Los enlaces institucionales reducen peso del correo y permiten controlar acceso.$q$,
   jsonb_build_array($q$Correcta: mejora distribución y seguridad.$q$, $q$Incorrecta: fragmentar dificulta seguimiento.$q$, $q$Incorrecta: cuentas personales públicas exponen información.$q$)),
  (30, 'ofi-30', 'ofimatica-correo', '25-32', 'Correo, calendario y colaboracion institucional',
   $q$La institución adopta un correo institucional y una plataforma colaborativa para enviar citaciones, programar reuniones, compartir actas y coordinar tareas de área. Han surgido problemas por mensajes duplicados, archivos adjuntos pesados, invitaciones sin agenda, respuestas enviadas a destinatarios equivocados y documentos compartidos con permisos excesivos.$q$,
   30, $q$¿Qué debe hacer un docente antes de responder “Responder a todos”?$q$,
   jsonb_build_array($q$Verificar si todos los destinatarios necesitan recibir la respuesta.$q$, $q$Usarlo siempre para demostrar transparencia.$q$, $q$Agregar nuevos destinatarios sin revisar pertinencia.$q$),
   0, $q$Responder a todos debe usarse solo cuando la respuesta es relevante para todo el grupo.$q$,
   jsonb_build_array($q$Correcta: evita ruido y exposición innecesaria.$q$, $q$Incorrecta: transparencia no implica saturar correos.$q$, $q$Incorrecta: agregar destinatarios puede vulnerar privacidad.$q$)),
  (31, 'ofi-31', 'ofimatica-correo', '25-32', 'Correo, calendario y colaboracion institucional',
   $q$La institución adopta un correo institucional y una plataforma colaborativa para enviar citaciones, programar reuniones, compartir actas y coordinar tareas de área. Han surgido problemas por mensajes duplicados, archivos adjuntos pesados, invitaciones sin agenda, respuestas enviadas a destinatarios equivocados y documentos compartidos con permisos excesivos.$q$,
   31, $q$¿Qué uso de carpetas compartidas favorece la gestión documental del área?$q$,
   jsonb_build_array($q$Estructurar carpetas por año, componente y tipo de documento con nombres consistentes.$q$, $q$Guardar todo en una sola carpeta llamada “varios”.$q$, $q$Duplicar cada archivo en carpetas personales sin control de versión.$q$),
   0, $q$Una estructura consistente facilita búsqueda, permisos y continuidad institucional.$q$,
   jsonb_build_array($q$Correcta: mejora organización y recuperación.$q$, $q$Incorrecta: “varios” dificulta ubicación.$q$, $q$Incorrecta: copias dispersas causan versiones contradictorias.$q$)),
  (32, 'ofi-32', 'ofimatica-correo', '25-32', 'Correo, calendario y colaboracion institucional',
   $q$La institución adopta un correo institucional y una plataforma colaborativa para enviar citaciones, programar reuniones, compartir actas y coordinar tareas de área. Han surgido problemas por mensajes duplicados, archivos adjuntos pesados, invitaciones sin agenda, respuestas enviadas a destinatarios equivocados y documentos compartidos con permisos excesivos.$q$,
   32, $q$Si llega un correo con enlace extraño solicitando contraseña institucional, ¿cuál es la respuesta correcta?$q$,
   jsonb_build_array($q$No ingresar credenciales, verificar remitente y reportar por el canal institucional.$q$, $q$Ingresar la contraseña para evitar bloqueo de cuenta.$q$, $q$Reenviar el enlace a todos para preguntar si también lo recibieron.$q$),
   0, $q$La solicitud sospechosa de credenciales es un indicador común de phishing.$q$,
   jsonb_build_array($q$Correcta: protege la cuenta y activa reporte.$q$, $q$Incorrecta: entregar credenciales compromete sistemas.$q$, $q$Incorrecta: reenviar el enlace puede propagar el riesgo.$q$)),
  (33, 'ofi-33', 'ofimatica-seguridad', '33-40', 'Seguridad digital, privacidad y ciudadania',
   $q$Durante una jornada institucional, los docentes analizan incidentes recientes: contraseñas compartidas entre compañeros, publicación de listados con datos personales, uso de memorias USB desconocidas y formularios en línea que recolectan más información de la necesaria. El rector solicita fortalecer hábitos de seguridad digital y ciudadanía responsable sin bloquear el uso pedagógico de las herramientas.$q$,
   33, $q$¿Qué característica debe tener una contraseña institucional segura?$q$,
   jsonb_build_array($q$Ser larga, única y difícil de adivinar, idealmente gestionada con un administrador confiable.$q$, $q$Ser el nombre del colegio para que nadie la olvide.$q$, $q$Compartirse entre docentes del área para agilizar trámites.$q$),
   0, $q$Las contraseñas seguras son únicas, robustas y no deben compartirse.$q$,
   jsonb_build_array($q$Correcta: reduce riesgo de acceso no autorizado.$q$, $q$Incorrecta: nombres obvios son vulnerables.$q$, $q$Incorrecta: compartir contraseñas elimina responsabilidad individual.$q$)),
  (34, 'ofi-34', 'ofimatica-seguridad', '33-40', 'Seguridad digital, privacidad y ciudadania',
   $q$Durante una jornada institucional, los docentes analizan incidentes recientes: contraseñas compartidas entre compañeros, publicación de listados con datos personales, uso de memorias USB desconocidas y formularios en línea que recolectan más información de la necesaria. El rector solicita fortalecer hábitos de seguridad digital y ciudadanía responsable sin bloquear el uso pedagógico de las herramientas.$q$,
   34, $q$¿Qué medida agrega una capa de seguridad al iniciar sesión?$q$,
   jsonb_build_array($q$Activar autenticación multifactor cuando esté disponible.$q$, $q$Usar la misma contraseña en todos los servicios.$q$, $q$Guardar claves en notas visibles del computador compartido.$q$),
   0, $q$La autenticación multifactor reduce el impacto de una contraseña comprometida.$q$,
   jsonb_build_array($q$Correcta: exige una verificación adicional.$q$, $q$Incorrecta: reutilizar claves amplifica riesgos.$q$, $q$Incorrecta: dejar claves visibles facilita acceso indebido.$q$)),
  (35, 'ofi-35', 'ofimatica-seguridad', '33-40', 'Seguridad digital, privacidad y ciudadania',
   $q$Durante una jornada institucional, los docentes analizan incidentes recientes: contraseñas compartidas entre compañeros, publicación de listados con datos personales, uso de memorias USB desconocidas y formularios en línea que recolectan más información de la necesaria. El rector solicita fortalecer hábitos de seguridad digital y ciudadanía responsable sin bloquear el uso pedagógico de las herramientas.$q$,
   35, $q$¿Qué principio debe guiar un formulario para familias?$q$,
   jsonb_build_array($q$Solicitar solo los datos necesarios para el propósito informado.$q$, $q$Pedir datos sensibles por si se necesitan en el futuro.$q$, $q$Hacer obligatorio todo campo aunque no sea pertinente.$q$),
   0, $q$La minimización de datos reduce riesgos y respeta privacidad.$q$,
   jsonb_build_array($q$Correcta: limita recolección a lo necesario.$q$, $q$Incorrecta: recolectar por si acaso aumenta riesgo.$q$, $q$Incorrecta: obligatoriedad sin pertinencia es inadecuada.$q$)),
  (36, 'ofi-36', 'ofimatica-seguridad', '33-40', 'Seguridad digital, privacidad y ciudadania',
   $q$Durante una jornada institucional, los docentes analizan incidentes recientes: contraseñas compartidas entre compañeros, publicación de listados con datos personales, uso de memorias USB desconocidas y formularios en línea que recolectan más información de la necesaria. El rector solicita fortalecer hábitos de seguridad digital y ciudadanía responsable sin bloquear el uso pedagógico de las herramientas.$q$,
   36, $q$¿Qué acción es prudente antes de abrir una memoria USB desconocida?$q$,
   jsonb_build_array($q$Evitar usarla o revisarla según protocolo institucional de seguridad.$q$, $q$Abrir todos los archivos para identificar al dueño.$q$, $q$Copiar su contenido a la red institucional para que no se pierda.$q$),
   0, $q$Los dispositivos desconocidos pueden contener malware o información no autorizada.$q$,
   jsonb_build_array($q$Correcta: prioriza prevención y protocolo.$q$, $q$Incorrecta: abrir archivos aumenta riesgo.$q$, $q$Incorrecta: copiar contenido puede propagar amenazas.$q$)),
  (37, 'ofi-37', 'ofimatica-seguridad', '33-40', 'Seguridad digital, privacidad y ciudadania',
   $q$Durante una jornada institucional, los docentes analizan incidentes recientes: contraseñas compartidas entre compañeros, publicación de listados con datos personales, uso de memorias USB desconocidas y formularios en línea que recolectan más información de la necesaria. El rector solicita fortalecer hábitos de seguridad digital y ciudadanía responsable sin bloquear el uso pedagógico de las herramientas.$q$,
   37, $q$¿Qué práctica es más responsable al publicar resultados académicos?$q$,
   jsonb_build_array($q$Usar canales privados y evitar listados públicos con nombres y calificaciones.$q$, $q$Pegar en redes sociales una tabla completa para que todos consulten rápido.$q$, $q$Publicar documentos de identidad para evitar confusiones.$q$),
   0, $q$Los resultados académicos son información personal y deben comunicarse por medios adecuados.$q$,
   jsonb_build_array($q$Correcta: respeta privacidad del estudiante.$q$, $q$Incorrecta: redes públicas exponen datos.$q$, $q$Incorrecta: documentos de identidad son datos sensibles.$q$)),
  (38, 'ofi-38', 'ofimatica-seguridad', '33-40', 'Seguridad digital, privacidad y ciudadania',
   $q$Durante una jornada institucional, los docentes analizan incidentes recientes: contraseñas compartidas entre compañeros, publicación de listados con datos personales, uso de memorias USB desconocidas y formularios en línea que recolectan más información de la necesaria. El rector solicita fortalecer hábitos de seguridad digital y ciudadanía responsable sin bloquear el uso pedagógico de las herramientas.$q$,
   38, $q$¿Qué indica que una fuente digital requiere verificación antes de usarse en clase?$q$,
   jsonb_build_array($q$No identifica autor, fecha, entidad responsable ni evidencia verificable.$q$, $q$Presenta referencias claras y coincide con fuentes confiables.$q$, $q$Permite contrastar datos con documentos institucionales.$q$),
   0, $q$La evaluación crítica de fuentes es parte de la ciudadanía digital docente.$q$,
   jsonb_build_array($q$Correcta: ausencia de trazabilidad exige cautela.$q$, $q$Incorrecta: referencias claras aumentan confiabilidad.$q$, $q$Incorrecta: posibilidad de contraste fortalece uso.$q$)),
  (39, 'ofi-39', 'ofimatica-seguridad', '33-40', 'Seguridad digital, privacidad y ciudadania',
   $q$Durante una jornada institucional, los docentes analizan incidentes recientes: contraseñas compartidas entre compañeros, publicación de listados con datos personales, uso de memorias USB desconocidas y formularios en línea que recolectan más información de la necesaria. El rector solicita fortalecer hábitos de seguridad digital y ciudadanía responsable sin bloquear el uso pedagógico de las herramientas.$q$,
   39, $q$¿Qué debe hacerse si se comparte por error un archivo con datos personales?$q$,
   jsonb_build_array($q$Retirar acceso, informar por el canal institucional y seguir el protocolo de incidente.$q$, $q$Ignorarlo si nadie ha reclamado.$q$, $q$Borrar el mensaje propio y no reportar para evitar sanciones.$q$),
   0, $q$Los incidentes de privacidad requieren contención y reporte oportuno.$q$,
   jsonb_build_array($q$Correcta: reduce daño y activa gestión institucional.$q$, $q$Incorrecta: la falta de queja no elimina el riesgo.$q$, $q$Incorrecta: ocultar el incidente agrava consecuencias.$q$)),
  (40, 'ofi-40', 'ofimatica-seguridad', '33-40', 'Seguridad digital, privacidad y ciudadania',
   $q$Durante una jornada institucional, los docentes analizan incidentes recientes: contraseñas compartidas entre compañeros, publicación de listados con datos personales, uso de memorias USB desconocidas y formularios en línea que recolectan más información de la necesaria. El rector solicita fortalecer hábitos de seguridad digital y ciudadanía responsable sin bloquear el uso pedagógico de las herramientas.$q$,
   40, $q$¿Qué conducta demuestra ciudadanía digital en un foro escolar?$q$,
   jsonb_build_array($q$Argumentar con respeto, citar fuentes y proteger información personal.$q$, $q$Compartir capturas privadas para ganar una discusión.$q$, $q$Publicar rumores si parecen importantes para la comunidad.$q$),
   0, $q$La ciudadanía digital combina respeto, verificación y cuidado de datos.$q$,
   jsonb_build_array($q$Correcta: integra ética y comunicación responsable.$q$, $q$Incorrecta: vulnera privacidad.$q$, $q$Incorrecta: difundir rumores desinforma.$q$)),
  (41, 'ofi-41', 'ofimatica-pedagogia', '41-46', 'Uso pedagogico de herramientas digitales',
   $q$El área académica quiere integrar herramientas digitales en una secuencia de aprendizaje. El propósito no es usar tecnología por novedad, sino mejorar comprensión, seguimiento y participación. El equipo debe elegir instrumentos coherentes con los objetivos, prever accesibilidad, evaluar evidencias y ofrecer alternativas cuando algunos estudiantes tienen conectividad limitada.$q$,
   41, $q$¿Qué criterio debe orientar primero la selección de una herramienta digital?$q$,
   jsonb_build_array($q$La relación con el aprendizaje esperado y las condiciones reales del grupo.$q$, $q$Que sea la aplicación más nueva aunque no responda al objetivo.$q$, $q$Que tenga muchas funciones aunque ninguna sea necesaria.$q$),
   0, $q$La herramienta debe estar al servicio del propósito pedagógico y del contexto.$q$,
   jsonb_build_array($q$Correcta: prioriza pertinencia didáctica.$q$, $q$Incorrecta: la novedad no garantiza aprendizaje.$q$, $q$Incorrecta: más funciones pueden aumentar complejidad sin valor.$q$)),
  (42, 'ofi-42', 'ofimatica-pedagogia', '41-46', 'Uso pedagogico de herramientas digitales',
   $q$El área académica quiere integrar herramientas digitales en una secuencia de aprendizaje. El propósito no es usar tecnología por novedad, sino mejorar comprensión, seguimiento y participación. El equipo debe elegir instrumentos coherentes con los objetivos, prever accesibilidad, evaluar evidencias y ofrecer alternativas cuando algunos estudiantes tienen conectividad limitada.$q$,
   42, $q$Si varios estudiantes no tienen conexión en casa, ¿qué decisión es más inclusiva?$q$,
   jsonb_build_array($q$Ofrecer alternativas descargables, tiempos de acceso escolar y actividades equivalentes.$q$, $q$Calificar con cero a quienes no ingresen a la plataforma desde casa.$q$, $q$Eliminar a esos estudiantes de la actividad digital.$q$),
   0, $q$La inclusión exige ajustes razonables para participar sin bajar expectativas de aprendizaje.$q$,
   jsonb_build_array($q$Correcta: atiende barreras de acceso.$q$, $q$Incorrecta: sanciona condiciones externas.$q$, $q$Incorrecta: excluir contradice el propósito formativo.$q$)),
  (43, 'ofi-43', 'ofimatica-pedagogia', '41-46', 'Uso pedagogico de herramientas digitales',
   $q$El área académica quiere integrar herramientas digitales en una secuencia de aprendizaje. El propósito no es usar tecnología por novedad, sino mejorar comprensión, seguimiento y participación. El equipo debe elegir instrumentos coherentes con los objetivos, prever accesibilidad, evaluar evidencias y ofrecer alternativas cuando algunos estudiantes tienen conectividad limitada.$q$,
   43, $q$¿Qué evidencia digital permite valorar proceso y no solo producto final?$q$,
   jsonb_build_array($q$Historial de versiones, borradores, comentarios y mejoras después de retroalimentación.$q$, $q$Una captura final sin fecha ni explicación.$q$, $q$El número de colores usados en la entrega.$q$),
   0, $q$El proceso se observa en revisiones, retroalimentación y cambios justificados.$q$,
   jsonb_build_array($q$Correcta: evidencia aprendizaje en desarrollo.$q$, $q$Incorrecta: la captura final oculta el proceso.$q$, $q$Incorrecta: colores no demuestran comprensión.$q$)),
  (44, 'ofi-44', 'ofimatica-pedagogia', '41-46', 'Uso pedagogico de herramientas digitales',
   $q$El área académica quiere integrar herramientas digitales en una secuencia de aprendizaje. El propósito no es usar tecnología por novedad, sino mejorar comprensión, seguimiento y participación. El equipo debe elegir instrumentos coherentes con los objetivos, prever accesibilidad, evaluar evidencias y ofrecer alternativas cuando algunos estudiantes tienen conectividad limitada.$q$,
   44, $q$¿Qué uso de formularios en línea apoya la evaluación formativa?$q$,
   jsonb_build_array($q$Recolectar respuestas diagnósticas y retroalimentar errores frecuentes para ajustar la clase.$q$, $q$Usarlos solo para poner una nota automática sin revisar patrones.$q$, $q$Pedir datos personales innecesarios antes de cada pregunta.$q$),
   0, $q$La evaluación formativa usa información para retroalimentar y ajustar la enseñanza.$q$,
   jsonb_build_array($q$Correcta: convierte datos en decisiones pedagógicas.$q$, $q$Incorrecta: una nota automática aislada no garantiza retroalimentación.$q$, $q$Incorrecta: datos innecesarios vulneran minimización.$q$)),
  (45, 'ofi-45', 'ofimatica-pedagogia', '41-46', 'Uso pedagogico de herramientas digitales',
   $q$El área académica quiere integrar herramientas digitales en una secuencia de aprendizaje. El propósito no es usar tecnología por novedad, sino mejorar comprensión, seguimiento y participación. El equipo debe elegir instrumentos coherentes con los objetivos, prever accesibilidad, evaluar evidencias y ofrecer alternativas cuando algunos estudiantes tienen conectividad limitada.$q$,
   45, $q$¿Qué decisión mejora la accesibilidad de un video usado en clase?$q$,
   jsonb_build_array($q$Incluir subtítulos, transcripción o guía de apoyo para estudiantes que lo requieran.$q$, $q$Reproducirlo sin sonido ni apoyo textual para todos.$q$, $q$Elegir videos por duración sin revisar contenido ni accesibilidad.$q$),
   0, $q$Los apoyos textuales amplían el acceso y facilitan revisión del contenido.$q$,
   jsonb_build_array($q$Correcta: atiende distintas necesidades de acceso.$q$, $q$Incorrecta: limita comprensión.$q$, $q$Incorrecta: duración no basta como criterio pedagógico.$q$)),
  (46, 'ofi-46', 'ofimatica-pedagogia', '41-46', 'Uso pedagogico de herramientas digitales',
   $q$El área académica quiere integrar herramientas digitales en una secuencia de aprendizaje. El propósito no es usar tecnología por novedad, sino mejorar comprensión, seguimiento y participación. El equipo debe elegir instrumentos coherentes con los objetivos, prever accesibilidad, evaluar evidencias y ofrecer alternativas cuando algunos estudiantes tienen conectividad limitada.$q$,
   46, $q$¿Qué actuación docente es más adecuada frente a respuestas generadas con IA sin análisis propio?$q$,
   jsonb_build_array($q$Solicitar evidencia de proceso, criterios de citación y explicación personal de las decisiones.$q$, $q$Prohibir toda herramienta digital sin revisar el propósito de la tarea.$q$, $q$Aceptar cualquier texto si está bien redactado.$q$),
   0, $q$El uso responsable de IA exige transparencia, criterio, autoría y evidencia de aprendizaje.$q$,
   jsonb_build_array($q$Correcta: evalúa pensamiento y proceso.$q$, $q$Incorrecta: prohibir sin análisis no desarrolla criterio digital.$q$, $q$Incorrecta: buena redacción no prueba comprensión.$q$))
)
insert into public.quiz_questions (
  external_id, test_id, test_title, category, block_id, block_range, topic, situation,
  question_number, prompt, options, correct_answer, explanation, option_feedback, sequence
)
select
  external_id,
  'ofimatica-01',
  'Simulacro #1 · Ofimática',
  'ofimatica',
  block_id,
  block_range,
  topic,
  situation,
  question_number,
  prompt,
  options,
  correct_answer,
  explanation,
  option_feedback,
  base_sequence.value + position
from new_questions
cross join base_sequence
on conflict (external_id) do update
set test_title = excluded.test_title,
    category = excluded.category,
    block_id = excluded.block_id,
    block_range = excluded.block_range,
    topic = excluded.topic,
    situation = excluded.situation,
    question_number = excluded.question_number,
    prompt = excluded.prompt,
    options = excluded.options,
    correct_answer = excluded.correct_answer,
    explanation = excluded.explanation,
    option_feedback = excluded.option_feedback,
    active = true;
