with base_sequence as (
  select coalesce(max(sequence), 0) + 1000 as value
  from public.quiz_questions
),
new_questions (
  position,
  external_id,
  test_id,
  test_title,
  block_id,
  block_range,
  topic,
  situation,
  question_number,
  prompt,
  options,
  correct_answer,
  explanation,
  option_feedback
) as (
  values
  (1, 'gen-chem-01', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-materia', '1-5', 'Química: estructura de la materia',
   $q$En una institución educativa, el docente de Química diseña una práctica para que los estudiantes expliquen propiedades macroscópicas de varias sustancias a partir de modelos microscópicos. El grupo compara sal común, agua, dióxido de carbono y un metal conductor.$q$,
   1, $q$Al comparar NaCl sólido y agua líquida, ¿cuál explicación relaciona mejor estructura y propiedad?$q$,
   jsonb_build_array($q$El NaCl forma una red iónica que explica su alto punto de fusión; el agua forma moléculas polares con puentes de hidrógeno.$q$, $q$Ambas sustancias son redes metálicas, por eso conducen siempre la corriente.$q$, $q$El agua es apolar y el NaCl está formado por moléculas covalentes discretas.$q$),
   0, $q$La red iónica del NaCl y la polaridad del agua permiten explicar propiedades como punto de fusión, solubilidad e interacciones intermoleculares.$q$,
   jsonb_build_array($q$Correcta: relaciona enlace, estructura e interacción con propiedades observables.$q$, $q$Incorrecta: ni el NaCl ni el agua son redes metálicas.$q$, $q$Incorrecta: el agua es polar y el NaCl no se describe como moléculas covalentes discretas.$q$)),
  (2, 'gen-chem-02', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-materia', '1-5', 'Química: estructura de la materia',
   $q$En una institución educativa, el docente de Química diseña una práctica para que los estudiantes expliquen propiedades macroscópicas de varias sustancias a partir de modelos microscópicos. El grupo compara sal común, agua, dióxido de carbono y un metal conductor.$q$,
   2, $q$Si un estudiante afirma que el CO2 es polar porque tiene enlaces polares, ¿qué retroalimentación es más adecuada?$q$,
   jsonb_build_array($q$Debe revisar la geometría lineal: aunque los enlaces C=O son polares, sus dipolos se cancelan.$q$, $q$Debe aceptar que todo enlace polar produce automáticamente una molécula polar.$q$, $q$Debe concluir que el CO2 es iónico porque contiene oxígeno.$q$),
   0, $q$La polaridad molecular depende de la polaridad de enlace y de la geometría. En CO2 la molécula lineal cancela los dipolos.$q$,
   jsonb_build_array($q$Correcta: integra enlace y geometría molecular.$q$, $q$Incorrecta: ignora el efecto de la geometría molecular.$q$, $q$Incorrecta: la presencia de oxígeno no convierte la sustancia en iónica.$q$)),
  (3, 'gen-chem-03', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-materia', '1-5', 'Química: estructura de la materia',
   $q$En una institución educativa, el docente de Química diseña una práctica para que los estudiantes expliquen propiedades macroscópicas de varias sustancias a partir de modelos microscópicos. El grupo compara sal común, agua, dióxido de carbono y un metal conductor.$q$,
   3, $q$¿Qué actividad evalúa mejor la comprensión del modelo de enlace metálico?$q$,
   jsonb_build_array($q$Pedir que expliquen conductividad y maleabilidad mediante electrones deslocalizados.$q$, $q$Solicitar que memoricen la lista de metales del grupo 1 sin justificar propiedades.$q$, $q$Pedir que representen todos los metales como moléculas diatómicas.$q$),
   0, $q$El enlace metálico se comprende al relacionar red de cationes, electrones deslocalizados y propiedades como conductividad y maleabilidad.$q$,
   jsonb_build_array($q$Correcta: exige usar el modelo para explicar propiedades.$q$, $q$Incorrecta: memorizar listas no evidencia comprensión del modelo.$q$, $q$Incorrecta: los metales no se representan como moléculas diatómicas en estado sólido.$q$)),
  (4, 'gen-chem-04', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-materia', '1-5', 'Química: estructura de la materia',
   $q$En una institución educativa, el docente de Química diseña una práctica para que los estudiantes expliquen propiedades macroscópicas de varias sustancias a partir de modelos microscópicos. El grupo compara sal común, agua, dióxido de carbono y un metal conductor.$q$,
   4, $q$Para abordar la solubilidad del NaCl en agua, ¿qué idea debe enfatizar el docente?$q$,
   jsonb_build_array($q$La interacción ion-dipolo entre los iones del cristal y las moléculas polares de agua.$q$, $q$La transformación de sodio y cloro en átomos neutros insolubles.$q$, $q$La ruptura del núcleo atómico durante la disolución.$q$),
   0, $q$La disolución de una sal iónica en agua se explica por la hidratación de iones mediante interacciones ion-dipolo.$q$,
   jsonb_build_array($q$Correcta: explica el proceso sin alterar la identidad nuclear.$q$, $q$Incorrecta: los iones no se vuelven necesariamente átomos neutros para disolverse.$q$, $q$Incorrecta: la disolución no implica cambios nucleares.$q$)),
  (5, 'gen-chem-05', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-materia', '1-5', 'Química: estructura de la materia',
   $q$En una institución educativa, el docente de Química diseña una práctica para que los estudiantes expliquen propiedades macroscópicas de varias sustancias a partir de modelos microscópicos. El grupo compara sal común, agua, dióxido de carbono y un metal conductor.$q$,
   5, $q$¿Cuál evidencia permite diferenciar mejor un cambio físico de un cambio químico?$q$,
   jsonb_build_array($q$La formación de nuevas sustancias con propiedades distintas a las iniciales.$q$, $q$El cambio de tamaño de una muestra sin modificación de composición.$q$, $q$La variación de forma del recipiente que contiene la sustancia.$q$),
   0, $q$En un cambio químico se forman sustancias nuevas; en un cambio físico cambia el estado, forma o distribución sin alterar composición.$q$,
   jsonb_build_array($q$Correcta: usa el criterio central de transformación química.$q$, $q$Incorrecta: describe un cambio físico.$q$, $q$Incorrecta: la forma del recipiente no demuestra reacción química.$q$)),

  (6, 'gen-chem-06', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-reacciones', '6-10', 'Química: reacciones y estequiometría',
   $q$En grado décimo, los estudiantes analizan una reacción de combustión y deben balancearla, interpretar la conservación de la masa y calcular cantidades de reactivos y productos con datos sencillos.$q$,
   6, $q$Al balancear CH4 + O2 -> CO2 + H2O, ¿cuál ecuación cumple conservación de átomos?$q$,
   jsonb_build_array($q$CH4 + 2 O2 -> CO2 + 2 H2O$q$, $q$CH4 + O2 -> CO2 + H2O$q$, $q$2 CH4 + O2 -> 2 CO2 + H2O$q$),
   0, $q$La ecuación balanceada conserva 1 C, 4 H y 4 O a ambos lados: CH4 + 2 O2 -> CO2 + 2 H2O.$q$,
   jsonb_build_array($q$Correcta: conserva todos los átomos.$q$, $q$Incorrecta: no conserva hidrógeno ni oxígeno.$q$, $q$Incorrecta: no conserva hidrógeno ni oxígeno.$q$)),
  (7, 'gen-chem-07', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-reacciones', '6-10', 'Química: reacciones y estequiometría',
   $q$En grado décimo, los estudiantes analizan una reacción de combustión y deben balancearla, interpretar la conservación de la masa y calcular cantidades de reactivos y productos con datos sencillos.$q$,
   7, $q$Si 1 mol de CH4 reacciona completamente, ¿cuántos moles de O2 requiere la ecuación balanceada?$q$,
   jsonb_build_array($q$2 moles de O2.$q$, $q$1 mol de O2.$q$, $q$4 moles de O2.$q$),
   0, $q$El coeficiente estequiométrico del oxígeno es 2 por cada mol de metano.$q$,
   jsonb_build_array($q$Correcta: interpreta la relación molar de la ecuación.$q$, $q$Incorrecta: omite el coeficiente del O2.$q$, $q$Incorrecta: confunde número de átomos de oxígeno con moles de O2.$q$)),
  (8, 'gen-chem-08', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-reacciones', '6-10', 'Química: reacciones y estequiometría',
   $q$En grado décimo, los estudiantes analizan una reacción de combustión y deben balancearla, interpretar la conservación de la masa y calcular cantidades de reactivos y productos con datos sencillos.$q$,
   8, $q$¿Qué error conceptual muestra un estudiante que cambia subíndices para balancear una ecuación?$q$,
   jsonb_build_array($q$No reconoce que cambiar subíndices modifica la identidad de las sustancias.$q$, $q$Comprende que los coeficientes nunca se usan en química.$q$, $q$Aplica correctamente la ley de conservación de la masa.$q$),
   0, $q$El balanceo se realiza con coeficientes. Modificar subíndices cambia la fórmula química.$q$,
   jsonb_build_array($q$Correcta: identifica el error central.$q$, $q$Incorrecta: los coeficientes son precisamente la herramienta de balanceo.$q$, $q$Incorrecta: cambiar subíndices no es una aplicación correcta de conservación.$q$)),
  (9, 'gen-chem-09', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-reacciones', '6-10', 'Química: reacciones y estequiometría',
   $q$En grado décimo, los estudiantes analizan una reacción de combustión y deben balancearla, interpretar la conservación de la masa y calcular cantidades de reactivos y productos con datos sencillos.$q$,
   9, $q$En una reacción con reactivo limitante, ¿qué determina la cantidad máxima de producto?$q$,
   jsonb_build_array($q$El reactivo que se consume primero según la relación estequiométrica.$q$, $q$El reactivo con mayor masa inicial sin importar su proporción molar.$q$, $q$El producto que aparece con menor coeficiente en la ecuación.$q$),
   0, $q$El reactivo limitante se agota primero y limita la formación de productos.$q$,
   jsonb_build_array($q$Correcta: usa la definición de reactivo limitante.$q$, $q$Incorrecta: la masa inicial sola no determina la limitación.$q$, $q$Incorrecta: el producto no limita el avance de la reacción inicial.$q$)),
  (10, 'gen-chem-10', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-reacciones', '6-10', 'Química: reacciones y estequiometría',
   $q$En grado décimo, los estudiantes analizan una reacción de combustión y deben balancearla, interpretar la conservación de la masa y calcular cantidades de reactivos y productos con datos sencillos.$q$,
   10, $q$¿Qué evaluación es más pertinente para verificar comprensión estequiométrica?$q$,
   jsonb_build_array($q$Resolver un caso donde deban balancear, convertir moles y justificar el reactivo limitante.$q$, $q$Copiar diez ecuaciones balanceadas sin explicar relaciones molares.$q$, $q$Memorizar colores de llamas sin relacionarlos con reacción química.$q$),
   0, $q$Una tarea integrada evidencia uso de conservación, proporciones molares y razonamiento químico.$q$,
   jsonb_build_array($q$Correcta: evalúa procedimiento y comprensión.$q$, $q$Incorrecta: copiar no demuestra razonamiento.$q$, $q$Incorrecta: no evalúa estequiometría.$q$)),

  (11, 'gen-chem-11', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-soluciones', '11-15', 'Química: soluciones, pH y equilibrio',
   $q$El laboratorio escolar recibe muestras de agua de una quebrada cercana. El docente propone analizar concentración, pH y posibles cambios de equilibrio para discutir calidad del agua y toma de decisiones basada en evidencia.$q$,
   11, $q$Si una solución tiene pH 3, ¿qué interpretación es correcta?$q$,
   jsonb_build_array($q$Es ácida y tiene mayor concentración de H3O+ que una solución de pH 7.$q$, $q$Es básica porque todo pH menor que 7 neutraliza ácidos.$q$, $q$Es neutra porque el pH solo mide temperatura.$q$),
   0, $q$Un pH menor que 7 indica acidez; pH 3 implica concentración de H3O+ superior a la neutralidad.$q$,
   jsonb_build_array($q$Correcta: interpreta la escala de pH.$q$, $q$Incorrecta: pH menor que 7 no es básico.$q$, $q$Incorrecta: el pH no mide temperatura.$q$)),
  (12, 'gen-chem-12', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-soluciones', '11-15', 'Química: soluciones, pH y equilibrio',
   $q$El laboratorio escolar recibe muestras de agua de una quebrada cercana. El docente propone analizar concentración, pH y posibles cambios de equilibrio para discutir calidad del agua y toma de decisiones basada en evidencia.$q$,
   12, $q$¿Qué significa preparar una solución 0,10 M de NaCl?$q$,
   jsonb_build_array($q$Disolver 0,10 moles de NaCl por cada litro de solución.$q$, $q$Disolver 0,10 gramos de NaCl en cualquier volumen de agua.$q$, $q$Tener 10 moles de NaCl por mililitro de solución.$q$),
   0, $q$La molaridad expresa moles de soluto por litro de solución.$q$,
   jsonb_build_array($q$Correcta: define molaridad.$q$, $q$Incorrecta: confunde gramos y no fija volumen final.$q$, $q$Incorrecta: usa una relación de unidades equivocada.$q$)),
  (13, 'gen-chem-13', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-soluciones', '11-15', 'Química: soluciones, pH y equilibrio',
   $q$El laboratorio escolar recibe muestras de agua de una quebrada cercana. El docente propone analizar concentración, pH y posibles cambios de equilibrio para discutir calidad del agua y toma de decisiones basada en evidencia.$q$,
   13, $q$Según Le Châtelier, si se aumenta la concentración de un reactivo en equilibrio, el sistema tiende a:$q$,
   jsonb_build_array($q$Desplazarse hacia el consumo parcial del reactivo añadido.$q$, $q$Detener toda reacción directa e inversa.$q$, $q$Eliminar la constante de equilibrio.$q$),
   0, $q$El sistema responde oponiéndose parcialmente a la perturbación, favoreciendo el consumo del reactivo agregado.$q$,
   jsonb_build_array($q$Correcta: aplica el principio cualitativamente.$q$, $q$Incorrecta: el equilibrio es dinámico, no ausencia de reacción.$q$, $q$Incorrecta: la constante depende de la temperatura, no desaparece por agregar reactivo.$q$)),
  (14, 'gen-chem-14', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-soluciones', '11-15', 'Química: soluciones, pH y equilibrio',
   $q$El laboratorio escolar recibe muestras de agua de una quebrada cercana. El docente propone analizar concentración, pH y posibles cambios de equilibrio para discutir calidad del agua y toma de decisiones basada en evidencia.$q$,
   14, $q$Para reducir error al medir pH con indicador universal, ¿qué acción pedagógica es más adecuada?$q$,
   jsonb_build_array($q$Comparar con una escala patrón, registrar rango de color y discutir incertidumbre.$q$, $q$Elegir siempre el color que parezca más bonito al grupo.$q$, $q$Usar el indicador sin controlar limpieza ni volumen de muestra.$q$),
   0, $q$La medición escolar debe incluir comparación, registro y discusión de incertidumbre para fortalecer competencia científica.$q$,
   jsonb_build_array($q$Correcta: promueve medición rigurosa y análisis de evidencia.$q$, $q$Incorrecta: introduce subjetividad sin criterio.$q$, $q$Incorrecta: descuida control de variables y contaminación.$q$)),
  (15, 'gen-chem-15', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-soluciones', '11-15', 'Química: soluciones, pH y equilibrio',
   $q$El laboratorio escolar recibe muestras de agua de una quebrada cercana. El docente propone analizar concentración, pH y posibles cambios de equilibrio para discutir calidad del agua y toma de decisiones basada en evidencia.$q$,
   15, $q$¿Qué conclusión es válida si dos grupos obtienen pH 6 y pH 8 para la misma muestra?$q$,
   jsonb_build_array($q$Se debe revisar procedimiento, calibración o contaminación antes de concluir sobre la muestra.$q$, $q$La muestra es simultáneamente ácida y básica sin necesidad de revisar datos.$q$, $q$El pH no sirve para analizar agua en ningún contexto.$q$),
   0, $q$Resultados discrepantes exigen revisar método, instrumentos y condiciones antes de interpretar la evidencia.$q$,
   jsonb_build_array($q$Correcta: prioriza control de calidad de datos.$q$, $q$Incorrecta: acepta contradicción sin análisis.$q$, $q$Incorrecta: descarta una herramienta útil por mala aplicación.$q$)),

  (16, 'gen-chem-16', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-organica', '16-20', 'Química: orgánica y materiales',
   $q$En un proyecto sobre materiales cotidianos, los estudiantes comparan alcoholes, ácidos carboxílicos, polímeros y combustibles. El docente busca que reconozcan grupos funcionales, propiedades y efectos ambientales.$q$,
   16, $q$¿Qué grupo funcional caracteriza a los alcoholes?$q$,
   jsonb_build_array($q$El grupo hidroxilo -OH unido a carbono saturado.$q$, $q$El grupo carboxilo -COOH como única posibilidad.$q$, $q$Un enlace iónico entre carbono y sodio.$q$),
   0, $q$Los alcoholes se caracterizan por el grupo hidroxilo unido a un carbono saturado.$q$,
   jsonb_build_array($q$Correcta: reconoce el grupo funcional.$q$, $q$Incorrecta: -COOH corresponde a ácidos carboxílicos.$q$, $q$Incorrecta: no describe un grupo funcional orgánico típico.$q$)),
  (17, 'gen-chem-17', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-organica', '16-20', 'Química: orgánica y materiales',
   $q$En un proyecto sobre materiales cotidianos, los estudiantes comparan alcoholes, ácidos carboxílicos, polímeros y combustibles. El docente busca que reconozcan grupos funcionales, propiedades y efectos ambientales.$q$,
   17, $q$¿Cuál afirmación sobre polímeros es más precisa para educación media?$q$,
   jsonb_build_array($q$Son macromoléculas formadas por unidades repetidas llamadas monómeros.$q$, $q$Son siempre sustancias iónicas simples con bajo punto de fusión.$q$, $q$Son átomos aislados sin enlaces químicos.$q$),
   0, $q$Los polímeros se forman por repetición de monómeros; sus propiedades dependen de estructura y composición.$q$,
   jsonb_build_array($q$Correcta: define polímero de forma escolarmente adecuada.$q$, $q$Incorrecta: no todos son iónicos ni simples.$q$, $q$Incorrecta: una macromolécula contiene enlaces químicos.$q$)),
  (18, 'gen-chem-18', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-organica', '16-20', 'Química: orgánica y materiales',
   $q$En un proyecto sobre materiales cotidianos, los estudiantes comparan alcoholes, ácidos carboxílicos, polímeros y combustibles. El docente busca que reconozcan grupos funcionales, propiedades y efectos ambientales.$q$,
   18, $q$¿Qué criterio permite comparar combustibles desde una perspectiva química y ambiental?$q$,
   jsonb_build_array($q$Energía liberada, productos de combustión y emisiones asociadas.$q$, $q$Solo el color del combustible antes de quemarse.$q$, $q$La marca comercial sin analizar composición.$q$),
   0, $q$La comparación debe integrar rendimiento energético y sustancias producidas, especialmente gases de efecto ambiental.$q$,
   jsonb_build_array($q$Correcta: relaciona química, energía e impacto ambiental.$q$, $q$Incorrecta: el color no basta para evaluar combustibles.$q$, $q$Incorrecta: la marca no es un criterio científico.$q$)),
  (19, 'gen-chem-19', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-organica', '16-20', 'Química: orgánica y materiales',
   $q$En un proyecto sobre materiales cotidianos, los estudiantes comparan alcoholes, ácidos carboxílicos, polímeros y combustibles. El docente busca que reconozcan grupos funcionales, propiedades y efectos ambientales.$q$,
   19, $q$Una estrategia didáctica pertinente para enseñar grupos funcionales es:$q$,
   jsonb_build_array($q$Analizar etiquetas y modelos moleculares de sustancias cotidianas para identificar patrones estructurales.$q$, $q$Presentar únicamente una lista de nombres IUPAC sin ejemplos ni representación.$q$, $q$Evitar modelos porque toda química orgánica debe memorizarse.$q$),
   0, $q$Relacionar modelos, nombres y contextos cotidianos favorece comprensión y transferencia.$q$,
   jsonb_build_array($q$Correcta: usa representación y contexto.$q$, $q$Incorrecta: la lista aislada limita comprensión.$q$, $q$Incorrecta: los modelos son herramientas centrales en química.$q$)),
  (20, 'gen-chem-20', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-organica', '16-20', 'Química: orgánica y materiales',
   $q$En un proyecto sobre materiales cotidianos, los estudiantes comparan alcoholes, ácidos carboxílicos, polímeros y combustibles. El docente busca que reconozcan grupos funcionales, propiedades y efectos ambientales.$q$,
   20, $q$¿Qué desempeño muestra mejor competencia química aplicada?$q$,
   jsonb_build_array($q$Justificar propiedades de un material con base en estructura, enlaces e interacciones.$q$, $q$Repetir una definición sin usarla para explicar ninguna situación.$q$, $q$Seleccionar una respuesta por familiaridad con una palabra técnica.$q$),
   0, $q$La competencia específica exige usar conceptos para explicar, predecir o tomar decisiones en contexto.$q$,
   jsonb_build_array($q$Correcta: evidencia aplicación conceptual.$q$, $q$Incorrecta: repetir no demuestra transferencia.$q$, $q$Incorrecta: reconocer palabras no equivale a comprensión.$q$)),

  (21, 'gen-chem-21', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-aula', '21-25', 'Química: práctica experimental y evaluación',
   $q$El docente planea una actividad experimental con materiales de bajo riesgo para fortalecer indagación. Debe formular preguntas, controlar variables, recoger datos y retroalimentar a estudiantes con distintos niveles de desempeño.$q$,
   21, $q$¿Qué pregunta promueve mejor indagación científica escolar?$q$,
   jsonb_build_array($q$¿Cómo cambia la velocidad de disolución al variar temperatura manteniendo constantes masa y agitación?$q$, $q$¿Cuál es la respuesta exacta que aparece en el libro?$q$, $q$¿Qué grupo termina primero sin registrar datos?$q$),
   0, $q$Una buena pregunta de indagación relaciona variables, permite medición y exige control experimental.$q$,
   jsonb_build_array($q$Correcta: plantea variables y control.$q$, $q$Incorrecta: no promueve investigación.$q$, $q$Incorrecta: privilegia rapidez sin evidencia.$q$)),
  (22, 'gen-chem-22', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-aula', '21-25', 'Química: práctica experimental y evaluación',
   $q$El docente planea una actividad experimental con materiales de bajo riesgo para fortalecer indagación. Debe formular preguntas, controlar variables, recoger datos y retroalimentar a estudiantes con distintos niveles de desempeño.$q$,
   22, $q$Si un grupo no controla la cantidad de soluto, ¿qué efecto tiene en sus conclusiones?$q$,
   jsonb_build_array($q$Reduce la validez porque no se puede atribuir el resultado solo a la variable estudiada.$q$, $q$Mejora la investigación porque aumenta la cantidad de datos sin orden.$q$, $q$No afecta porque en química escolar no existen variables de control.$q$),
   0, $q$Sin control de variables, las conclusiones pierden validez causal.$q$,
   jsonb_build_array($q$Correcta: reconoce la función del control experimental.$q$, $q$Incorrecta: más datos desordenados no mejoran validez.$q$, $q$Incorrecta: el control de variables es esencial en indagación.$q$)),
  (23, 'gen-chem-23', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-aula', '21-25', 'Química: práctica experimental y evaluación',
   $q$El docente planea una actividad experimental con materiales de bajo riesgo para fortalecer indagación. Debe formular preguntas, controlar variables, recoger datos y retroalimentar a estudiantes con distintos niveles de desempeño.$q$,
   23, $q$¿Qué retroalimentación es más formativa ante una gráfica mal construida?$q$,
   jsonb_build_array($q$Pedir revisar ejes, unidades y relación entre variables, explicando cómo corregirla.$q$, $q$Calificar con cero sin indicar el error.$q$, $q$Decir que la gráfica no importa si el resultado final parece correcto.$q$),
   0, $q$La evaluación formativa orienta al estudiante sobre criterios y acciones de mejora.$q$,
   jsonb_build_array($q$Correcta: retroalimenta con criterios claros.$q$, $q$Incorrecta: sanciona sin orientar mejora.$q$, $q$Incorrecta: la representación de datos sí es parte de la competencia científica.$q$)),
  (24, 'gen-chem-24', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-aula', '21-25', 'Química: práctica experimental y evaluación',
   $q$El docente planea una actividad experimental con materiales de bajo riesgo para fortalecer indagación. Debe formular preguntas, controlar variables, recoger datos y retroalimentar a estudiantes con distintos niveles de desempeño.$q$,
   24, $q$En seguridad de laboratorio escolar, la decisión inicial más pertinente es:$q$,
   jsonb_build_array($q$Valorar riesgos, seleccionar materiales adecuados y acordar normas antes de iniciar.$q$, $q$Permitir cualquier mezcla para estimular creatividad sin restricciones.$q$, $q$Usar sustancias desconocidas sin rotular para ahorrar tiempo.$q$),
   0, $q$La práctica experimental exige prevención, selección de materiales y normas claras.$q$,
   jsonb_build_array($q$Correcta: prioriza seguridad y aprendizaje.$q$, $q$Incorrecta: la creatividad no justifica riesgo no controlado.$q$, $q$Incorrecta: usar sustancias desconocidas es inseguro.$q$)),
  (25, 'gen-chem-25', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-aula', '21-25', 'Química: práctica experimental y evaluación',
   $q$El docente planea una actividad experimental con materiales de bajo riesgo para fortalecer indagación. Debe formular preguntas, controlar variables, recoger datos y retroalimentar a estudiantes con distintos niveles de desempeño.$q$,
   25, $q$¿Qué evidencia integra mejor aprendizaje químico y competencia pedagógica?$q$,
   jsonb_build_array($q$Informe donde el estudiante justifica datos, reconoce errores y propone mejora experimental.$q$, $q$Cuaderno con fórmulas copiadas sin interpretación.$q$, $q$Asistencia al laboratorio sin registro de procedimiento ni análisis.$q$),
   0, $q$La evidencia más sólida combina comprensión conceptual, análisis de datos, metacognición y mejora.$q$,
   jsonb_build_array($q$Correcta: integra saber químico e indagación.$q$, $q$Incorrecta: copiar fórmulas no evidencia comprensión.$q$, $q$Incorrecta: asistir no basta para evaluar aprendizaje.$q$)),

  (26, 'gen-nat-01', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-ecosistemas', '1-5', 'Ciencias naturales: ecosistemas y ambiente',
   $q$Una institución educativa rural trabaja con estudiantes de básica y media en el análisis de una microcuenca cercana. Se revisan relaciones ecológicas, calidad ambiental, uso del suelo y acciones de conservación.$q$,
   1, $q$Si disminuye una población de polinizadores, ¿qué efecto ecológico es más probable?$q$,
   jsonb_build_array($q$Reducción en la reproducción de algunas plantas y cambios en la red trófica.$q$, $q$Aumento automático de todas las especies vegetales.$q$, $q$Desaparición inmediata de todos los organismos acuáticos.$q$),
   0, $q$Los polinizadores participan en la reproducción de muchas plantas; su disminución puede afectar comunidades y redes tróficas.$q$,
   jsonb_build_array($q$Correcta: reconoce interdependencias ecosistémicas.$q$, $q$Incorrecta: no todas las plantas aumentarían.$q$, $q$Incorrecta: extrapola un efecto inmediato sin evidencia.$q$)),
  (27, 'gen-nat-02', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-ecosistemas', '1-5', 'Ciencias naturales: ecosistemas y ambiente',
   $q$Una institución educativa rural trabaja con estudiantes de básica y media en el análisis de una microcuenca cercana. Se revisan relaciones ecológicas, calidad ambiental, uso del suelo y acciones de conservación.$q$,
   2, $q$¿Qué indicador sería más pertinente para estudiar eutrofización en un cuerpo de agua?$q$,
   jsonb_build_array($q$Aumento de nutrientes, proliferación de algas y reducción de oxígeno disuelto.$q$, $q$Únicamente el color de las piedras del río.$q$, $q$La cantidad de pupitres disponibles en el aula.$q$),
   0, $q$La eutrofización se asocia con exceso de nutrientes, proliferación algal y disminución de oxígeno.$q$,
   jsonb_build_array($q$Correcta: relaciona causa y efecto ambiental.$q$, $q$Incorrecta: el color de piedras no basta como indicador.$q$, $q$Incorrecta: no corresponde al sistema estudiado.$q$)),
  (28, 'gen-nat-03', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-ecosistemas', '1-5', 'Ciencias naturales: ecosistemas y ambiente',
   $q$Una institución educativa rural trabaja con estudiantes de básica y media en el análisis de una microcuenca cercana. Se revisan relaciones ecológicas, calidad ambiental, uso del suelo y acciones de conservación.$q$,
   3, $q$Una relación depredador-presa se caracteriza porque:$q$,
   jsonb_build_array($q$Un organismo obtiene alimento de otro, afectando su supervivencia individual.$q$, $q$Ambos organismos se benefician obligatoriamente sin costo.$q$, $q$Ningún organismo interactúa con el otro.$q$),
   0, $q$La depredación implica consumo de un organismo por otro y regula poblaciones dentro de redes tróficas.$q$,
   jsonb_build_array($q$Correcta: define la relación ecológica.$q$, $q$Incorrecta: describe mutualismo, no depredación.$q$, $q$Incorrecta: niega la interacción.$q$)),
  (29, 'gen-nat-04', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-ecosistemas', '1-5', 'Ciencias naturales: ecosistemas y ambiente',
   $q$Una institución educativa rural trabaja con estudiantes de básica y media en el análisis de una microcuenca cercana. Se revisan relaciones ecológicas, calidad ambiental, uso del suelo y acciones de conservación.$q$,
   4, $q$¿Qué acción escolar integra mejor educación ambiental y pensamiento científico?$q$,
   jsonb_build_array($q$Medir variables de la microcuenca, analizar datos y proponer acciones justificadas.$q$, $q$Hacer una cartelera sin observación ni consulta de evidencia.$q$, $q$Prohibir preguntas de los estudiantes para terminar rápido.$q$),
   0, $q$La educación ambiental pertinente se apoya en evidencia, análisis crítico y acción contextualizada.$q$,
   jsonb_build_array($q$Correcta: une indagación y acción ambiental.$q$, $q$Incorrecta: puede sensibilizar, pero no evidencia pensamiento científico suficiente.$q$, $q$Incorrecta: limita la indagación.$q$)),
  (30, 'gen-nat-05', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-ecosistemas', '1-5', 'Ciencias naturales: ecosistemas y ambiente',
   $q$Una institución educativa rural trabaja con estudiantes de básica y media en el análisis de una microcuenca cercana. Se revisan relaciones ecológicas, calidad ambiental, uso del suelo y acciones de conservación.$q$,
   5, $q$¿Qué diferencia mejor población y comunidad?$q$,
   jsonb_build_array($q$Población es un conjunto de individuos de la misma especie; comunidad incluye poblaciones de distintas especies.$q$, $q$Población y comunidad son sinónimos exactos.$q$, $q$Comunidad solo se refiere a estudiantes y docentes.$q$),
   0, $q$La ecología distingue niveles de organización: población y comunidad no son equivalentes.$q$,
   jsonb_build_array($q$Correcta: diferencia niveles ecológicos.$q$, $q$Incorrecta: confunde conceptos.$q$, $q$Incorrecta: reduce comunidad a uso social no ecológico.$q$)),

  (31, 'gen-nat-06', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-celula', '6-10', 'Ciencias naturales: célula y herencia',
   $q$En una secuencia de biología, el docente relaciona estructura celular, división, herencia y salud. Los estudiantes deben interpretar esquemas y argumentar con modelos científicos.$q$,
   6, $q$¿Cuál función corresponde principalmente a las mitocondrias?$q$,
   jsonb_build_array($q$Participar en la respiración celular y producción de ATP.$q$, $q$Almacenar toda la información genética en procariotas.$q$, $q$Realizar fotosíntesis en células animales.$q$),
   0, $q$Las mitocondrias participan en respiración celular aerobia y producción de ATP en células eucariotas.$q$,
   jsonb_build_array($q$Correcta: identifica función energética.$q$, $q$Incorrecta: las procariotas no poseen mitocondrias.$q$, $q$Incorrecta: la fotosíntesis ocurre en cloroplastos de células vegetales y algas.$q$)),
  (32, 'gen-nat-07', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-celula', '6-10', 'Ciencias naturales: célula y herencia',
   $q$En una secuencia de biología, el docente relaciona estructura celular, división, herencia y salud. Los estudiantes deben interpretar esquemas y argumentar con modelos científicos.$q$,
   7, $q$La mitosis se diferencia de la meiosis porque:$q$,
   jsonb_build_array($q$Conserva el número cromosómico en células hijas genéticamente similares.$q$, $q$Produce gametos con recombinación en todos los tejidos somáticos.$q$, $q$Reduce siempre el número cromosómico a la cuarta parte.$q$),
   0, $q$La mitosis produce células hijas con igual número cromosómico y se relaciona con crecimiento y reparación.$q$,
   jsonb_build_array($q$Correcta: diferencia mitosis y meiosis.$q$, $q$Incorrecta: describe rasgos de meiosis, no mitosis.$q$, $q$Incorrecta: la reducción no es a la cuarta parte.$q$)),
  (33, 'gen-nat-08', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-celula', '6-10', 'Ciencias naturales: célula y herencia',
   $q$En una secuencia de biología, el docente relaciona estructura celular, división, herencia y salud. Los estudiantes deben interpretar esquemas y argumentar con modelos científicos.$q$,
   8, $q$¿Qué representa mejor un alelo?$q$,
   jsonb_build_array($q$Una variante de un gen que puede influir en un rasgo.$q$, $q$Un orgánulo encargado de producir energía.$q$, $q$Una molécula de agua dentro del núcleo.$q$),
   0, $q$Los alelos son variantes de un gen ubicadas en loci correspondientes.$q$,
   jsonb_build_array($q$Correcta: define alelo.$q$, $q$Incorrecta: confunde genética con estructura celular.$q$, $q$Incorrecta: no corresponde al concepto genético.$q$)),
  (34, 'gen-nat-09', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-celula', '6-10', 'Ciencias naturales: célula y herencia',
   $q$En una secuencia de biología, el docente relaciona estructura celular, división, herencia y salud. Los estudiantes deben interpretar esquemas y argumentar con modelos científicos.$q$,
   9, $q$Si dos progenitores heterocigotos Aa se cruzan, ¿qué proporción genotípica esperada se obtiene?$q$,
   jsonb_build_array($q$1 AA : 2 Aa : 1 aa.$q$, $q$3 AA : 1 aa.$q$, $q$4 Aa : 0 aa.$q$),
   0, $q$El cuadro de Punnett para Aa x Aa produce proporción genotípica 1:2:1.$q$,
   jsonb_build_array($q$Correcta: aplica herencia mendeliana básica.$q$, $q$Incorrecta: confunde proporción fenotípica con genotípica y además cambia genotipos.$q$, $q$Incorrecta: no reconoce segregación de alelos.$q$)),
  (35, 'gen-nat-10', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-celula', '6-10', 'Ciencias naturales: célula y herencia',
   $q$En una secuencia de biología, el docente relaciona estructura celular, división, herencia y salud. Los estudiantes deben interpretar esquemas y argumentar con modelos científicos.$q$,
   10, $q$¿Qué actividad evalúa mejor comprensión de herencia y no solo memorización?$q$,
   jsonb_build_array($q$Resolver un caso familiar sencillo, construir Punnett y justificar probabilidades.$q$, $q$Copiar definiciones de gen, alelo y cromosoma sin aplicación.$q$, $q$Repetir nombres de científicos sin relacionarlos con evidencias.$q$),
   0, $q$La competencia se evidencia al aplicar modelos para explicar y predecir resultados en contexto.$q$,
   jsonb_build_array($q$Correcta: exige aplicación y justificación.$q$, $q$Incorrecta: copiar no garantiza comprensión.$q$, $q$Incorrecta: datos históricos aislados no evalúan el modelo.$q$)),

  (36, 'gen-nat-11', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-fisica', '11-15', 'Ciencias naturales: física escolar',
   $q$En una clase integrada de ciencias, el docente propone analizar el movimiento de una bicicleta, el uso de energía y la transferencia de calor en situaciones cotidianas.$q$,
   11, $q$Si una bicicleta mantiene velocidad constante en línea recta, la fuerza neta sobre ella es:$q$,
   jsonb_build_array($q$Cero, si se desprecia cualquier cambio de movimiento.$q$, $q$Siempre mayor que su peso.$q$, $q$Igual a la masa multiplicada por la distancia total.$q$),
   0, $q$Con velocidad constante no hay aceleración; por la segunda ley de Newton, la fuerza neta es cero.$q$,
   jsonb_build_array($q$Correcta: aplica fuerza neta y aceleración.$q$, $q$Incorrecta: confunde fuerzas particulares con fuerza neta.$q$, $q$Incorrecta: masa por distancia no es fuerza neta.$q$)),
  (37, 'gen-nat-12', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-fisica', '11-15', 'Ciencias naturales: física escolar',
   $q$En una clase integrada de ciencias, el docente propone analizar el movimiento de una bicicleta, el uso de energía y la transferencia de calor en situaciones cotidianas.$q$,
   12, $q$¿Cuál enunciado representa conservación de la energía en una bajada?$q$,
   jsonb_build_array($q$Parte de la energía potencial gravitatoria se transforma en cinética y en energía térmica por rozamiento.$q$, $q$La energía desaparece cuando aumenta la velocidad.$q$, $q$La masa se convierte por completo en fuerza.$q$),
   0, $q$La energía se transforma; el rozamiento puede disipar parte como calor, pero no desaparece.$q$,
   jsonb_build_array($q$Correcta: explica transformación energética.$q$, $q$Incorrecta: viola conservación de energía.$q$, $q$Incorrecta: mezcla conceptos sin relación física correcta.$q$)),
  (38, 'gen-nat-13', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-fisica', '11-15', 'Ciencias naturales: física escolar',
   $q$En una clase integrada de ciencias, el docente propone analizar el movimiento de una bicicleta, el uso de energía y la transferencia de calor en situaciones cotidianas.$q$,
   13, $q$¿Qué diferencia calor y temperatura?$q$,
   jsonb_build_array($q$El calor es energía en transferencia; la temperatura se relaciona con el estado térmico de un cuerpo.$q$, $q$Son exactamente la misma magnitud y tienen siempre la misma unidad.$q$, $q$La temperatura solo existe en líquidos y el calor solo en sólidos.$q$),
   0, $q$Calor y temperatura son conceptos distintos: transferencia energética y medida asociada al estado térmico.$q$,
   jsonb_build_array($q$Correcta: diferencia magnitudes.$q$, $q$Incorrecta: no son equivalentes.$q$, $q$Incorrecta: ambos conceptos aplican a diferentes estados de la materia.$q$)),
  (39, 'gen-nat-14', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-fisica', '11-15', 'Ciencias naturales: física escolar',
   $q$En una clase integrada de ciencias, el docente propone analizar el movimiento de una bicicleta, el uso de energía y la transferencia de calor en situaciones cotidianas.$q$,
   14, $q$¿Qué representación ayuda más a interpretar movimiento rectilíneo uniforme?$q$,
   jsonb_build_array($q$Una gráfica posición-tiempo con pendiente constante.$q$, $q$Una lista de colores de bicicletas.$q$, $q$Un dibujo sin escala ni variables.$q$),
   0, $q$En movimiento uniforme, la posición cambia linealmente con el tiempo; la pendiente representa velocidad.$q$,
   jsonb_build_array($q$Correcta: usa representación gráfica pertinente.$q$, $q$Incorrecta: no representa variables físicas.$q$, $q$Incorrecta: sin escala ni variables no permite análisis.$q$)),
  (40, 'gen-nat-15', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-fisica', '11-15', 'Ciencias naturales: física escolar',
   $q$En una clase integrada de ciencias, el docente propone analizar el movimiento de una bicicleta, el uso de energía y la transferencia de calor en situaciones cotidianas.$q$,
   15, $q$Si un estudiante confunde masa y peso, ¿qué intervención es más adecuada?$q$,
   jsonb_build_array($q$Comparar masa como cantidad de materia y peso como fuerza gravitatoria, usando unidades diferentes.$q$, $q$Decir que son iguales porque se miden con cualquier instrumento.$q$, $q$Evitar el tema para no generar conflicto conceptual.$q$),
   0, $q$Masa y peso son magnitudes distintas: kg para masa y newton para peso.$q$,
   jsonb_build_array($q$Correcta: diferencia concepto, unidad y causa.$q$, $q$Incorrecta: refuerza la confusión.$q$, $q$Incorrecta: el error conceptual debe abordarse didácticamente.$q$)),

  (41, 'gen-nat-16', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-indagacion', '16-20', 'Ciencias naturales: indagación y evaluación',
   $q$El área de Ciencias Naturales diseña una feria investigativa. Los estudiantes deben formular preguntas, diseñar procedimientos, interpretar datos y comunicar conclusiones con responsabilidad ética.$q$,
   16, $q$¿Qué hipótesis es más investigable en contexto escolar?$q$,
   jsonb_build_array($q$Si aumenta la luz recibida por una planta, entonces puede cambiar su crecimiento bajo condiciones controladas.$q$, $q$Las plantas son bonitas porque sí.$q$, $q$La ciencia siempre tiene una única respuesta sin evidencia.$q$),
   0, $q$Una hipótesis investigable relaciona variables y puede ponerse a prueba con datos.$q$,
   jsonb_build_array($q$Correcta: propone relación entre variables.$q$, $q$Incorrecta: es una valoración subjetiva.$q$, $q$Incorrecta: contradice la naturaleza empírica de la ciencia.$q$)),
  (42, 'gen-nat-17', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-indagacion', '16-20', 'Ciencias naturales: indagación y evaluación',
   $q$El área de Ciencias Naturales diseña una feria investigativa. Los estudiantes deben formular preguntas, diseñar procedimientos, interpretar datos y comunicar conclusiones con responsabilidad ética.$q$,
   17, $q$¿Qué elemento fortalece la validez de un diseño experimental?$q$,
   jsonb_build_array($q$Definir variable independiente, dependiente y condiciones controladas.$q$, $q$Cambiar todas las variables a la vez.$q$, $q$Eliminar el registro de datos para ahorrar tiempo.$q$),
   0, $q$Controlar variables permite atribuir cambios observados a la variable estudiada.$q$,
   jsonb_build_array($q$Correcta: establece diseño controlado.$q$, $q$Incorrecta: impide interpretar causas.$q$, $q$Incorrecta: sin datos no hay evidencia evaluable.$q$)),
  (43, 'gen-nat-18', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-indagacion', '16-20', 'Ciencias naturales: indagación y evaluación',
   $q$El área de Ciencias Naturales diseña una feria investigativa. Los estudiantes deben formular preguntas, diseñar procedimientos, interpretar datos y comunicar conclusiones con responsabilidad ética.$q$,
   18, $q$Al evaluar conclusiones, el docente debe priorizar que los estudiantes:$q$,
   jsonb_build_array($q$Relacionen afirmaciones con datos y reconozcan limitaciones del procedimiento.$q$, $q$Presenten conclusiones extensas aunque contradigan los datos.$q$, $q$Eviten mencionar errores para que el trabajo parezca perfecto.$q$),
   0, $q$La comunicación científica exige coherencia entre datos, afirmaciones y limitaciones.$q$,
   jsonb_build_array($q$Correcta: evalúa argumentación basada en evidencia.$q$, $q$Incorrecta: la extensión no reemplaza coherencia.$q$, $q$Incorrecta: reconocer limitaciones fortalece el análisis.$q$)),
  (44, 'gen-nat-19', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-indagacion', '16-20', 'Ciencias naturales: indagación y evaluación',
   $q$El área de Ciencias Naturales diseña una feria investigativa. Los estudiantes deben formular preguntas, diseñar procedimientos, interpretar datos y comunicar conclusiones con responsabilidad ética.$q$,
   19, $q$¿Qué decisión muestra evaluación formativa en la feria?$q$,
   jsonb_build_array($q$Usar una rúbrica, dar retroalimentación durante el proceso y permitir ajustes justificados.$q$, $q$Calificar solo la decoración del cartel final.$q$, $q$Ocultar criterios hasta después de entregar el proyecto.$q$),
   0, $q$La evaluación formativa comunica criterios, retroalimenta y mejora el proceso antes del cierre.$q$,
   jsonb_build_array($q$Correcta: incluye criterios, retroalimentación y mejora.$q$, $q$Incorrecta: descuida competencia científica.$q$, $q$Incorrecta: sin criterios previos se reduce transparencia.$q$)),
  (45, 'gen-nat-20', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-indagacion', '16-20', 'Ciencias naturales: indagación y evaluación',
   $q$El área de Ciencias Naturales diseña una feria investigativa. Los estudiantes deben formular preguntas, diseñar procedimientos, interpretar datos y comunicar conclusiones con responsabilidad ética.$q$,
   20, $q$¿Qué práctica es éticamente adecuada en el trabajo con seres vivos?$q$,
   jsonb_build_array($q$Minimizar daño, justificar el procedimiento y cumplir normas institucionales.$q$, $q$Manipular organismos sin cuidado porque es una actividad escolar.$q$, $q$Ocultar riesgos para que los estudiantes participen sin preguntar.$q$),
   0, $q$La enseñanza de ciencias debe integrar responsabilidad ética y seguridad.$q$,
   jsonb_build_array($q$Correcta: incorpora cuidado y norma.$q$, $q$Incorrecta: desconoce responsabilidad ética.$q$, $q$Incorrecta: oculta información relevante y riesgos.$q$)),

  (46, 'gen-nat-21', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-cuerpo', '21-25', 'Ciencias naturales: cuerpo humano y salud',
   $q$En educación básica, el docente aborda nutrición, sistemas del cuerpo humano, prevención y toma de decisiones saludables desde evidencia científica y contexto familiar.$q$,
   21, $q$¿Qué relación explica mejor la función del sistema digestivo?$q$,
   jsonb_build_array($q$Transforma alimentos en nutrientes que pueden ser absorbidos y utilizados por el organismo.$q$, $q$Produce oxígeno para todos los ecosistemas.$q$, $q$Transporta impulsos nerviosos desde el cerebro a los músculos únicamente.$q$),
   0, $q$El sistema digestivo realiza digestión y absorción de nutrientes.$q$,
   jsonb_build_array($q$Correcta: describe función central.$q$, $q$Incorrecta: no corresponde al sistema digestivo.$q$, $q$Incorrecta: describe parcialmente función nerviosa.$q$)),
  (47, 'gen-nat-22', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-cuerpo', '21-25', 'Ciencias naturales: cuerpo humano y salud',
   $q$En educación básica, el docente aborda nutrición, sistemas del cuerpo humano, prevención y toma de decisiones saludables desde evidencia científica y contexto familiar.$q$,
   22, $q$¿Cómo se relacionan sistema respiratorio y circulatorio?$q$,
   jsonb_build_array($q$El respiratorio intercambia gases y el circulatorio transporta oxígeno y dióxido de carbono.$q$, $q$Ambos producen alimentos mediante fotosíntesis.$q$, $q$El circulatorio solo funciona cuando no hay respiración.$q$),
   0, $q$El intercambio gaseoso y el transporte sanguíneo permiten suministro de oxígeno y eliminación de CO2.$q$,
   jsonb_build_array($q$Correcta: integra sistemas.$q$, $q$Incorrecta: la fotosíntesis no ocurre en sistemas humanos.$q$, $q$Incorrecta: ambos sistemas funcionan de manera coordinada.$q$)),
  (48, 'gen-nat-23', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-cuerpo', '21-25', 'Ciencias naturales: cuerpo humano y salud',
   $q$En educación básica, el docente aborda nutrición, sistemas del cuerpo humano, prevención y toma de decisiones saludables desde evidencia científica y contexto familiar.$q$,
   23, $q$¿Qué enfoque es más adecuado para enseñar prevención de enfermedades?$q$,
   jsonb_build_array($q$Analizar causas, vías de transmisión, hábitos preventivos y fuentes confiables.$q$, $q$Usar rumores locales como única explicación.$q$, $q$Centrarse solo en memorizar nombres de enfermedades.$q$),
   0, $q$La educación en salud debe promover explicación causal, prevención y pensamiento crítico sobre información.$q$,
   jsonb_build_array($q$Correcta: integra ciencia y toma de decisiones.$q$, $q$Incorrecta: los rumores no son fuente suficiente.$q$, $q$Incorrecta: memorizar nombres no garantiza prevención.$q$)),
  (49, 'gen-nat-24', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-cuerpo', '21-25', 'Ciencias naturales: cuerpo humano y salud',
   $q$En educación básica, el docente aborda nutrición, sistemas del cuerpo humano, prevención y toma de decisiones saludables desde evidencia científica y contexto familiar.$q$,
   24, $q$¿Qué evidencia permite valorar mejor el aprendizaje sobre alimentación saludable?$q$,
   jsonb_build_array($q$Un análisis de etiquetas nutricionales y una decisión argumentada para un caso familiar.$q$, $q$Una lista copiada de alimentos buenos y malos sin criterios.$q$, $q$Una cartelera decorativa sin relación con nutrientes.$q$),
   0, $q$Analizar etiquetas y argumentar decisiones evidencia uso de conceptos en contexto.$q$,
   jsonb_build_array($q$Correcta: aplica información científica a decisiones.$q$, $q$Incorrecta: clasifica sin criterios claros.$q$, $q$Incorrecta: la decoración no evidencia comprensión.$q$)),
  (50, 'gen-nat-25', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-cuerpo', '21-25', 'Ciencias naturales: cuerpo humano y salud',
   $q$En educación básica, el docente aborda nutrición, sistemas del cuerpo humano, prevención y toma de decisiones saludables desde evidencia científica y contexto familiar.$q$,
   25, $q$Ante una creencia familiar contraria a evidencia científica sobre vacunación, ¿qué acción docente es más pertinente?$q$,
   jsonb_build_array($q$Promover análisis respetuoso de fuentes confiables y remitir a orientación sanitaria competente.$q$, $q$Ridiculizar públicamente a la familia para imponer autoridad.$q$, $q$Ignorar el tema aunque afecte decisiones de salud escolar.$q$),
   0, $q$El docente debe actuar con respeto, pensamiento crítico y articulación con fuentes sanitarias confiables.$q$,
   jsonb_build_array($q$Correcta: combina respeto, evidencia y ruta institucional.$q$, $q$Incorrecta: vulnera la relación escuela-familia.$q$, $q$Incorrecta: evita una oportunidad formativa y preventiva.$q$))
)
insert into public.quiz_questions (
  external_id,
  test_id,
  test_title,
  category,
  block_id,
  block_range,
  topic,
  situation,
  question_number,
  prompt,
  options,
  correct_answer,
  explanation,
  option_feedback,
  sequence,
  active
)
select
  new_questions.external_id,
  new_questions.test_id,
  new_questions.test_title,
  'especificos',
  new_questions.block_id,
  new_questions.block_range,
  new_questions.topic,
  new_questions.situation,
  new_questions.question_number,
  new_questions.prompt,
  new_questions.options,
  new_questions.correct_answer,
  new_questions.explanation,
  new_questions.option_feedback,
  base_sequence.value + new_questions.position,
  true
from new_questions
cross join base_sequence
on conflict (external_id) do update set
  test_id = excluded.test_id,
  test_title = excluded.test_title,
  category = excluded.category,
  block_id = excluded.block_id,
  block_range = excluded.block_range,
  topic = excluded.topic,
  situation = excluded.situation,
  question_number = excluded.question_number,
  prompt = excluded.prompt,
  options = excluded.options,
  correct_answer = excluded.correct_answer,
  explanation = excluded.explanation,
  option_feedback = excluded.option_feedback,
  sequence = excluded.sequence,
  active = true;

update public.quiz_questions
set
  options = jsonb_build_array(options ->> 1, options ->> 0, options ->> 2),
  option_feedback = jsonb_build_array(option_feedback ->> 1, option_feedback ->> 0, option_feedback ->> 2),
  correct_answer = 1
where external_id in (
  'gen-chem-02', 'gen-chem-05', 'gen-chem-08', 'gen-chem-11', 'gen-chem-14',
  'gen-chem-17', 'gen-chem-20', 'gen-chem-23',
  'gen-nat-02', 'gen-nat-05', 'gen-nat-08', 'gen-nat-11', 'gen-nat-14',
  'gen-nat-17', 'gen-nat-20', 'gen-nat-23'
);

update public.quiz_questions
set
  options = jsonb_build_array(options ->> 1, options ->> 2, options ->> 0),
  option_feedback = jsonb_build_array(option_feedback ->> 1, option_feedback ->> 2, option_feedback ->> 0),
  correct_answer = 2
where external_id in (
  'gen-chem-03', 'gen-chem-06', 'gen-chem-09', 'gen-chem-12', 'gen-chem-15',
  'gen-chem-18', 'gen-chem-21', 'gen-chem-24',
  'gen-nat-03', 'gen-nat-06', 'gen-nat-09', 'gen-nat-12', 'gen-nat-15',
  'gen-nat-18', 'gen-nat-21', 'gen-nat-24'
);
