with base_sequence as (
  select coalesce(max(sequence), 0) + 1000 as value
  from public.quiz_questions
),
new_questions (
  position, external_id, test_id, test_title, block_id, block_range, topic, situation,
  question_number, prompt, options, correct_answer, explanation, option_feedback
) as (
  values
  (1, 'gen-chem-26', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-termodinamica', '26-30', 'Química: energía y velocidad de reacción',
   $q$En una secuencia sobre energía química, el docente compara reacciones endotérmicas, exotérmicas, velocidad de reacción y factores que modifican la frecuencia de choques efectivos entre partículas.$q$,
   26, $q$Una reacción exotérmica se caracteriza porque:$q$,
   jsonb_build_array($q$Libera energía al entorno y los productos tienen menor energía que los reactivos.$q$, $q$Absorbe energía y siempre se detiene al iniciar.$q$, $q$No implica transformación de enlaces químicos.$q$),
   0, $q$En una reacción exotérmica el sistema transfiere energía al entorno y se forman productos más estables energéticamente.$q$,
   jsonb_build_array($q$Correcta: relaciona transferencia de energía y estabilidad.$q$,$q$Incorrecta: describe de forma parcial una reacción endotérmica.$q$,$q$Incorrecta: las reacciones químicas implican ruptura y formación de enlaces.$q$)),
  (2, 'gen-chem-27', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-termodinamica', '26-30', 'Química: energía y velocidad de reacción',
   $q$En una secuencia sobre energía química, el docente compara reacciones endotérmicas, exotérmicas, velocidad de reacción y factores que modifican la frecuencia de choques efectivos entre partículas.$q$,
   27, $q$¿Qué efecto tiene aumentar la temperatura en muchas reacciones químicas?$q$,
   jsonb_build_array($q$Aumenta la energía cinética de las partículas y puede incrementar los choques efectivos.$q$, $q$Disminuye siempre la energía cinética hasta cero.$q$, $q$Convierte todos los reactivos en gases nobles.$q$),
   0, $q$Al aumentar la temperatura aumenta la energía cinética promedio, lo que puede incrementar la velocidad de reacción.$q$,
   jsonb_build_array($q$Correcta: usa teoría de colisiones.$q$,$q$Incorrecta: contradice la relación temperatura-energía cinética.$q$,$q$Incorrecta: no hay transmutación química hacia gases nobles.$q$)),
  (3, 'gen-chem-28', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-termodinamica', '26-30', 'Química: energía y velocidad de reacción',
   $q$En una secuencia sobre energía química, el docente compara reacciones endotérmicas, exotérmicas, velocidad de reacción y factores que modifican la frecuencia de choques efectivos entre partículas.$q$,
   28, $q$Un catalizador actúa principalmente porque:$q$,
   jsonb_build_array($q$Ofrece una ruta alternativa con menor energía de activación.$q$, $q$Aumenta la masa total de productos sin conservar átomos.$q$, $q$Cambia la constante de equilibrio solo por estar presente.$q$),
   0, $q$Los catalizadores aceleran la reacción al disminuir la energía de activación, sin consumirse globalmente.$q$,
   jsonb_build_array($q$Correcta: define el papel cinético del catalizador.$q$,$q$Incorrecta: no viola conservación de masa.$q$,$q$Incorrecta: el catalizador no cambia la posición de equilibrio.$q$)),
  (4, 'gen-chem-29', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-termodinamica', '26-30', 'Química: energía y velocidad de reacción',
   $q$En una secuencia sobre energía química, el docente compara reacciones endotérmicas, exotérmicas, velocidad de reacción y factores que modifican la frecuencia de choques efectivos entre partículas.$q$,
   29, $q$¿Qué evidencia experimental permite comparar velocidades de reacción?$q$,
   jsonb_build_array($q$Medir el volumen de gas producido por unidad de tiempo bajo condiciones controladas.$q$, $q$Comparar únicamente el color de los cuadernos de cada grupo.$q$, $q$Cambiar temperatura, concentración y masa al mismo tiempo sin registro.$q$),
   0, $q$La velocidad se evalúa midiendo cambios de reactivos o productos respecto al tiempo, controlando variables.$q$,
   jsonb_build_array($q$Correcta: propone una variable medible y control.$q$,$q$Incorrecta: no es evidencia química.$q$,$q$Incorrecta: impide atribuir causas.$q$)),
  (5, 'gen-chem-30', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-termodinamica', '26-30', 'Química: energía y velocidad de reacción',
   $q$En una secuencia sobre energía química, el docente compara reacciones endotérmicas, exotérmicas, velocidad de reacción y factores que modifican la frecuencia de choques efectivos entre partículas.$q$,
   30, $q$Para estudiantes con dificultades en gráficas de energía, la mejor mediación es:$q$,
   jsonb_build_array($q$Relacionar eje de energía, avance de reacción, energía de activación y diferencia entre reactivos y productos.$q$, $q$Pedir copiar la gráfica sin interpretar sus partes.$q$, $q$Eliminar las gráficas de la clase porque son abstractas.$q$),
   0, $q$La mediación debe hacer explícitas las variables y la lectura conceptual de la representación.$q$,
   jsonb_build_array($q$Correcta: articula representación y significado químico.$q$,$q$Incorrecta: copiar no asegura comprensión.$q$,$q$Incorrecta: evita una representación clave.$q$)),

  (6, 'gen-chem-31', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-redox', '31-36', 'Química: electroquímica y reacciones redox',
   $q$En una actividad sobre oxidación-reducción, los estudiantes analizan corrosión de metales, pilas sencillas y transferencia de electrones en situaciones cotidianas.$q$,
   31, $q$En una reacción redox, la oxidación corresponde a:$q$,
   jsonb_build_array($q$Pérdida de electrones por una especie química.$q$, $q$Ganancia obligatoria de protones en toda reacción.$q$, $q$Desaparición de la masa del sistema.$q$),
   0, $q$Oxidación es pérdida de electrones; reducción es ganancia de electrones.$q$,
   jsonb_build_array($q$Correcta: usa la definición electrónica.$q$,$q$Incorrecta: confunde redox con ácido-base.$q$,$q$Incorrecta: la masa se conserva.$q$)),
  (7, 'gen-chem-32', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-redox', '31-36', 'Química: electroquímica y reacciones redox',
   $q$En una actividad sobre oxidación-reducción, los estudiantes analizan corrosión de metales, pilas sencillas y transferencia de electrones en situaciones cotidianas.$q$,
   32, $q$Si el hierro se oxida durante la corrosión, esto implica que:$q$,
   jsonb_build_array($q$El hierro pierde electrones y aumenta su número de oxidación.$q$, $q$El hierro gana electrones y se vuelve gas noble.$q$, $q$El hierro deja de ser elemento químico por evaporación inmediata.$q$),
   0, $q$La corrosión del hierro involucra oxidación: pérdida de electrones y aumento del número de oxidación.$q$,
   jsonb_build_array($q$Correcta: vincula proceso cotidiano con redox.$q$,$q$Incorrecta: describe reducción, no oxidación.$q$,$q$Incorrecta: no corresponde al fenómeno.$q$)),
  (8, 'gen-chem-33', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-redox', '31-36', 'Química: electroquímica y reacciones redox',
   $q$En una actividad sobre oxidación-reducción, los estudiantes analizan corrosión de metales, pilas sencillas y transferencia de electrones en situaciones cotidianas.$q$,
   33, $q$En una pila galvánica, la energía eléctrica se origina principalmente por:$q$,
   jsonb_build_array($q$Una reacción redox espontánea que separa procesos de oxidación y reducción.$q$, $q$La creación de electrones desde la nada.$q$, $q$La neutralización de todas las moléculas de agua del ambiente.$q$),
   0, $q$Las pilas convierten energía química de una reacción redox espontánea en energía eléctrica.$q$,
   jsonb_build_array($q$Correcta: explica el principio de funcionamiento.$q$,$q$Incorrecta: no se crean electrones.$q$,$q$Incorrecta: no describe una pila galvánica.$q$)),
  (9, 'gen-chem-34', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-redox', '31-36', 'Química: electroquímica y reacciones redox',
   $q$En una actividad sobre oxidación-reducción, los estudiantes analizan corrosión de metales, pilas sencillas y transferencia de electrones en situaciones cotidianas.$q$,
   34, $q$¿Qué pregunta conecta redox con ciudadanía ambiental?$q$,
   jsonb_build_array($q$¿Cómo deben disponerse pilas usadas para evitar liberación de metales y contaminantes?$q$, $q$¿Qué pila tiene el empaque más brillante?$q$, $q$¿Cuántas pilas caben en una cartelera sin analizar residuos?$q$),
   0, $q$La gestión de pilas usadas permite relacionar electroquímica, contaminación y decisiones responsables.$q$,
   jsonb_build_array($q$Correcta: integra conocimiento químico y ambiente.$q$,$q$Incorrecta: el brillo del empaque no aborda impacto ambiental.$q$,$q$Incorrecta: no analiza el problema químico.$q$)),
  (10, 'gen-chem-35', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-redox', '31-36', 'Química: electroquímica y reacciones redox',
   $q$En una actividad sobre oxidación-reducción, los estudiantes analizan corrosión de metales, pilas sencillas y transferencia de electrones en situaciones cotidianas.$q$,
   35, $q$Para identificar agente oxidante se debe reconocer la especie que:$q$,
   jsonb_build_array($q$Se reduce al aceptar electrones de otra especie.$q$, $q$Se oxida al perder electrones y por eso siempre es producto.$q$, $q$No participa en la reacción.$q$),
   0, $q$El agente oxidante causa oxidación en otra especie y se reduce al ganar electrones.$q$,
   jsonb_build_array($q$Correcta: distingue agente oxidante y proceso propio.$q$,$q$Incorrecta: describe al agente reductor.$q$,$q$Incorrecta: un agente participa en la reacción.$q$)),
  (11, 'gen-chem-36', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-redox', '31-36', 'Química: electroquímica y reacciones redox',
   $q$En una actividad sobre oxidación-reducción, los estudiantes analizan corrosión de metales, pilas sencillas y transferencia de electrones en situaciones cotidianas.$q$,
   36, $q$Una evaluación pertinente sobre redox debería pedir al estudiante:$q$,
   jsonb_build_array($q$Identificar transferencia de electrones, justificar oxidación-reducción y relacionarla con un caso.$q$, $q$Memorizar solo símbolos de metales sin explicar procesos.$q$, $q$Evitar situaciones reales porque confunden la teoría.$q$),
   0, $q$La competencia se evidencia al aplicar el modelo redox a fenómenos y argumentar con conceptos.$q$,
   jsonb_build_array($q$Correcta: evalúa comprensión aplicada.$q$,$q$Incorrecta: memorizar símbolos es insuficiente.$q$,$q$Incorrecta: los contextos favorecen transferencia.$q$)),

  (12, 'gen-chem-37', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-ambiental', '37-42', 'Química: ambiente, análisis y sociedad',
   $q$La institución participa en un proyecto de aula sobre contaminación atmosférica y del agua. El docente busca que los estudiantes interpreten datos químicos y propongan acciones viables para su contexto.$q$,
   37, $q$La lluvia ácida se relaciona principalmente con:$q$,
   jsonb_build_array($q$Óxidos de azufre y nitrógeno que forman ácidos en la atmósfera.$q$, $q$Aumento exclusivo de oxígeno molecular puro.$q$, $q$Evaporación de agua destilada sin interacción con gases.$q$),
   0, $q$SOx y NOx pueden reaccionar en la atmósfera y generar ácidos que disminuyen el pH de la precipitación.$q$,
   jsonb_build_array($q$Correcta: identifica causas químicas.$q$,$q$Incorrecta: oxígeno molecular no explica lluvia ácida.$q$,$q$Incorrecta: ignora reacciones atmosféricas.$q$)),
  (13, 'gen-chem-38', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-ambiental', '37-42', 'Química: ambiente, análisis y sociedad',
   $q$La institución participa en un proyecto de aula sobre contaminación atmosférica y del agua. El docente busca que los estudiantes interpreten datos químicos y propongan acciones viables para su contexto.$q$,
   38, $q$¿Qué dato permite valorar mejor contaminación por nitratos en agua?$q$,
   jsonb_build_array($q$Concentración medida, comparación con referente y análisis de fuente probable.$q$, $q$Opinión aislada de un estudiante sobre el sabor.$q$, $q$Color del recipiente usado para transportar la muestra.$q$),
   0, $q$La valoración requiere dato cuantitativo, criterio de comparación y análisis de origen.$q$,
   jsonb_build_array($q$Correcta: integra medición e interpretación.$q$,$q$Incorrecta: el sabor no basta ni es seguro.$q$,$q$Incorrecta: el recipiente no es indicador directo.$q$)),
  (14, 'gen-chem-39', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-ambiental', '37-42', 'Química: ambiente, análisis y sociedad',
   $q$La institución participa en un proyecto de aula sobre contaminación atmosférica y del agua. El docente busca que los estudiantes interpreten datos químicos y propongan acciones viables para su contexto.$q$,
   39, $q$Una propuesta escolar ante contaminación química debe priorizar:$q$,
   jsonb_build_array($q$Acciones basadas en evidencia, prevención de exposición y articulación con autoridades competentes.$q$, $q$Manipular contaminantes sin protección para aprender más rápido.$q$, $q$Publicar culpables sin verificar datos.$q$),
   0, $q$La respuesta educativa debe ser segura, basada en evidencia y responsable institucionalmente.$q$,
   jsonb_build_array($q$Correcta: integra ciencia, seguridad y ciudadanía.$q$,$q$Incorrecta: aumenta riesgos.$q$,$q$Incorrecta: no respeta evidencia ni debido proceso.$q$)),
  (15, 'gen-chem-40', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-ambiental', '37-42', 'Química: ambiente, análisis y sociedad',
   $q$La institución participa en un proyecto de aula sobre contaminación atmosférica y del agua. El docente busca que los estudiantes interpreten datos químicos y propongan acciones viables para su contexto.$q$,
   40, $q$¿Qué competencia científica se evidencia al comparar datos de pH de varias fuentes de agua?$q$,
   jsonb_build_array($q$Interpretar evidencia, reconocer variabilidad y justificar conclusiones.$q$, $q$Copiar números sin unidades ni contexto.$q$, $q$Elegir el dato que confirme una idea previa y descartar los demás.$q$),
   0, $q$Comparar datos exige análisis de evidencia, unidades, incertidumbre y argumentación.$q$,
   jsonb_build_array($q$Correcta: describe competencia de indagación.$q$,$q$Incorrecta: copiar no interpreta.$q$,$q$Incorrecta: introduce sesgo de confirmación.$q$)),
  (16, 'gen-chem-41', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-ambiental', '37-42', 'Química: ambiente, análisis y sociedad',
   $q$La institución participa en un proyecto de aula sobre contaminación atmosférica y del agua. El docente busca que los estudiantes interpreten datos químicos y propongan acciones viables para su contexto.$q$,
   41, $q$Para explicar efecto invernadero desde química atmosférica, conviene destacar que:$q$,
   jsonb_build_array($q$Algunos gases absorben radiación infrarroja y alteran el balance energético terrestre.$q$, $q$Todos los gases de la atmósfera tienen exactamente el mismo efecto.$q$, $q$El efecto invernadero no tiene relación con moléculas.$q$),
   0, $q$Gases como CO2, CH4 y vapor de agua interactúan con radiación infrarroja y participan en el balance térmico.$q$,
   jsonb_build_array($q$Correcta: relaciona moléculas y radiación.$q$,$q$Incorrecta: los gases tienen comportamientos distintos.$q$,$q$Incorrecta: el fenómeno depende de propiedades moleculares.$q$)),
  (17, 'gen-chem-42', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-ambiental', '37-42', 'Química: ambiente, análisis y sociedad',
   $q$La institución participa en un proyecto de aula sobre contaminación atmosférica y del agua. El docente busca que los estudiantes interpreten datos químicos y propongan acciones viables para su contexto.$q$,
   42, $q$¿Qué decisión didáctica fortalece pensamiento crítico sobre noticias ambientales?$q$,
   jsonb_build_array($q$Contrastar fuente, datos, método y conclusiones antes de aceptar una afirmación.$q$, $q$Aceptar cualquier publicación viral si tiene imágenes llamativas.$q$, $q$Evitar el análisis de fuentes porque no pertenece a química.$q$),
   0, $q$El pensamiento crítico científico exige evaluar evidencia, fuente y método.$q$,
   jsonb_build_array($q$Correcta: aplica alfabetización científica.$q$,$q$Incorrecta: viralidad no es validez.$q$,$q$Incorrecta: analizar evidencia también es parte de ciencias.$q$)),

  (18, 'gen-chem-43', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-evaluacion', '43-46', 'Química: evaluación de competencias específicas',
   $q$El docente prepara preguntas tipo concurso para evaluar no solo memoria química, sino uso de conceptos en situaciones de aula, laboratorio, ambiente y resolución de problemas.$q$,
   43, $q$Una pregunta de mayor calidad para evaluar nomenclatura debería:$q$,
   jsonb_build_array($q$Pedir nombrar o formular una sustancia y justificar la regla aplicada en contexto.$q$, $q$Preguntar únicamente si al estudiante le gusta el nombre de la sustancia.$q$, $q$Evitar toda relación entre fórmula, nombre y composición.$q$),
   0, $q$La nomenclatura se evalúa mejor cuando el estudiante aplica reglas a fórmulas o nombres y justifica su uso.$q$,
   jsonb_build_array($q$Correcta: evalúa aplicación de reglas.$q$,$q$Incorrecta: es una preferencia, no conocimiento químico.$q$,$q$Incorrecta: fórmula, nombre y composición deben relacionarse.$q$)),
  (19, 'gen-chem-44', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-evaluacion', '43-46', 'Química: evaluación de competencias específicas',
   $q$El docente prepara preguntas tipo concurso para evaluar no solo memoria química, sino uso de conceptos en situaciones de aula, laboratorio, ambiente y resolución de problemas.$q$,
   44, $q$¿Qué opción refleja mejor evaluación por competencias en química?$q$,
   jsonb_build_array($q$Resolver un problema contextualizado, explicar el procedimiento y valorar la coherencia del resultado.$q$, $q$Premiar solo la respuesta numérica sin unidades ni procedimiento.$q$, $q$Calificar por velocidad sin revisar razonamiento.$q$),
   0, $q$La competencia incluye procedimiento, justificación, unidades, interpretación y coherencia del resultado.$q$,
   jsonb_build_array($q$Correcta: integra razonamiento y resultado.$q$,$q$Incorrecta: la respuesta aislada puede ocultar errores.$q$,$q$Incorrecta: velocidad no reemplaza comprensión.$q$)),
  (20, 'gen-chem-45', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-evaluacion', '43-46', 'Química: evaluación de competencias específicas',
   $q$El docente prepara preguntas tipo concurso para evaluar no solo memoria química, sino uso de conceptos en situaciones de aula, laboratorio, ambiente y resolución de problemas.$q$,
   45, $q$Si muchos estudiantes fallan una pregunta sobre molaridad, la mejor acción docente es:$q$,
   jsonb_build_array($q$Analizar el error común, retroalimentar unidades y diseñar nueva práctica guiada.$q$, $q$Eliminar el tema porque resultó difícil.$q$, $q$Repetir la misma prueba sin intervención.$q$),
   0, $q$El análisis de errores permite ajustar enseñanza y fortalecer aprendizaje.$q$,
   jsonb_build_array($q$Correcta: usa evaluación para mejorar enseñanza.$q$,$q$Incorrecta: baja expectativas curriculares.$q$,$q$Incorrecta: no atiende la causa del error.$q$)),
  (21, 'gen-chem-46', 'generado-quimica-01', 'Simulacro nuevo · Química', 'quimica-evaluacion', '43-46', 'Química: evaluación de competencias específicas',
   $q$El docente prepara preguntas tipo concurso para evaluar no solo memoria química, sino uso de conceptos en situaciones de aula, laboratorio, ambiente y resolución de problemas.$q$,
   46, $q$¿Qué rasgo deben tener los distractores en una pregunta tipo concurso?$q$,
   jsonb_build_array($q$Ser plausibles y representar errores frecuentes sin ser ambiguos frente a la clave.$q$, $q$Ser absurdos para que todos respondan sin analizar.$q$, $q$Contradecir el enunciado correcto de forma evidente y sin relación con el tema.$q$),
   0, $q$Buenos distractores permiten discriminar comprensión porque recogen errores conceptuales razonables.$q$,
   jsonb_build_array($q$Correcta: mejora validez de la pregunta.$q$,$q$Incorrecta: no discrimina aprendizajes.$q$,$q$Incorrecta: distractores sin relación reducen calidad.$q$)),

  (22, 'gen-nat-26', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-evolucion', '26-30', 'Ciencias naturales: evolución y biodiversidad',
   $q$En una clase sobre biodiversidad colombiana, el docente conecta variación, adaptación, selección natural y conservación de especies con casos de ecosistemas locales.$q$,
   26, $q$La selección natural ocurre cuando:$q$,
   jsonb_build_array($q$Individuos con rasgos heredables ventajosos dejan más descendencia en un ambiente dado.$q$, $q$Todos los organismos deciden cambiar sus rasgos durante la vida.$q$, $q$Las especies aparecen sin variación ni herencia.$q$),
   0, $q$La selección natural actúa sobre variación heredable y afecta éxito reproductivo diferencial.$q$,
   jsonb_build_array($q$Correcta: integra variación, herencia y ambiente.$q$,$q$Incorrecta: no es una decisión individual.$q$,$q$Incorrecta: niega condiciones básicas del proceso.$q$)),
  (23, 'gen-nat-27', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-evolucion', '26-30', 'Ciencias naturales: evolución y biodiversidad',
   $q$En una clase sobre biodiversidad colombiana, el docente conecta variación, adaptación, selección natural y conservación de especies con casos de ecosistemas locales.$q$,
   27, $q$¿Qué ejemplo representa una adaptación?$q$,
   jsonb_build_array($q$Una característica heredable que mejora supervivencia o reproducción en cierto ambiente.$q$, $q$Un aprendizaje individual que no puede heredarse nunca.$q$, $q$Un cambio de color de una cartelera escolar.$q$),
   0, $q$Una adaptación es un rasgo heredable favorecido en un contexto ambiental por su efecto en supervivencia o reproducción.$q$,
   jsonb_build_array($q$Correcta: define adaptación evolutiva.$q$,$q$Incorrecta: aprendizaje individual no equivale a adaptación evolutiva.$q$,$q$Incorrecta: no es un rasgo biológico.$q$)),
  (24, 'gen-nat-28', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-evolucion', '26-30', 'Ciencias naturales: evolución y biodiversidad',
   $q$En una clase sobre biodiversidad colombiana, el docente conecta variación, adaptación, selección natural y conservación de especies con casos de ecosistemas locales.$q$,
   28, $q$Para enseñar biodiversidad de forma contextualizada, conviene:$q$,
   jsonb_build_array($q$Analizar especies locales, relaciones ecológicas, amenazas y acciones de conservación.$q$, $q$Memorizar nombres aislados sin ubicación ni función ecológica.$q$, $q$Evitar ecosistemas cercanos porque no son científicos.$q$),
   0, $q$El contexto local facilita comprensión de biodiversidad, interacciones y conservación.$q$,
   jsonb_build_array($q$Correcta: articula ciencia y territorio.$q$,$q$Incorrecta: nombres aislados no bastan.$q$,$q$Incorrecta: lo local puede ser objeto de investigación rigurosa.$q$)),
  (25, 'gen-nat-29', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-evolucion', '26-30', 'Ciencias naturales: evolución y biodiversidad',
   $q$En una clase sobre biodiversidad colombiana, el docente conecta variación, adaptación, selección natural y conservación de especies con casos de ecosistemas locales.$q$,
   29, $q$La pérdida de hábitat afecta la biodiversidad porque:$q$,
   jsonb_build_array($q$Reduce recursos, refugios y condiciones necesarias para poblaciones y comunidades.$q$, $q$Aumenta siempre la diversidad genética de todas las especies.$q$, $q$No modifica interacciones entre organismos.$q$),
   0, $q$La pérdida de hábitat reduce condiciones para supervivencia y reproducción, afectando poblaciones y redes ecológicas.$q$,
   jsonb_build_array($q$Correcta: explica el impacto ecológico.$q$,$q$Incorrecta: no es un efecto general esperado.$q$,$q$Incorrecta: sí modifica interacciones.$q$)),
  (26, 'gen-nat-30', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-evolucion', '26-30', 'Ciencias naturales: evolución y biodiversidad',
   $q$En una clase sobre biodiversidad colombiana, el docente conecta variación, adaptación, selección natural y conservación de especies con casos de ecosistemas locales.$q$,
   30, $q$Una evidencia adecuada de comprensión sobre evolución es:$q$,
   jsonb_build_array($q$Explicar un caso usando variación, herencia, presión ambiental y reproducción diferencial.$q$, $q$Afirmar que los organismos cambian porque quieren mejorar.$q$, $q$Repetir que evolución significa progreso obligatorio.$q$),
   0, $q$La explicación evolutiva debe evitar finalismo y usar mecanismos científicos.$q$,
   jsonb_build_array($q$Correcta: usa el modelo evolutivo.$q$,$q$Incorrecta: es una explicación finalista.$q$,$q$Incorrecta: evolución no implica progreso lineal obligatorio.$q$)),

  (27, 'gen-nat-31', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-tierra', '31-36', 'Ciencias naturales: Tierra, clima y recursos',
   $q$El área de ciencias desarrolla un proyecto sobre cambio climático, suelo, ciclo del agua y gestión del riesgo en el municipio.$q$,
   31, $q$El ciclo del agua incluye principalmente:$q$,
   jsonb_build_array($q$Evaporación, condensación, precipitación, infiltración y escorrentía.$q$, $q$Fotosíntesis, digestión y respiración exclusivamente.$q$, $q$Fusión nuclear dentro del núcleo terrestre.$q$),
   0, $q$El ciclo hidrológico describe cambios y movimientos del agua en atmósfera, superficie y subsuelo.$q$,
   jsonb_build_array($q$Correcta: identifica procesos del ciclo.$q$,$q$Incorrecta: mezcla procesos biológicos.$q$,$q$Incorrecta: no corresponde al ciclo del agua.$q$)),
  (28, 'gen-nat-32', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-tierra', '31-36', 'Ciencias naturales: Tierra, clima y recursos',
   $q$El área de ciencias desarrolla un proyecto sobre cambio climático, suelo, ciclo del agua y gestión del riesgo en el municipio.$q$,
   32, $q$¿Qué diferencia clima y tiempo atmosférico?$q$,
   jsonb_build_array($q$El tiempo describe condiciones de corto plazo; el clima patrones estadísticos de largo plazo.$q$, $q$Son sinónimos y nunca requieren datos.$q$, $q$El clima solo existe de noche y el tiempo de día.$q$),
   0, $q$Clima y tiempo atmosférico se distinguen por escala temporal y tratamiento de datos.$q$,
   jsonb_build_array($q$Correcta: diferencia escalas.$q$,$q$Incorrecta: confunde conceptos.$q$,$q$Incorrecta: no tiene fundamento científico.$q$)),
  (29, 'gen-nat-33', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-tierra', '31-36', 'Ciencias naturales: Tierra, clima y recursos',
   $q$El área de ciencias desarrolla un proyecto sobre cambio climático, suelo, ciclo del agua y gestión del riesgo en el municipio.$q$,
   33, $q$Para analizar erosión del suelo, una variable pertinente es:$q$,
   jsonb_build_array($q$Cobertura vegetal, pendiente, tipo de suelo y presencia de escorrentía.$q$, $q$Número de pupitres en el salón.$q$, $q$Color de la mochila del observador.$q$),
   0, $q$La erosión depende de factores físicos y de cobertura que afectan desprendimiento y transporte de suelo.$q$,
   jsonb_build_array($q$Correcta: selecciona variables relevantes.$q$,$q$Incorrecta: no explica erosión.$q$,$q$Incorrecta: no es variable científica del fenómeno.$q$)),
  (30, 'gen-nat-34', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-tierra', '31-36', 'Ciencias naturales: Tierra, clima y recursos',
   $q$El área de ciencias desarrolla un proyecto sobre cambio climático, suelo, ciclo del agua y gestión del riesgo en el municipio.$q$,
   34, $q$Una medida de adaptación al cambio climático en la escuela podría ser:$q$,
   jsonb_build_array($q$Diseñar ahorro de agua, sombra, monitoreo de temperatura y gestión de riesgo local.$q$, $q$Negar los datos climáticos porque incomodan.$q$, $q$Aumentar desperdicio de agua para observar sequía.$q$),
   0, $q$La adaptación reduce vulnerabilidad mediante decisiones contextualizadas basadas en datos.$q$,
   jsonb_build_array($q$Correcta: propone acciones viables y contextualizadas.$q$,$q$Incorrecta: niega evidencia.$q$,$q$Incorrecta: es irresponsable ambientalmente.$q$)),
  (31, 'gen-nat-35', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-tierra', '31-36', 'Ciencias naturales: Tierra, clima y recursos',
   $q$El área de ciencias desarrolla un proyecto sobre cambio climático, suelo, ciclo del agua y gestión del riesgo en el municipio.$q$,
   35, $q$¿Qué dato permite discutir cambio climático con rigor escolar?$q$,
   jsonb_build_array($q$Series históricas de temperatura o precipitación analizadas con tendencia y variabilidad.$q$, $q$Una tarde calurosa aislada como única prueba.$q$, $q$Una opinión sin fuente ni medición.$q$),
   0, $q$El cambio climático se analiza con series de datos de largo plazo, no con eventos aislados.$q$,
   jsonb_build_array($q$Correcta: usa evidencia temporal adecuada.$q$,$q$Incorrecta: un día no define clima.$q$,$q$Incorrecta: no es evidencia científica.$q$)),
  (32, 'gen-nat-36', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-tierra', '31-36', 'Ciencias naturales: Tierra, clima y recursos',
   $q$El área de ciencias desarrolla un proyecto sobre cambio climático, suelo, ciclo del agua y gestión del riesgo en el municipio.$q$,
   36, $q$La gestión del riesgo en ciencias debe promover:$q$,
   jsonb_build_array($q$Reconocimiento de amenazas, vulnerabilidades, prevención y respuesta informada.$q$, $q$Improvisación sin análisis del territorio.$q$, $q$Ocultar mapas de riesgo para evitar preguntas.$q$),
   0, $q$La educación científica contribuye a comprender riesgos y tomar decisiones preventivas.$q$,
   jsonb_build_array($q$Correcta: integra territorio y prevención.$q$,$q$Incorrecta: improvisar aumenta vulnerabilidad.$q$,$q$Incorrecta: ocultar información impide prevención.$q$)),

  (33, 'gen-nat-37', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-quimica-integrada', '37-42', 'Ciencias naturales: materia y energía integradas',
   $q$En una unidad integrada, el docente conecta química, física y biología para explicar nutrición, combustión, energía en ecosistemas y transformación de la materia.$q$,
   37, $q$En una cadena alimentaria, la energía fluye principalmente desde:$q$,
   jsonb_build_array($q$Productores hacia consumidores y descomponedores, con pérdidas en forma de calor.$q$, $q$Consumidores terciarios hacia el Sol sin pérdidas.$q$, $q$Rocas hacia pupitres por enlace iónico.$q$),
   0, $q$La energía entra por productores y se transfiere entre niveles tróficos con pérdidas energéticas.$q$,
   jsonb_build_array($q$Correcta: integra energía y ecosistemas.$q$,$q$Incorrecta: invierte el flujo y niega pérdidas.$q$,$q$Incorrecta: no corresponde a ecología.$q$)),
  (34, 'gen-nat-38', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-quimica-integrada', '37-42', 'Ciencias naturales: materia y energía integradas',
   $q$En una unidad integrada, el docente conecta química, física y biología para explicar nutrición, combustión, energía en ecosistemas y transformación de la materia.$q$,
   38, $q$La fotosíntesis puede explicarse como un proceso en el que:$q$,
   jsonb_build_array($q$Se transforma energía luminosa en energía química almacenada en moléculas orgánicas.$q$, $q$Se destruyen átomos para formar luz.$q$, $q$Los animales producen clorofila en los pulmones.$q$),
   0, $q$La fotosíntesis transforma energía y materia para producir compuestos orgánicos a partir de CO2 y agua.$q$,
   jsonb_build_array($q$Correcta: relaciona energía y materia.$q$,$q$Incorrecta: no destruye átomos.$q$,$q$Incorrecta: animales no fotosintetizan con pulmones.$q$)),
  (35, 'gen-nat-39', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-quimica-integrada', '37-42', 'Ciencias naturales: materia y energía integradas',
   $q$En una unidad integrada, el docente conecta química, física y biología para explicar nutrición, combustión, energía en ecosistemas y transformación de la materia.$q$,
   39, $q$¿Qué enunciado integra respiración celular y conservación de la materia?$q$,
   jsonb_build_array($q$La glucosa y el oxígeno se transforman en dióxido de carbono, agua y energía utilizable.$q$, $q$La glucosa desaparece sin productos.$q$, $q$El oxígeno se convierte en nitrógeno por voluntad celular.$q$),
   0, $q$La respiración celular transforma sustancias conservando átomos y liberando energía para la célula.$q$,
   jsonb_build_array($q$Correcta: integra química y biología.$q$,$q$Incorrecta: no conserva materia.$q$,$q$Incorrecta: no ocurre transmutación voluntaria.$q$)),
  (36, 'gen-nat-40', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-quimica-integrada', '37-42', 'Ciencias naturales: materia y energía integradas',
   $q$En una unidad integrada, el docente conecta química, física y biología para explicar nutrición, combustión, energía en ecosistemas y transformación de la materia.$q$,
   40, $q$Una situación cotidiana para integrar combustión y ambiente es:$q$,
   jsonb_build_array($q$Comparar combustibles, productos de combustión y efectos en calidad del aire.$q$, $q$Escoger el combustible por el color de su envase.$q$, $q$Afirmar que quemar no produce sustancias nuevas.$q$),
   0, $q$La combustión produce sustancias como CO2 y otros contaminantes según condiciones y combustible.$q$,
   jsonb_build_array($q$Correcta: conecta química y ambiente.$q$,$q$Incorrecta: el envase no es criterio científico.$q$,$q$Incorrecta: la combustión es reacción química.$q$)),
  (37, 'gen-nat-41', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-quimica-integrada', '37-42', 'Ciencias naturales: materia y energía integradas',
   $q$En una unidad integrada, el docente conecta química, física y biología para explicar nutrición, combustión, energía en ecosistemas y transformación de la materia.$q$,
   41, $q$¿Qué habilidad se evalúa al pedir que los estudiantes construyan un modelo de flujo de energía?$q$,
   jsonb_build_array($q$Representar relaciones, transferencias y pérdidas energéticas en un sistema.$q$, $q$Dibujar flechas sin significado.$q$, $q$Memorizar nombres sin relacionarlos.$q$),
   0, $q$Modelar implica representar componentes, relaciones y procesos de un sistema.$q$,
   jsonb_build_array($q$Correcta: evalúa modelación científica.$q$,$q$Incorrecta: una flecha sin significado no modela.$q$,$q$Incorrecta: memorizar no integra relaciones.$q$)),
  (38, 'gen-nat-42', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-quimica-integrada', '37-42', 'Ciencias naturales: materia y energía integradas',
   $q$En una unidad integrada, el docente conecta química, física y biología para explicar nutrición, combustión, energía en ecosistemas y transformación de la materia.$q$,
   42, $q$¿Qué criterio ayuda a seleccionar una actividad interdisciplinar válida?$q$,
   jsonb_build_array($q$Que cada disciplina aporte conceptos necesarios para explicar el fenómeno común.$q$, $q$Que se junten temas al azar sin relación.$q$, $q$Que se elimine la profundidad conceptual para terminar rápido.$q$),
   0, $q$La interdisciplinariedad requiere articulación conceptual auténtica alrededor de un problema o fenómeno.$q$,
   jsonb_build_array($q$Correcta: evita yuxtaposición superficial.$q$,$q$Incorrecta: juntar temas no basta.$q$,$q$Incorrecta: reduce calidad del aprendizaje.$q$)),

  (39, 'gen-nat-43', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-pedagogia-ciencias', '43-46', 'Ciencias naturales: didáctica y evaluación',
   $q$El equipo de ciencias ajusta su plan de área para fortalecer pensamiento científico, inclusión y evaluación formativa con estudiantes de diversos ritmos y contextos.$q$,
   43, $q$Una estrategia inclusiva en ciencias debe:$q$,
   jsonb_build_array($q$Ofrecer múltiples formas de observar, representar, argumentar y demostrar aprendizaje.$q$, $q$Aplicar una sola actividad rígida aunque excluya estudiantes.$q$, $q$Reducir expectativas sin apoyos ni seguimiento.$q$),
   0, $q$La inclusión requiere eliminar barreras y diversificar mediaciones manteniendo propósitos de aprendizaje.$q$,
   jsonb_build_array($q$Correcta: se alinea con apoyos y participación.$q$,$q$Incorrecta: mantiene barreras.$q$,$q$Incorrecta: bajar expectativas sin apoyos no es inclusión.$q$)),
  (40, 'gen-nat-44', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-pedagogia-ciencias', '43-46', 'Ciencias naturales: didáctica y evaluación',
   $q$El equipo de ciencias ajusta su plan de área para fortalecer pensamiento científico, inclusión y evaluación formativa con estudiantes de diversos ritmos y contextos.$q$,
   44, $q$¿Qué evidencia muestra argumentación científica?$q$,
   jsonb_build_array($q$Afirmación sustentada en datos, con razonamiento que conecta evidencia y concepto.$q$, $q$Opinión sin datos pero expresada con seguridad.$q$, $q$Respuesta copiada sin explicación.$q$),
   0, $q$La argumentación científica integra afirmación, evidencia y razonamiento.$q$,
   jsonb_build_array($q$Correcta: recoge componentes de argumentación.$q$,$q$Incorrecta: seguridad no reemplaza evidencia.$q$,$q$Incorrecta: copiar no argumenta.$q$)),
  (41, 'gen-nat-45', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-pedagogia-ciencias', '43-46', 'Ciencias naturales: didáctica y evaluación',
   $q$El equipo de ciencias ajusta su plan de área para fortalecer pensamiento científico, inclusión y evaluación formativa con estudiantes de diversos ritmos y contextos.$q$,
   45, $q$Si una práctica experimental falla, la mejor respuesta pedagógica es:$q$,
   jsonb_build_array($q$Analizar posibles causas, revisar variables y usar el error como oportunidad de indagación.$q$, $q$Ocultar el resultado para no perder autoridad.$q$, $q$Decir que la ciencia solo funciona cuando todo sale perfecto.$q$),
   0, $q$El error experimental puede convertirse en evidencia para mejorar diseño y razonamiento científico.$q$,
   jsonb_build_array($q$Correcta: aprovecha el error formativamente.$q$,$q$Incorrecta: evita aprendizaje.$q$,$q$Incorrecta: transmite una visión errada de la ciencia.$q$)),
  (42, 'gen-nat-46', 'generado-naturales-01', 'Simulacro nuevo · Ciencias Naturales', 'naturales-pedagogia-ciencias', '43-46', 'Ciencias naturales: didáctica y evaluación',
   $q$El equipo de ciencias ajusta su plan de área para fortalecer pensamiento científico, inclusión y evaluación formativa con estudiantes de diversos ritmos y contextos.$q$,
   46, $q$¿Qué decisión mejora la coherencia del plan de área de ciencias?$q$,
   jsonb_build_array($q$Alinear estándares, preguntas orientadoras, actividades de indagación y criterios de evaluación.$q$, $q$Planear actividades desconectadas de criterios y propósitos.$q$, $q$Evaluar solo asistencia sin evidencias de aprendizaje.$q$),
   0, $q$La coherencia curricular exige relación entre propósitos, actividades, evidencias y evaluación.$q$,
   jsonb_build_array($q$Correcta: articula currículo y evaluación.$q$,$q$Incorrecta: genera fragmentación.$q$,$q$Incorrecta: asistencia no basta como evidencia de competencia.$q$))
)
insert into public.quiz_questions (
  external_id, test_id, test_title, category, block_id, block_range, topic, situation,
  question_number, prompt, options, correct_answer, explanation, option_feedback, sequence, active
)
select
  new_questions.external_id,
  new_questions.test_id,
  new_questions.test_title,
  'especificos',
  new_questions.block_id,
  new_questions.block_range,
  new_questions.topic,
  new_questions.situation,
  new_questions.question_number,
  new_questions.prompt,
  new_questions.options,
  new_questions.correct_answer,
  new_questions.explanation,
  new_questions.option_feedback,
  base_sequence.value + new_questions.position,
  true
from new_questions
cross join base_sequence
on conflict (external_id) do update set
  test_id = excluded.test_id,
  test_title = excluded.test_title,
  category = excluded.category,
  block_id = excluded.block_id,
  block_range = excluded.block_range,
  topic = excluded.topic,
  situation = excluded.situation,
  question_number = excluded.question_number,
  prompt = excluded.prompt,
  options = excluded.options,
  correct_answer = excluded.correct_answer,
  explanation = excluded.explanation,
  option_feedback = excluded.option_feedback,
  sequence = excluded.sequence,
  active = true;

update public.quiz_questions
set
  options = jsonb_build_array(options ->> 1, options ->> 0, options ->> 2),
  option_feedback = jsonb_build_array(option_feedback ->> 1, option_feedback ->> 0, option_feedback ->> 2),
  correct_answer = 1
where external_id in (
  'gen-chem-27', 'gen-chem-30', 'gen-chem-33', 'gen-chem-36', 'gen-chem-39', 'gen-chem-42', 'gen-chem-45',
  'gen-nat-27', 'gen-nat-30', 'gen-nat-33', 'gen-nat-36', 'gen-nat-39', 'gen-nat-42', 'gen-nat-45'
);

update public.quiz_questions
set
  options = jsonb_build_array(options ->> 1, options ->> 2, options ->> 0),
  option_feedback = jsonb_build_array(option_feedback ->> 1, option_feedback ->> 2, option_feedback ->> 0),
  correct_answer = 2
where external_id in (
  'gen-chem-28', 'gen-chem-31', 'gen-chem-34', 'gen-chem-37', 'gen-chem-40', 'gen-chem-43', 'gen-chem-46',
  'gen-nat-28', 'gen-nat-31', 'gen-nat-34', 'gen-nat-37', 'gen-nat-40', 'gen-nat-43', 'gen-nat-46'
);
