update public.quiz_questions
set active = false
where active = true
  and (
    (category = 'razonamiento' and topic in ('Lectura critica', 'Razonamiento cuantitativo', 'Razonamiento cuantitativo y lectura critica'))
    or (category = 'pedagogica' and topic = 'Competencias comportamentales docentes')
  );

with base_sequence as (
  select coalesce(max(sequence), 0) + 1000 as value
  from public.quiz_questions
),
new_questions (
  position, external_id, test_id, test_title, category, block_id, block_range, topic, situation,
  question_number, prompt, options, correct_answer, explanation, option_feedback
) as (
  values
  (1, 'lect-crit-01', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-01', '1-5', 'Lectura critica',
   $q$Situacion 1. La rectoria de una institucion educativa envia a las familias una circular sobre el uso de celulares. El texto afirma que los dispositivos no seran prohibidos de manera absoluta, pero que su uso quedara limitado a actividades pedagogicas planeadas, momentos de emergencia y autorizaciones expresas. Tambien explica que la medida busca proteger la concentracion, evitar grabaciones no consentidas y promover acuerdos de convivencia. Algunas familias interpretan la circular como una prohibicion total y otras como una autorizacion libre siempre que el estudiante tenga buen comportamiento.$q$,
   1, $q$La idea central de la circular es:$q$,
   jsonb_build_array($q$regular el uso de celulares mediante criterios pedagogicos y de convivencia.$q$, $q$prohibir todo dispositivo movil dentro de la institucion sin excepciones.$q$, $q$permitir que cada estudiante decida como usar su celular si no afecta sus notas.$q$),
   0, $q$El texto no elimina el uso de celulares, sino que lo condiciona a finalidades pedagogicas, seguridad y convivencia.$q$,
   jsonb_build_array($q$Correcta: sintetiza el proposito regulador del texto.$q$, $q$Incorrecta: contradice las excepciones mencionadas.$q$, $q$Incorrecta: omite los limites institucionales.$q$)),
  (2, 'lect-crit-02', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-01', '1-5', 'Lectura critica',
   $q$Situacion 1. La rectoria de una institucion educativa envia a las familias una circular sobre el uso de celulares. El texto afirma que los dispositivos no seran prohibidos de manera absoluta, pero que su uso quedara limitado a actividades pedagogicas planeadas, momentos de emergencia y autorizaciones expresas. Tambien explica que la medida busca proteger la concentracion, evitar grabaciones no consentidas y promover acuerdos de convivencia. Algunas familias interpretan la circular como una prohibicion total y otras como una autorizacion libre siempre que el estudiante tenga buen comportamiento.$q$,
   2, $q$La interpretacion de las familias que hablan de prohibicion total es inadecuada porque:$q$,
   jsonb_build_array($q$el texto reconoce usos permitidos bajo condiciones definidas.$q$, $q$la circular no menciona el aprendizaje ni la convivencia escolar.$q$, $q$la rectoria delega toda decision en los estudiantes.$q$),
   0, $q$La circular establece restricciones, pero conserva usos autorizados en situaciones especificas.$q$,
   jsonb_build_array($q$Correcta: identifica una excepcion explicita.$q$, $q$Incorrecta: esos aspectos si aparecen como justificacion.$q$, $q$Incorrecta: la decision queda regulada por la institucion.$q$)),
  (3, 'lect-crit-03', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-01', '1-5', 'Lectura critica',
   $q$Situacion 1. La rectoria de una institucion educativa envia a las familias una circular sobre el uso de celulares. El texto afirma que los dispositivos no seran prohibidos de manera absoluta, pero que su uso quedara limitado a actividades pedagogicas planeadas, momentos de emergencia y autorizaciones expresas. Tambien explica que la medida busca proteger la concentracion, evitar grabaciones no consentidas y promover acuerdos de convivencia. Algunas familias interpretan la circular como una prohibicion total y otras como una autorizacion libre siempre que el estudiante tenga buen comportamiento.$q$,
   3, $q$Segun la circular, una condicion necesaria para usar celulares en clase es que:$q$,
   jsonb_build_array($q$el uso haga parte de una actividad pedagogica planeada o autorizada.$q$, $q$la familia envie una autorizacion general al inicio del ano.$q$, $q$el estudiante tenga un promedio alto en todas las areas.$q$),
   0, $q$El permiso depende del sentido pedagogico o de una autorizacion concreta, no del rendimiento general.$q$,
   jsonb_build_array($q$Correcta: corresponde a una condicion del texto.$q$, $q$Incorrecta: el texto no habla de autorizacion general permanente.$q$, $q$Incorrecta: el promedio no aparece como criterio.$q$)),
  (4, 'lect-crit-04', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-01', '1-5', 'Lectura critica',
   $q$Situacion 1. La rectoria de una institucion educativa envia a las familias una circular sobre el uso de celulares. El texto afirma que los dispositivos no seran prohibidos de manera absoluta, pero que su uso quedara limitado a actividades pedagogicas planeadas, momentos de emergencia y autorizaciones expresas. Tambien explica que la medida busca proteger la concentracion, evitar grabaciones no consentidas y promover acuerdos de convivencia. Algunas familias interpretan la circular como una prohibicion total y otras como una autorizacion libre siempre que el estudiante tenga buen comportamiento.$q$,
   4, $q$La expresion "no seran prohibidos de manera absoluta" permite inferir que:$q$,
   jsonb_build_array($q$habra restricciones, pero tambien escenarios de uso permitido.$q$, $q$la institucion renuncia a regular los dispositivos.$q$, $q$los celulares se consideran indispensables en todas las clases.$q$),
   0, $q$La frase niega una prohibicion total y abre la posibilidad de excepciones reguladas.$q$,
   jsonb_build_array($q$Correcta: interpreta el matiz de la expresion.$q$, $q$Incorrecta: si existe regulacion.$q$, $q$Incorrecta: no se afirma obligatoriedad permanente.$q$)),
  (5, 'lect-crit-05', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-01', '1-5', 'Lectura critica',
   $q$Situacion 1. La rectoria de una institucion educativa envia a las familias una circular sobre el uso de celulares. El texto afirma que los dispositivos no seran prohibidos de manera absoluta, pero que su uso quedara limitado a actividades pedagogicas planeadas, momentos de emergencia y autorizaciones expresas. Tambien explica que la medida busca proteger la concentracion, evitar grabaciones no consentidas y promover acuerdos de convivencia. Algunas familias interpretan la circular como una prohibicion total y otras como una autorizacion libre siempre que el estudiante tenga buen comportamiento.$q$,
   5, $q$La mejor respuesta institucional ante las interpretaciones opuestas de las familias seria:$q$,
   jsonb_build_array($q$aclarar con ejemplos concretos los usos permitidos, restringidos y excepcionales.$q$, $q$retirar la circular para evitar nuevas discusiones.$q$, $q$aplicar sanciones a las familias que no comprendieron el mensaje.$q$),
   0, $q$La dificultad es de comprension y comunicacion; aclarar criterios reduce ambiguedades.$q$,
   jsonb_build_array($q$Correcta: responde al problema de interpretacion.$q$, $q$Incorrecta: elimina la orientacion sin resolver el desacuerdo.$q$, $q$Incorrecta: castiga una duda comunicativa.$q$)),

  (6, 'lect-crit-06', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-02', '6-10', 'Lectura critica',
   $q$Situacion 2. Un periodico local publica una nota titulada "La lectura mejora cuando la escuela escucha a sus estudiantes". La noticia describe un proyecto en el que varios cursos eligieron textos cercanos a sus intereses, discutieron noticias del municipio y escribieron resenas breves. El articulo afirma que los resultados mejoraron porque los estudiantes "por fin leyeron lo que querian". Sin embargo, en el desarrollo de la nota se reconoce que tambien hubo acompanamiento docente, criterios de evaluacion claros y reuniones con las familias.$q$,
   6, $q$La explicacion del titulo resulta incompleta porque:$q$,
   jsonb_build_array($q$atribuye la mejora solo al interes estudiantil e ignora otros apoyos descritos.$q$, $q$niega que los estudiantes puedan elegir textos en la escuela.$q$, $q$sostiene que las familias reemplazaron el trabajo docente.$q$),
   0, $q$El cuerpo del texto presenta varios factores, no una sola causa.$q$,
   jsonb_build_array($q$Correcta: contrasta titulo y desarrollo.$q$, $q$Incorrecta: la eleccion si aparece en la nota.$q$, $q$Incorrecta: las familias acompanaron, no sustituyeron.$q$)),
  (7, 'lect-crit-07', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-02', '6-10', 'Lectura critica',
   $q$Situacion 2. Un periodico local publica una nota titulada "La lectura mejora cuando la escuela escucha a sus estudiantes". La noticia describe un proyecto en el que varios cursos eligieron textos cercanos a sus intereses, discutieron noticias del municipio y escribieron resenas breves. El articulo afirma que los resultados mejoraron porque los estudiantes "por fin leyeron lo que querian". Sin embargo, en el desarrollo de la nota se reconoce que tambien hubo acompanamiento docente, criterios de evaluacion claros y reuniones con las familias.$q$,
   7, $q$Una conclusion prudente a partir de la noticia seria que:$q$,
   jsonb_build_array($q$la participacion estudiantil pudo favorecer la lectura junto con otras acciones pedagogicas.$q$, $q$la seleccion libre de textos garantiza por si sola mejores desempenos.$q$, $q$los criterios de evaluacion impiden que la lectura resulte significativa.$q$),
   0, $q$La noticia permite inferir una relacion entre varias estrategias y los resultados, no una garantia unica.$q$,
   jsonb_build_array($q$Correcta: reconoce alcance y limites de la informacion.$q$, $q$Incorrecta: absolutiza una causa.$q$, $q$Incorrecta: contradice el papel positivo de criterios claros.$q$)),
  (8, 'lect-crit-08', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-02', '6-10', 'Lectura critica',
   $q$Situacion 2. Un periodico local publica una nota titulada "La lectura mejora cuando la escuela escucha a sus estudiantes". La noticia describe un proyecto en el que varios cursos eligieron textos cercanos a sus intereses, discutieron noticias del municipio y escribieron resenas breves. El articulo afirma que los resultados mejoraron porque los estudiantes "por fin leyeron lo que querian". Sin embargo, en el desarrollo de la nota se reconoce que tambien hubo acompanamiento docente, criterios de evaluacion claros y reuniones con las familias.$q$,
   8, $q$La expresion "por fin leyeron lo que querian" cumple principalmente la funcion de:$q$,
   jsonb_build_array($q$resaltar de forma enfatica el papel de los intereses estudiantiles.$q$, $q$presentar un dato estadistico verificable sobre habitos de lectura.$q$, $q$demostrar que antes ningun estudiante leia textos escolares.$q$),
   0, $q$La expresion enfatiza una interpretacion del periodista, no un dato cuantitativo completo.$q$,
   jsonb_build_array($q$Correcta: identifica el tono valorativo.$q$, $q$Incorrecta: no contiene cifras ni metodologia.$q$, $q$Incorrecta: generaliza sin evidencia.$q$)),
  (9, 'lect-crit-09', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-02', '6-10', 'Lectura critica',
   $q$Situacion 2. Un periodico local publica una nota titulada "La lectura mejora cuando la escuela escucha a sus estudiantes". La noticia describe un proyecto en el que varios cursos eligieron textos cercanos a sus intereses, discutieron noticias del municipio y escribieron resenas breves. El articulo afirma que los resultados mejoraron porque los estudiantes "por fin leyeron lo que querian". Sin embargo, en el desarrollo de la nota se reconoce que tambien hubo acompanamiento docente, criterios de evaluacion claros y reuniones con las familias.$q$,
   9, $q$Si un lector quiere evaluar la solidez de la noticia, deberia pedir principalmente:$q$,
   jsonb_build_array($q$datos comparables sobre desempeno antes y despues del proyecto.$q$, $q$mas opiniones anonimas que repitan el titulo.$q$, $q$una lista de textos favoritos sin informacion de resultados.$q$),
   0, $q$La validez de la afirmacion mejora si se aportan evidencias comparables.$q$,
   jsonb_build_array($q$Correcta: solicita evidencia pertinente.$q$, $q$Incorrecta: repetir opiniones no fortalece la prueba.$q$, $q$Incorrecta: los gustos no bastan para medir mejora.$q$)),
  (10, 'lect-crit-10', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-02', '6-10', 'Lectura critica',
   $q$Situacion 2. Un periodico local publica una nota titulada "La lectura mejora cuando la escuela escucha a sus estudiantes". La noticia describe un proyecto en el que varios cursos eligieron textos cercanos a sus intereses, discutieron noticias del municipio y escribieron resenas breves. El articulo afirma que los resultados mejoraron porque los estudiantes "por fin leyeron lo que querian". Sin embargo, en el desarrollo de la nota se reconoce que tambien hubo acompanamiento docente, criterios de evaluacion claros y reuniones con las familias.$q$,
   10, $q$La relacion entre el titulo y el desarrollo de la nota puede describirse como:$q$,
   jsonb_build_array($q$un titulo atractivo que simplifica una explicacion mas amplia.$q$, $q$una contradiccion total entre dos textos sin ningun punto comun.$q$, $q$una demostracion tecnica basada solo en estadisticas oficiales.$q$),
   0, $q$El titulo no es falso, pero reduce una explicacion multifactorial.$q$,
   jsonb_build_array($q$Correcta: reconoce la simplificacion.$q$, $q$Incorrecta: hay relacion entre titulo y contenido.$q$, $q$Incorrecta: la nota no se basa solo en cifras oficiales.$q$)),

  (11, 'lect-crit-11', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-03', '11-15', 'Lectura critica',
   $q$Situacion 3. En una reunion academica, una docente presenta una columna de opinion que critica la evaluacion estandarizada. El autor sostiene que las pruebas reducen la educacion a numeros, aunque reconoce que pueden ofrecer informacion util si se interpretan con cuidado. Luego propone complementar los resultados con observaciones de aula, analisis de producciones estudiantiles y dialogo con la comunidad. El texto no pide eliminar toda evaluacion, sino evitar que un solo indicador defina la calidad educativa.$q$,
   11, $q$La tesis principal de la columna es que:$q$,
   jsonb_build_array($q$las pruebas deben interpretarse con otros elementos y no como unico criterio de calidad.$q$, $q$toda evaluacion numerica debe eliminarse de las instituciones educativas.$q$, $q$la calidad escolar depende exclusivamente de las opiniones de la comunidad.$q$),
   0, $q$El autor critica el uso unico de las pruebas, no toda forma de evaluacion.$q$,
   jsonb_build_array($q$Correcta: recoge la postura equilibrada del texto.$q$, $q$Incorrecta: exagera la posicion del autor.$q$, $q$Incorrecta: reemplaza un criterio unico por otro.$q$)),
  (12, 'lect-crit-12', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-03', '11-15', 'Lectura critica',
   $q$Situacion 3. En una reunion academica, una docente presenta una columna de opinion que critica la evaluacion estandarizada. El autor sostiene que las pruebas reducen la educacion a numeros, aunque reconoce que pueden ofrecer informacion util si se interpretan con cuidado. Luego propone complementar los resultados con observaciones de aula, analisis de producciones estudiantiles y dialogo con la comunidad. El texto no pide eliminar toda evaluacion, sino evitar que un solo indicador defina la calidad educativa.$q$,
   12, $q$La concesion del autor aparece cuando:$q$,
   jsonb_build_array($q$acepta que las pruebas pueden aportar informacion si se interpretan cuidadosamente.$q$, $q$afirma que las pruebas siempre destruyen el sentido de la educacion.$q$, $q$propone que las familias califiquen directamente a los docentes.$q$),
   0, $q$Una concesion reconoce parcialmente la validez de una idea contraria o matizada.$q$,
   jsonb_build_array($q$Correcta: identifica el matiz argumentativo.$q$, $q$Incorrecta: es una critica, no una concesion.$q$, $q$Incorrecta: no corresponde al planteamiento del texto.$q$)),
  (13, 'lect-crit-13', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-03', '11-15', 'Lectura critica',
   $q$Situacion 3. En una reunion academica, una docente presenta una columna de opinion que critica la evaluacion estandarizada. El autor sostiene que las pruebas reducen la educacion a numeros, aunque reconoce que pueden ofrecer informacion util si se interpretan con cuidado. Luego propone complementar los resultados con observaciones de aula, analisis de producciones estudiantiles y dialogo con la comunidad. El texto no pide eliminar toda evaluacion, sino evitar que un solo indicador defina la calidad educativa.$q$,
   13, $q$La propuesta de complementar resultados busca principalmente:$q$,
   jsonb_build_array($q$ampliar la comprension del aprendizaje y del contexto escolar.$q$, $q$ocultar los resultados bajos para proteger la imagen institucional.$q$, $q$evitar que los docentes rindan cuentas sobre su trabajo.$q$),
   0, $q$El complemento permite interpretar mejor las evidencias y no ocultarlas.$q$,
   jsonb_build_array($q$Correcta: coincide con el sentido de la propuesta.$q$, $q$Incorrecta: el texto no plantea ocultamiento.$q$, $q$Incorrecta: complementar no equivale a evitar responsabilidad.$q$)),
  (14, 'lect-crit-14', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-03', '11-15', 'Lectura critica',
   $q$Situacion 3. En una reunion academica, una docente presenta una columna de opinion que critica la evaluacion estandarizada. El autor sostiene que las pruebas reducen la educacion a numeros, aunque reconoce que pueden ofrecer informacion util si se interpretan con cuidado. Luego propone complementar los resultados con observaciones de aula, analisis de producciones estudiantiles y dialogo con la comunidad. El texto no pide eliminar toda evaluacion, sino evitar que un solo indicador defina la calidad educativa.$q$,
   14, $q$Un uso contrario a la postura del autor seria:$q$,
   jsonb_build_array($q$ordenar escuelas solo por puntaje y tomar decisiones sin analizar contexto.$q$, $q$cruzar resultados de pruebas con observaciones de aula.$q$, $q$leer los puntajes junto con producciones de los estudiantes.$q$),
   0, $q$El autor rechaza que un unico indicador defina la calidad educativa.$q$,
   jsonb_build_array($q$Correcta: representa el uso que el texto critica.$q$, $q$Incorrecta: coincide con la propuesta de complementar.$q$, $q$Incorrecta: tambien integra evidencias.$q$)),
  (15, 'lect-crit-15', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-03', '11-15', 'Lectura critica',
   $q$Situacion 3. En una reunion academica, una docente presenta una columna de opinion que critica la evaluacion estandarizada. El autor sostiene que las pruebas reducen la educacion a numeros, aunque reconoce que pueden ofrecer informacion util si se interpretan con cuidado. Luego propone complementar los resultados con observaciones de aula, analisis de producciones estudiantiles y dialogo con la comunidad. El texto no pide eliminar toda evaluacion, sino evitar que un solo indicador defina la calidad educativa.$q$,
   15, $q$La frase "reducen la educacion a numeros" expresa:$q$,
   jsonb_build_array($q$una critica a interpretar la calidad educativa de forma estrecha.$q$, $q$una descripcion neutral de todos los instrumentos de medicion.$q$, $q$una defensa del calculo como unico metodo pedagogico.$q$),
   0, $q$La frase tiene carga valorativa y cuestiona una mirada limitada.$q$,
   jsonb_build_array($q$Correcta: reconoce el sentido critico de la expresion.$q$, $q$Incorrecta: no es neutral.$q$, $q$Incorrecta: plantea lo contrario de la tesis.$q$)),

  (16, 'lect-crit-16', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-04', '16-20', 'Lectura critica',
   $q$Situacion 4. El consejo academico recibe dos informes sobre convivencia. El primero enumera sanciones aplicadas y concluye que la convivencia mejoro porque hubo menos reportes disciplinarios. El segundo advierte que los reportes bajaron, pero tambien disminuyeron las denuncias de estudiantes por desconfianza en el proceso. Propone revisar canales de escucha, tiempos de respuesta y acciones restaurativas. Ambos informes usan datos, pero llegan a conclusiones distintas sobre el mismo fenomeno escolar.$q$,
   16, $q$La diferencia principal entre los informes consiste en que:$q$,
   jsonb_build_array($q$el segundo problematiza el significado de la disminucion de reportes.$q$, $q$el primero incluye voces estudiantiles y el segundo solo sanciones.$q$, $q$ambos niegan la necesidad de analizar datos institucionales.$q$),
   0, $q$El segundo no toma la baja de reportes como mejora automatica; revisa su posible causa.$q$,
   jsonb_build_array($q$Correcta: compara el razonamiento de ambos textos.$q$, $q$Incorrecta: invierte la informacion presentada.$q$, $q$Incorrecta: ambos usan datos.$q$)),
  (17, 'lect-crit-17', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-04', '16-20', 'Lectura critica',
   $q$Situacion 4. El consejo academico recibe dos informes sobre convivencia. El primero enumera sanciones aplicadas y concluye que la convivencia mejoro porque hubo menos reportes disciplinarios. El segundo advierte que los reportes bajaron, pero tambien disminuyeron las denuncias de estudiantes por desconfianza en el proceso. Propone revisar canales de escucha, tiempos de respuesta y acciones restaurativas. Ambos informes usan datos, pero llegan a conclusiones distintas sobre el mismo fenomeno escolar.$q$,
   17, $q$La conclusion del primer informe es debil porque:$q$,
   jsonb_build_array($q$confunde menor numero de reportes con mejora sin examinar otras causas.$q$, $q$presenta demasiadas fuentes cualitativas y cuantitativas.$q$, $q$rechaza por completo el uso de sanciones institucionales.$q$),
   0, $q$La disminucion puede deberse a desconfianza, no necesariamente a mejora de convivencia.$q$,
   jsonb_build_array($q$Correcta: identifica una inferencia insuficiente.$q$, $q$Incorrecta: el informe es limitado, no excesivo.$q$, $q$Incorrecta: enumera sanciones, no las rechaza.$q$)),
  (18, 'lect-crit-18', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-04', '16-20', 'Lectura critica',
   $q$Situacion 4. El consejo academico recibe dos informes sobre convivencia. El primero enumera sanciones aplicadas y concluye que la convivencia mejoro porque hubo menos reportes disciplinarios. El segundo advierte que los reportes bajaron, pero tambien disminuyeron las denuncias de estudiantes por desconfianza en el proceso. Propone revisar canales de escucha, tiempos de respuesta y acciones restaurativas. Ambos informes usan datos, pero llegan a conclusiones distintas sobre el mismo fenomeno escolar.$q$,
   18, $q$Una pregunta critica pertinente para evaluar ambos informes seria:$q$,
   jsonb_build_array($q$que razones explican la variacion en reportes y denuncias estudiantiles.$q$, $q$que informe tiene mas paginas y mejor presentacion grafica.$q$, $q$que sancion resulta mas visible para publicar en redes.$q$),
   0, $q$La pregunta examina la relacion entre datos y causas posibles.$q$,
   jsonb_build_array($q$Correcta: ayuda a valorar la validez de las conclusiones.$q$, $q$Incorrecta: la extension no prueba solidez.$q$, $q$Incorrecta: la visibilidad no evalua convivencia.$q$)),
  (19, 'lect-crit-19', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-04', '16-20', 'Lectura critica',
   $q$Situacion 4. El consejo academico recibe dos informes sobre convivencia. El primero enumera sanciones aplicadas y concluye que la convivencia mejoro porque hubo menos reportes disciplinarios. El segundo advierte que los reportes bajaron, pero tambien disminuyeron las denuncias de estudiantes por desconfianza en el proceso. Propone revisar canales de escucha, tiempos de respuesta y acciones restaurativas. Ambos informes usan datos, pero llegan a conclusiones distintas sobre el mismo fenomeno escolar.$q$,
   19, $q$El segundo informe usa la informacion de manera mas cuidadosa porque:$q$,
   jsonb_build_array($q$considera explicaciones alternativas antes de concluir que hubo mejora.$q$, $q$elimina todos los datos numericos para concentrarse en percepciones.$q$, $q$afirma que toda sancion demuestra fracaso institucional.$q$),
   0, $q$El analisis critico exige valorar diferentes explicaciones posibles.$q$,
   jsonb_build_array($q$Correcta: muestra lectura inferencial de los datos.$q$, $q$Incorrecta: el informe tambien usa datos.$q$, $q$Incorrecta: no absolutiza las sanciones.$q$)),
  (20, 'lect-crit-20', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-04', '16-20', 'Lectura critica',
   $q$Situacion 4. El consejo academico recibe dos informes sobre convivencia. El primero enumera sanciones aplicadas y concluye que la convivencia mejoro porque hubo menos reportes disciplinarios. El segundo advierte que los reportes bajaron, pero tambien disminuyeron las denuncias de estudiantes por desconfianza en el proceso. Propone revisar canales de escucha, tiempos de respuesta y acciones restaurativas. Ambos informes usan datos, pero llegan a conclusiones distintas sobre el mismo fenomeno escolar.$q$,
   20, $q$La expresion "ambos informes usan datos" sugiere que:$q$,
   jsonb_build_array($q$tener datos no garantiza una interpretacion adecuada de ellos.$q$, $q$los datos siempre conducen a una unica conclusion correcta.$q$, $q$las conclusiones no dependen de la forma de interpretar la informacion.$q$),
   0, $q$El caso muestra que los mismos fenomenos pueden leerse con niveles distintos de rigor.$q$,
   jsonb_build_array($q$Correcta: identifica la leccion critica del texto.$q$, $q$Incorrecta: hay conclusiones distintas.$q$, $q$Incorrecta: la interpretacion es decisiva.$q$)),

  (21, 'lect-crit-21', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-05', '21-25', 'Lectura critica',
   $q$Situacion 5. Una guia docente afirma que la inclusion no consiste en bajar expectativas, sino en identificar barreras y ofrecer apoyos razonables para que todos los estudiantes participen y aprendan. El texto diferencia entre flexibilizar medios y renunciar a los propositos formativos. Tambien advierte que separar permanentemente a un estudiante puede parecer una ayuda, pero limitar sus oportunidades de interaccion y aprendizaje compartido.$q$,
   21, $q$Segun la guia, inclusion significa principalmente:$q$,
   jsonb_build_array($q$mantener propositos formativos y ajustar medios para superar barreras.$q$, $q$reducir los aprendizajes esperados para evitar exigencias.$q$, $q$separar a quienes requieren apoyo para que trabajen sin incomodar al grupo.$q$),
   0, $q$El texto distingue ajustes de medios y conservacion de propositos formativos.$q$,
   jsonb_build_array($q$Correcta: recoge la definicion del texto.$q$, $q$Incorrecta: confunde inclusion con baja expectativa.$q$, $q$Incorrecta: la separacion permanente es cuestionada.$q$)),
  (22, 'lect-crit-22', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-05', '21-25', 'Lectura critica',
   $q$Situacion 5. Una guia docente afirma que la inclusion no consiste en bajar expectativas, sino en identificar barreras y ofrecer apoyos razonables para que todos los estudiantes participen y aprendan. El texto diferencia entre flexibilizar medios y renunciar a los propositos formativos. Tambien advierte que separar permanentemente a un estudiante puede parecer una ayuda, pero limitar sus oportunidades de interaccion y aprendizaje compartido.$q$,
   22, $q$La oposicion entre "flexibilizar medios" y "renunciar a propositos" sirve para:$q$,
   jsonb_build_array($q$aclarar que adaptar la ensenanza no equivale a disminuir el aprendizaje esperado.$q$, $q$demostrar que todos los estudiantes deben hacer exactamente lo mismo.$q$, $q$justificar que algunos estudiantes no sean evaluados.$q$),
   0, $q$La guia defiende ajustes sin abandonar los fines formativos.$q$,
   jsonb_build_array($q$Correcta: interpreta la distincion clave.$q$, $q$Incorrecta: adaptar medios implica no hacer todo identico.$q$, $q$Incorrecta: no se elimina la evaluacion.$q$)),
  (23, 'lect-crit-23', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-05', '21-25', 'Lectura critica',
   $q$Situacion 5. Una guia docente afirma que la inclusion no consiste en bajar expectativas, sino en identificar barreras y ofrecer apoyos razonables para que todos los estudiantes participen y aprendan. El texto diferencia entre flexibilizar medios y renunciar a los propositos formativos. Tambien advierte que separar permanentemente a un estudiante puede parecer una ayuda, pero limitar sus oportunidades de interaccion y aprendizaje compartido.$q$,
   23, $q$La advertencia sobre separar permanentemente a un estudiante indica que una medida puede ser problematica cuando:$q$,
   jsonb_build_array($q$aunque parezca protectora, reduce participacion e interaccion.$q$, $q$permite que el estudiante reciba apoyos razonables en el aula.$q$, $q$mantiene los mismos propositos con medios diferentes.$q$),
   0, $q$La guia advierte sobre apoyos que terminan limitando oportunidades.$q$,
   jsonb_build_array($q$Correcta: identifica el riesgo señalado.$q$, $q$Incorrecta: eso corresponde a una practica inclusiva.$q$, $q$Incorrecta: esa es la distincion defendida por el texto.$q$)),
  (24, 'lect-crit-24', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-05', '21-25', 'Lectura critica',
   $q$Situacion 5. Una guia docente afirma que la inclusion no consiste en bajar expectativas, sino en identificar barreras y ofrecer apoyos razonables para que todos los estudiantes participen y aprendan. El texto diferencia entre flexibilizar medios y renunciar a los propositos formativos. Tambien advierte que separar permanentemente a un estudiante puede parecer una ayuda, pero limitar sus oportunidades de interaccion y aprendizaje compartido.$q$,
   24, $q$Una practica coherente con la guia seria:$q$,
   jsonb_build_array($q$ofrecer apoyos visuales y tiempo adicional sin excluir al estudiante del proyecto comun.$q$, $q$asignar actividades sin relacion con los objetivos para que no se frustre.$q$, $q$eximirlo de participar en actividades grupales durante todo el periodo.$q$),
   0, $q$La practica mantiene participacion y ajusta condiciones de acceso.$q$,
   jsonb_build_array($q$Correcta: aplica el enfoque de apoyos razonables.$q$, $q$Incorrecta: renuncia al proposito formativo.$q$, $q$Incorrecta: limita interaccion de forma permanente.$q$)),
  (25, 'lect-crit-25', 'lectura-critica-01', 'Simulacro #1 - Lectura critica', 'razonamiento', 'lectura-contexto-05', '21-25', 'Lectura critica',
   $q$Situacion 5. Una guia docente afirma que la inclusion no consiste en bajar expectativas, sino en identificar barreras y ofrecer apoyos razonables para que todos los estudiantes participen y aprendan. El texto diferencia entre flexibilizar medios y renunciar a los propositos formativos. Tambien advierte que separar permanentemente a un estudiante puede parecer una ayuda, pero limitar sus oportunidades de interaccion y aprendizaje compartido.$q$,
   25, $q$El tono del texto es principalmente:$q$,
   jsonb_build_array($q$orientador, porque precisa criterios para tomar decisiones inclusivas.$q$, $q$sancionatorio, porque enumera castigos para docentes y familias.$q$, $q$narrativo, porque relata una historia con personajes y desenlace.$q$),
   0, $q$La guia define conceptos, diferencia practicas y orienta decisiones.$q$,
   jsonb_build_array($q$Correcta: reconoce la intencion orientadora.$q$, $q$Incorrecta: no lista sanciones.$q$, $q$Incorrecta: no desarrolla una narracion.$q$)),

  (26, 'raz-cuant-01', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-01', '1-5', 'Razonamiento cuantitativo',
   $q$Situacion 1. La coordinacion revisa asistencia a un refuerzo de lectura. En grado sexto A hay 30 estudiantes y asistieron 24; en sexto B hay 25 estudiantes y asistieron 21; en sexto C hay 20 estudiantes y asistieron 15. El equipo debe comparar porcentajes y no solo cantidades absolutas para decidir donde reforzar la convocatoria.$q$,
   1, $q$El grupo con mayor porcentaje de asistencia fue:$q$,
   jsonb_build_array($q$Sexto B, porque 21 de 25 equivale al 84%.$q$, $q$Sexto A, porque 24 asistentes es la cantidad mas alta.$q$, $q$Sexto C, porque 15 asistentes representa tres cuartas partes.$q$),
   0, $q$Sexto A alcanza 80%, sexto B 84% y sexto C 75%; por tanto, el mayor porcentaje es sexto B.$q$,
   jsonb_build_array($q$Correcta: compara proporciones.$q$, $q$Incorrecta: confunde cantidad absoluta con porcentaje.$q$, $q$Incorrecta: 75% no es el mayor porcentaje.$q$)),
  (27, 'raz-cuant-02', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-01', '1-5', 'Razonamiento cuantitativo',
   $q$Situacion 1. La coordinacion revisa asistencia a un refuerzo de lectura. En grado sexto A hay 30 estudiantes y asistieron 24; en sexto B hay 25 estudiantes y asistieron 21; en sexto C hay 20 estudiantes y asistieron 15. El equipo debe comparar porcentajes y no solo cantidades absolutas para decidir donde reforzar la convocatoria.$q$,
   2, $q$El porcentaje de inasistencia de sexto C fue:$q$,
   jsonb_build_array($q$25%.$q$, $q$15%.$q$, $q$75%.$q$),
   0, $q$Faltaron 5 de 20 estudiantes; 5/20 equivale a 25%.$q$,
   jsonb_build_array($q$Correcta: calcula la parte que no asistio.$q$, $q$Incorrecta: 15 es la cantidad que asistio, no porcentaje de inasistencia.$q$, $q$Incorrecta: 75% corresponde a asistencia.$q$)),
  (28, 'raz-cuant-03', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-01', '1-5', 'Razonamiento cuantitativo',
   $q$Situacion 1. La coordinacion revisa asistencia a un refuerzo de lectura. En grado sexto A hay 30 estudiantes y asistieron 24; en sexto B hay 25 estudiantes y asistieron 21; en sexto C hay 20 estudiantes y asistieron 15. El equipo debe comparar porcentajes y no solo cantidades absolutas para decidir donde reforzar la convocatoria.$q$,
   3, $q$Si se quiere priorizar el grupo con menor asistencia proporcional, se debe iniciar por:$q$,
   jsonb_build_array($q$Sexto C, porque tuvo 75% de asistencia.$q$, $q$Sexto A, porque tuvo 24 asistentes.$q$, $q$Sexto B, porque tuvo 4 estudiantes ausentes.$q$),
   0, $q$El menor porcentaje de asistencia es 75%, correspondiente a sexto C.$q$,
   jsonb_build_array($q$Correcta: selecciona por proporcion, no por cantidad.$q$, $q$Incorrecta: sexto A tuvo 80%.$q$, $q$Incorrecta: sexto B tuvo la mayor asistencia proporcional.$q$)),
  (29, 'raz-cuant-04', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-01', '1-5', 'Razonamiento cuantitativo',
   $q$Situacion 1. La coordinacion revisa asistencia a un refuerzo de lectura. En grado sexto A hay 30 estudiantes y asistieron 24; en sexto B hay 25 estudiantes y asistieron 21; en sexto C hay 20 estudiantes y asistieron 15. El equipo debe comparar porcentajes y no solo cantidades absolutas para decidir donde reforzar la convocatoria.$q$,
   4, $q$La asistencia total de los tres grupos fue:$q$,
   jsonb_build_array($q$60 estudiantes.$q$, $q$75 estudiantes.$q$, $q$15 estudiantes.$q$),
   0, $q$24 + 21 + 15 = 60 estudiantes asistentes.$q$,
   jsonb_build_array($q$Correcta: suma las asistencias.$q$, $q$Incorrecta: 75 es la matricula total.$q$, $q$Incorrecta: 15 corresponde solo a sexto C.$q$)),
  (30, 'raz-cuant-05', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-01', '1-5', 'Razonamiento cuantitativo',
   $q$Situacion 1. La coordinacion revisa asistencia a un refuerzo de lectura. En grado sexto A hay 30 estudiantes y asistieron 24; en sexto B hay 25 estudiantes y asistieron 21; en sexto C hay 20 estudiantes y asistieron 15. El equipo debe comparar porcentajes y no solo cantidades absolutas para decidir donde reforzar la convocatoria.$q$,
   5, $q$Si la meta minima era 80% de asistencia, el grupo que no cumplio fue:$q$,
   jsonb_build_array($q$Sexto C.$q$, $q$Sexto A.$q$, $q$Sexto B.$q$),
   0, $q$Sexto C obtuvo 75%, por debajo de la meta; sexto A alcanzo 80% y sexto B 84%.$q$,
   jsonb_build_array($q$Correcta: compara cada porcentaje con la meta.$q$, $q$Incorrecta: sexto A cumple exactamente la meta.$q$, $q$Incorrecta: sexto B supera la meta.$q$)),

  (31, 'raz-cuant-06', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-02', '6-10', 'Razonamiento cuantitativo',
   $q$Situacion 2. Una sede rural organiza transporte para estudiantes. Un bus tiene 40 cupos y realiza dos recorridos diarios. El lunes viajaron 34 estudiantes en el primer recorrido y 28 en el segundo. El martes viajaron 36 en el primero y 32 en el segundo. La rectoria quiere calcular ocupacion, cupos disponibles y variaciones para planear rutas.$q$,
   6, $q$La ocupacion del primer recorrido del lunes fue:$q$,
   jsonb_build_array($q$85%.$q$, $q$34%.$q$, $q$40%.$q$),
   0, $q$34 de 40 cupos equivale a 34/40 = 0,85 = 85%.$q$,
   jsonb_build_array($q$Correcta: calcula la razon entre ocupados y cupos.$q$, $q$Incorrecta: usa la cantidad como porcentaje.$q$, $q$Incorrecta: corresponde al total de cupos, no a ocupacion.$q$)),
  (32, 'raz-cuant-07', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-02', '6-10', 'Razonamiento cuantitativo',
   $q$Situacion 2. Una sede rural organiza transporte para estudiantes. Un bus tiene 40 cupos y realiza dos recorridos diarios. El lunes viajaron 34 estudiantes en el primer recorrido y 28 en el segundo. El martes viajaron 36 en el primero y 32 en el segundo. La rectoria quiere calcular ocupacion, cupos disponibles y variaciones para planear rutas.$q$,
   7, $q$El total de estudiantes transportados el martes fue:$q$,
   jsonb_build_array($q$68 estudiantes.$q$, $q$72 estudiantes.$q$, $q$40 estudiantes.$q$),
   0, $q$El martes viajaron 36 + 32 = 68 estudiantes en los dos recorridos.$q$,
   jsonb_build_array($q$Correcta: suma ambos recorridos del martes.$q$, $q$Incorrecta: 72 no corresponde a los datos.$q$, $q$Incorrecta: 40 es la capacidad por recorrido.$q$)),
  (33, 'raz-cuant-08', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-02', '6-10', 'Razonamiento cuantitativo',
   $q$Situacion 2. Una sede rural organiza transporte para estudiantes. Un bus tiene 40 cupos y realiza dos recorridos diarios. El lunes viajaron 34 estudiantes en el primer recorrido y 28 en el segundo. El martes viajaron 36 en el primero y 32 en el segundo. La rectoria quiere calcular ocupacion, cupos disponibles y variaciones para planear rutas.$q$,
   8, $q$El aumento de estudiantes transportados del lunes al martes fue:$q$,
   jsonb_build_array($q$6 estudiantes.$q$, $q$4 estudiantes.$q$, $q$12 estudiantes.$q$),
   0, $q$El lunes viajaron 62 y el martes 68; la diferencia es 6.$q$,
   jsonb_build_array($q$Correcta: compara totales diarios.$q$, $q$Incorrecta: 4 es solo la diferencia del segundo recorrido.$q$, $q$Incorrecta: no corresponde a la variacion total.$q$)),
  (34, 'raz-cuant-09', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-02', '6-10', 'Razonamiento cuantitativo',
   $q$Situacion 2. Una sede rural organiza transporte para estudiantes. Un bus tiene 40 cupos y realiza dos recorridos diarios. El lunes viajaron 34 estudiantes en el primer recorrido y 28 en el segundo. El martes viajaron 36 en el primero y 32 en el segundo. La rectoria quiere calcular ocupacion, cupos disponibles y variaciones para planear rutas.$q$,
   9, $q$El segundo recorrido del lunes tuvo disponibles:$q$,
   jsonb_build_array($q$12 cupos.$q$, $q$28 cupos.$q$, $q$6 cupos.$q$),
   0, $q$La capacidad es 40 y viajaron 28; quedaron 12 cupos disponibles.$q$,
   jsonb_build_array($q$Correcta: resta ocupados a capacidad.$q$, $q$Incorrecta: 28 es el numero de pasajeros.$q$, $q$Incorrecta: 6 es otra diferencia del contexto.$q$)),
  (35, 'raz-cuant-10', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-02', '6-10', 'Razonamiento cuantitativo',
   $q$Situacion 2. Una sede rural organiza transporte para estudiantes. Un bus tiene 40 cupos y realiza dos recorridos diarios. El lunes viajaron 34 estudiantes en el primer recorrido y 28 en el segundo. El martes viajaron 36 en el primero y 32 en el segundo. La rectoria quiere calcular ocupacion, cupos disponibles y variaciones para planear rutas.$q$,
   10, $q$La mayor ocupacion entre los cuatro recorridos fue:$q$,
   jsonb_build_array($q$90%, en el primer recorrido del martes.$q$, $q$80%, en el segundo recorrido del martes.$q$, $q$70%, en el segundo recorrido del lunes.$q$),
   0, $q$36 de 40 equivale a 90%, el valor mas alto entre 85%, 70%, 90% y 80%.$q$,
   jsonb_build_array($q$Correcta: compara todas las ocupaciones.$q$, $q$Incorrecta: 80% no es el mayor valor.$q$, $q$Incorrecta: 70% es el menor valor.$q$)),

  (36, 'raz-cuant-11', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-03', '11-15', 'Razonamiento cuantitativo',
   $q$Situacion 3. Para comprar material didactico, la institucion recibe tres cotizaciones. El proveedor A ofrece 12 kits por 360000 pesos. El proveedor B ofrece 10 kits por 320000 pesos. El proveedor C ofrece 15 kits por 420000 pesos. La decision debe considerar el costo unitario y la cantidad requerida para cinco sedes.$q$,
   11, $q$El proveedor con menor costo por kit es:$q$,
   jsonb_build_array($q$Proveedor C, con 28000 pesos por kit.$q$, $q$Proveedor A, con 30000 pesos por kit.$q$, $q$Proveedor B, con 32000 pesos por kit.$q$),
   0, $q$A cuesta 30000 por kit, B 32000 y C 28000; el menor es C.$q$,
   jsonb_build_array($q$Correcta: divide costo entre cantidad.$q$, $q$Incorrecta: A no es el menor.$q$, $q$Incorrecta: B es el mas costoso por unidad.$q$)),
  (37, 'raz-cuant-12', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-03', '11-15', 'Razonamiento cuantitativo',
   $q$Situacion 3. Para comprar material didactico, la institucion recibe tres cotizaciones. El proveedor A ofrece 12 kits por 360000 pesos. El proveedor B ofrece 10 kits por 320000 pesos. El proveedor C ofrece 15 kits por 420000 pesos. La decision debe considerar el costo unitario y la cantidad requerida para cinco sedes.$q$,
   12, $q$Si cada sede necesita 3 kits, la institucion requiere en total:$q$,
   jsonb_build_array($q$15 kits.$q$, $q$8 kits.$q$, $q$5 kits.$q$),
   0, $q$Cinco sedes por tres kits cada una equivalen a 15 kits.$q$,
   jsonb_build_array($q$Correcta: multiplica sedes por kits requeridos.$q$, $q$Incorrecta: suma 5 y 3, pero no representa el total.$q$, $q$Incorrecta: corresponde solo al numero de sedes.$q$)),
  (38, 'raz-cuant-13', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-03', '11-15', 'Razonamiento cuantitativo',
   $q$Situacion 3. Para comprar material didactico, la institucion recibe tres cotizaciones. El proveedor A ofrece 12 kits por 360000 pesos. El proveedor B ofrece 10 kits por 320000 pesos. El proveedor C ofrece 15 kits por 420000 pesos. La decision debe considerar el costo unitario y la cantidad requerida para cinco sedes.$q$,
   13, $q$Si se requieren exactamente 15 kits, el proveedor C permite comprarlos por:$q$,
   jsonb_build_array($q$420000 pesos.$q$, $q$450000 pesos.$q$, $q$320000 pesos.$q$),
   0, $q$La oferta C incluye 15 kits por 420000 pesos.$q$,
   jsonb_build_array($q$Correcta: toma la cotizacion directa.$q$, $q$Incorrecta: seria 15 kits al precio unitario de A.$q$, $q$Incorrecta: corresponde al paquete de B de 10 kits.$q$)),
  (39, 'raz-cuant-14', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-03', '11-15', 'Razonamiento cuantitativo',
   $q$Situacion 3. Para comprar material didactico, la institucion recibe tres cotizaciones. El proveedor A ofrece 12 kits por 360000 pesos. El proveedor B ofrece 10 kits por 320000 pesos. El proveedor C ofrece 15 kits por 420000 pesos. La decision debe considerar el costo unitario y la cantidad requerida para cinco sedes.$q$,
   14, $q$Comparado con comprar 15 kits al costo unitario del proveedor A, elegir C ahorra:$q$,
   jsonb_build_array($q$30000 pesos.$q$, $q$60000 pesos.$q$, $q$120000 pesos.$q$),
   0, $q$Al precio de A, 15 kits costarian 450000; C cuesta 420000, ahorro de 30000.$q$,
   jsonb_build_array($q$Correcta: compara costos equivalentes para 15 kits.$q$, $q$Incorrecta: duplica el ahorro real.$q$, $q$Incorrecta: no surge de los datos.$q$)),
  (40, 'raz-cuant-15', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-03', '11-15', 'Razonamiento cuantitativo',
   $q$Situacion 3. Para comprar material didactico, la institucion recibe tres cotizaciones. El proveedor A ofrece 12 kits por 360000 pesos. El proveedor B ofrece 10 kits por 320000 pesos. El proveedor C ofrece 15 kits por 420000 pesos. La decision debe considerar el costo unitario y la cantidad requerida para cinco sedes.$q$,
   15, $q$La decision mas eficiente, si se necesitan 15 kits y la calidad es equivalente, es:$q$,
   jsonb_build_array($q$elegir el proveedor C porque cubre la necesidad completa al menor costo unitario.$q$, $q$elegir el proveedor B porque el paquete total cuesta menos, aunque trae menos kits.$q$, $q$elegir el proveedor A porque ofrece una cantidad intermedia.$q$),
   0, $q$C satisface la cantidad requerida y tiene el menor costo por unidad.$q$,
   jsonb_build_array($q$Correcta: integra cantidad y costo unitario.$q$, $q$Incorrecta: B no cubre los 15 kits.$q$, $q$Incorrecta: A no cubre la necesidad completa ni es mas barato.$q$)),

  (41, 'raz-cuant-16', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-04', '16-20', 'Razonamiento cuantitativo',
   $q$Situacion 4. En una evaluacion diagnostica, 80 estudiantes presentaron una prueba. El 35% quedo en nivel bajo, el 45% en nivel basico y el resto en nivel alto. La coordinacion necesita convertir porcentajes en cantidades y definir metas de mejoramiento para el siguiente periodo.$q$,
   16, $q$La cantidad de estudiantes en nivel bajo es:$q$,
   jsonb_build_array($q$28 estudiantes.$q$, $q$35 estudiantes.$q$, $q$45 estudiantes.$q$),
   0, $q$El 35% de 80 es 28.$q$,
   jsonb_build_array($q$Correcta: calcula 0,35 por 80.$q$, $q$Incorrecta: confunde porcentaje con cantidad.$q$, $q$Incorrecta: corresponde al porcentaje de basico, no a cantidad.$q$)),
  (42, 'raz-cuant-17', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-04', '16-20', 'Razonamiento cuantitativo',
   $q$Situacion 4. En una evaluacion diagnostica, 80 estudiantes presentaron una prueba. El 35% quedo en nivel bajo, el 45% en nivel basico y el resto en nivel alto. La coordinacion necesita convertir porcentajes en cantidades y definir metas de mejoramiento para el siguiente periodo.$q$,
   17, $q$El porcentaje de estudiantes en nivel alto es:$q$,
   jsonb_build_array($q$20%.$q$, $q$10%.$q$, $q$80%.$q$),
   0, $q$35% + 45% = 80%; el porcentaje restante es 20%.$q$,
   jsonb_build_array($q$Correcta: calcula el complemento hasta 100%.$q$, $q$Incorrecta: no corresponde al restante.$q$, $q$Incorrecta: es la suma de bajo y basico.$q$)),
  (43, 'raz-cuant-18', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-04', '16-20', 'Razonamiento cuantitativo',
   $q$Situacion 4. En una evaluacion diagnostica, 80 estudiantes presentaron una prueba. El 35% quedo en nivel bajo, el 45% en nivel basico y el resto en nivel alto. La coordinacion necesita convertir porcentajes en cantidades y definir metas de mejoramiento para el siguiente periodo.$q$,
   18, $q$La cantidad de estudiantes en nivel basico es:$q$,
   jsonb_build_array($q$36 estudiantes.$q$, $q$45 estudiantes.$q$, $q$20 estudiantes.$q$),
   0, $q$El 45% de 80 es 36 estudiantes.$q$,
   jsonb_build_array($q$Correcta: convierte porcentaje a cantidad.$q$, $q$Incorrecta: confunde porcentaje con estudiantes.$q$, $q$Incorrecta: corresponde al porcentaje alto, no a cantidad.$q$)),
  (44, 'raz-cuant-19', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-04', '16-20', 'Razonamiento cuantitativo',
   $q$Situacion 4. En una evaluacion diagnostica, 80 estudiantes presentaron una prueba. El 35% quedo en nivel bajo, el 45% en nivel basico y el resto en nivel alto. La coordinacion necesita convertir porcentajes en cantidades y definir metas de mejoramiento para el siguiente periodo.$q$,
   19, $q$Si se quiere reducir el nivel bajo a 20%, la cantidad maxima de estudiantes en ese nivel deberia ser:$q$,
   jsonb_build_array($q$16 estudiantes.$q$, $q$20 estudiantes.$q$, $q$28 estudiantes.$q$),
   0, $q$El 20% de 80 equivale a 16 estudiantes.$q$,
   jsonb_build_array($q$Correcta: aplica la meta porcentual al total.$q$, $q$Incorrecta: usa el porcentaje como cantidad.$q$, $q$Incorrecta: es la cantidad actual en bajo.$q$)),
  (45, 'raz-cuant-20', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-04', '16-20', 'Razonamiento cuantitativo',
   $q$Situacion 4. En una evaluacion diagnostica, 80 estudiantes presentaron una prueba. El 35% quedo en nivel bajo, el 45% en nivel basico y el resto en nivel alto. La coordinacion necesita convertir porcentajes en cantidades y definir metas de mejoramiento para el siguiente periodo.$q$,
   20, $q$Para cumplir la meta de bajar de 35% a 20%, deben salir del nivel bajo al menos:$q$,
   jsonb_build_array($q$12 estudiantes.$q$, $q$8 estudiantes.$q$, $q$16 estudiantes.$q$),
   0, $q$Actualmente hay 28 en bajo; la meta es 16. Deben mejorar al menos 12 estudiantes.$q$,
   jsonb_build_array($q$Correcta: resta cantidad actual menos cantidad meta.$q$, $q$Incorrecta: no alcanza la meta.$q$, $q$Incorrecta: confunde cantidad meta con reduccion necesaria.$q$)),

  (46, 'raz-cuant-21', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-05', '21-25', 'Razonamiento cuantitativo',
   $q$Situacion 5. Un proyecto institucional duro 8 semanas. En cada semana se realizaron 3 sesiones de 50 minutos. La orientadora informa que 18 estudiantes asistieron a todas las sesiones, 12 asistieron a tres cuartas partes y 10 asistieron a la mitad. El equipo quiere estimar tiempo de trabajo y clasificar asistencia.$q$,
   21, $q$El numero total de sesiones programadas fue:$q$,
   jsonb_build_array($q$24 sesiones.$q$, $q$11 sesiones.$q$, $q$50 sesiones.$q$),
   0, $q$8 semanas por 3 sesiones semanales equivalen a 24 sesiones.$q$,
   jsonb_build_array($q$Correcta: multiplica semanas por sesiones.$q$, $q$Incorrecta: suma semanas y sesiones.$q$, $q$Incorrecta: 50 son minutos por sesion.$q$)),
  (47, 'raz-cuant-22', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-05', '21-25', 'Razonamiento cuantitativo',
   $q$Situacion 5. Un proyecto institucional duro 8 semanas. En cada semana se realizaron 3 sesiones de 50 minutos. La orientadora informa que 18 estudiantes asistieron a todas las sesiones, 12 asistieron a tres cuartas partes y 10 asistieron a la mitad. El equipo quiere estimar tiempo de trabajo y clasificar asistencia.$q$,
   22, $q$Cada estudiante que asistio a todas las sesiones recibio:$q$,
   jsonb_build_array($q$1200 minutos de trabajo.$q$, $q$400 minutos de trabajo.$q$, $q$150 minutos de trabajo.$q$),
   0, $q$24 sesiones por 50 minutos equivalen a 1200 minutos.$q$,
   jsonb_build_array($q$Correcta: calcula tiempo total individual.$q$, $q$Incorrecta: 400 resulta de 8 por 50, sin considerar tres sesiones.$q$, $q$Incorrecta: corresponde a una semana.$q$)),
  (48, 'raz-cuant-23', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-05', '21-25', 'Razonamiento cuantitativo',
   $q$Situacion 5. Un proyecto institucional duro 8 semanas. En cada semana se realizaron 3 sesiones de 50 minutos. La orientadora informa que 18 estudiantes asistieron a todas las sesiones, 12 asistieron a tres cuartas partes y 10 asistieron a la mitad. El equipo quiere estimar tiempo de trabajo y clasificar asistencia.$q$,
   23, $q$Tres cuartas partes de 24 sesiones equivalen a:$q$,
   jsonb_build_array($q$18 sesiones.$q$, $q$12 sesiones.$q$, $q$6 sesiones.$q$),
   0, $q$24 por 3/4 equivale a 18 sesiones.$q$,
   jsonb_build_array($q$Correcta: calcula tres cuartas partes del total.$q$, $q$Incorrecta: corresponde a la mitad.$q$, $q$Incorrecta: corresponde a una cuarta parte.$q$)),
  (49, 'raz-cuant-24', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-05', '21-25', 'Razonamiento cuantitativo',
   $q$Situacion 5. Un proyecto institucional duro 8 semanas. En cada semana se realizaron 3 sesiones de 50 minutos. La orientadora informa que 18 estudiantes asistieron a todas las sesiones, 12 asistieron a tres cuartas partes y 10 asistieron a la mitad. El equipo quiere estimar tiempo de trabajo y clasificar asistencia.$q$,
   24, $q$La cantidad total de estudiantes reportados es:$q$,
   jsonb_build_array($q$40 estudiantes.$q$, $q$30 estudiantes.$q$, $q$24 estudiantes.$q$),
   0, $q$18 + 12 + 10 = 40 estudiantes.$q$,
   jsonb_build_array($q$Correcta: suma los grupos de asistencia.$q$, $q$Incorrecta: omite un grupo.$q$, $q$Incorrecta: corresponde al numero de sesiones.$q$)),
  (50, 'raz-cuant-25', 'razonamiento-cuantitativo-01', 'Simulacro #1 - Razonamiento cuantitativo', 'razonamiento', 'razonamiento-contexto-05', '21-25', 'Razonamiento cuantitativo',
   $q$Situacion 5. Un proyecto institucional duro 8 semanas. En cada semana se realizaron 3 sesiones de 50 minutos. La orientadora informa que 18 estudiantes asistieron a todas las sesiones, 12 asistieron a tres cuartas partes y 10 asistieron a la mitad. El equipo quiere estimar tiempo de trabajo y clasificar asistencia.$q$,
   25, $q$El porcentaje de estudiantes que asistio a todas las sesiones fue:$q$,
   jsonb_build_array($q$45%.$q$, $q$18%.$q$, $q$55%.$q$),
   0, $q$18 de 40 estudiantes equivalen a 45%.$q$,
   jsonb_build_array($q$Correcta: divide 18 entre 40.$q$, $q$Incorrecta: usa la cantidad como porcentaje.$q$, $q$Incorrecta: corresponde a los que no asistieron a todas.$q$)),

  (51, 'comp-bland-01', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-01', '1-5', 'Competencias comportamentales docentes',
   $q$Situacion 1. En una institucion educativa, el equipo de primaria debe organizar una feria de proyectos. La docente Ana propone distribuir tareas de acuerdo con fortalezas de cada integrante, pero dos companeros consideran que ella intenta controlar el proceso. Durante la reunion, algunos interrumpen, otros guardan silencio y el cronograma queda sin responsables claros. La coordinadora pide que el equipo retome la conversacion con acuerdos verificables.$q$,
   1, $q$La actuacion mas adecuada de Ana para fortalecer el trabajo en equipo es:$q$,
   jsonb_build_array($q$escuchar las inquietudes, aclarar su intencion y construir responsabilidades consensuadas.$q$, $q$asignar las tareas de inmediato porque ya identifico las fortalezas.$q$, $q$retirarse de la organizacion para evitar nuevos desacuerdos.$q$),
   0, $q$El trabajo colaborativo exige escucha, claridad y acuerdos compartidos.$q$,
   jsonb_build_array($q$Correcta: combina comunicacion y corresponsabilidad.$q$, $q$Incorrecta: refuerza la percepcion de control.$q$, $q$Incorrecta: abandona una responsabilidad institucional.$q$)),
  (52, 'comp-bland-02', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-01', '1-5', 'Competencias comportamentales docentes',
   $q$Situacion 1. En una institucion educativa, el equipo de primaria debe organizar una feria de proyectos. La docente Ana propone distribuir tareas de acuerdo con fortalezas de cada integrante, pero dos companeros consideran que ella intenta controlar el proceso. Durante la reunion, algunos interrumpen, otros guardan silencio y el cronograma queda sin responsables claros. La coordinadora pide que el equipo retome la conversacion con acuerdos verificables.$q$,
   2, $q$La coordinadora evidencia liderazgo cuando:$q$,
   jsonb_build_array($q$facilita turnos de palabra, precisa acuerdos y define seguimiento.$q$, $q$decide sola todas las tareas para ahorrar tiempo.$q$, $q$ignora el conflicto porque la feria es mas importante.$q$),
   0, $q$El liderazgo escolar promueve participacion, organizacion y cumplimiento de acuerdos.$q$,
   jsonb_build_array($q$Correcta: orienta al equipo sin anularlo.$q$, $q$Incorrecta: centraliza y reduce compromiso.$q$, $q$Incorrecta: el conflicto afecta el desarrollo del proyecto.$q$)),
  (53, 'comp-bland-03', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-01', '1-5', 'Competencias comportamentales docentes',
   $q$Situacion 1. En una institucion educativa, el equipo de primaria debe organizar una feria de proyectos. La docente Ana propone distribuir tareas de acuerdo con fortalezas de cada integrante, pero dos companeros consideran que ella intenta controlar el proceso. Durante la reunion, algunos interrumpen, otros guardan silencio y el cronograma queda sin responsables claros. La coordinadora pide que el equipo retome la conversacion con acuerdos verificables.$q$,
   3, $q$Interrumpir constantemente a los companeros afecta principalmente:$q$,
   jsonb_build_array($q$la comunicacion asertiva y la participacion equilibrada.$q$, $q$la disponibilidad de recursos materiales.$q$, $q$la validez juridica del proyecto institucional.$q$),
   0, $q$La interrupcion impide escuchar argumentos y reduce la participacion del equipo.$q$,
   jsonb_build_array($q$Correcta: identifica la competencia comportamental implicada.$q$, $q$Incorrecta: no se relaciona directamente con recursos.$q$, $q$Incorrecta: no se trata de validez juridica.$q$)),
  (54, 'comp-bland-04', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-01', '1-5', 'Competencias comportamentales docentes',
   $q$Situacion 1. En una institucion educativa, el equipo de primaria debe organizar una feria de proyectos. La docente Ana propone distribuir tareas de acuerdo con fortalezas de cada integrante, pero dos companeros consideran que ella intenta controlar el proceso. Durante la reunion, algunos interrumpen, otros guardan silencio y el cronograma queda sin responsables claros. La coordinadora pide que el equipo retome la conversacion con acuerdos verificables.$q$,
   4, $q$Un acuerdo verificable debe incluir:$q$,
   jsonb_build_array($q$responsable, tarea, fecha y evidencia de cumplimiento.$q$, $q$una intencion general sin responsables para evitar presion.$q$, $q$solo la opinion de quien coordina el proyecto.$q$),
   0, $q$Los acuerdos claros permiten seguimiento y distribucion responsable.$q$,
   jsonb_build_array($q$Correcta: hace observable el compromiso.$q$, $q$Incorrecta: la vaguedad impide seguimiento.$q$, $q$Incorrecta: excluye la participacion del equipo.$q$)),
  (55, 'comp-bland-05', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-01', '1-5', 'Competencias comportamentales docentes',
   $q$Situacion 1. En una institucion educativa, el equipo de primaria debe organizar una feria de proyectos. La docente Ana propone distribuir tareas de acuerdo con fortalezas de cada integrante, pero dos companeros consideran que ella intenta controlar el proceso. Durante la reunion, algunos interrumpen, otros guardan silencio y el cronograma queda sin responsables claros. La coordinadora pide que el equipo retome la conversacion con acuerdos verificables.$q$,
   5, $q$La mejor forma de manejar el desacuerdo inicial es:$q$,
   jsonb_build_array($q$identificar la preocupacion de fondo y acordar un metodo comun de decision.$q$, $q$votar rapidamente sin discutir las razones de cada posicion.$q$, $q$pedir que quienes discrepan no participen en la feria.$q$),
   0, $q$La negociacion efectiva aborda intereses y define reglas de trabajo compartidas.$q$,
   jsonb_build_array($q$Correcta: transforma el desacuerdo en acuerdo operativo.$q$, $q$Incorrecta: puede dejar tensiones sin resolver.$q$, $q$Incorrecta: excluye en vez de mediar.$q$)),

  (56, 'comp-bland-06', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-02', '6-10', 'Competencias comportamentales docentes',
   $q$Situacion 2. Un padre de familia llega alterado porque considera injusta la calificacion de su hija. Afirma que la docente no explica los criterios y amenaza con publicar el caso en redes sociales. La docente siente que se esta cuestionando su profesionalismo, pero sabe que debe proteger el dialogo, revisar evidencias y evitar una confrontacion publica que afecte a la estudiante.$q$,
   6, $q$La respuesta inicial mas adecuada de la docente es:$q$,
   jsonb_build_array($q$escuchar, reconocer la preocupacion y proponer revisar evidencias con criterios claros.$q$, $q$responder en redes sociales para defender inmediatamente su imagen.$q$, $q$negar la reunion porque el acudiente llego molesto.$q$),
   0, $q$La comunicacion asertiva reduce tension y orienta el dialogo hacia evidencias.$q$,
   jsonb_build_array($q$Correcta: cuida la relacion y el debido proceso.$q$, $q$Incorrecta: escala el conflicto publicamente.$q$, $q$Incorrecta: cierra un canal necesario de comunicacion.$q$)),
  (57, 'comp-bland-07', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-02', '6-10', 'Competencias comportamentales docentes',
   $q$Situacion 2. Un padre de familia llega alterado porque considera injusta la calificacion de su hija. Afirma que la docente no explica los criterios y amenaza con publicar el caso en redes sociales. La docente siente que se esta cuestionando su profesionalismo, pero sabe que debe proteger el dialogo, revisar evidencias y evitar una confrontacion publica que afecte a la estudiante.$q$,
   7, $q$Evitar la confrontacion publica protege principalmente:$q$,
   jsonb_build_array($q$la dignidad de la estudiante y la gestion responsable del conflicto.$q$, $q$la posibilidad de ocultar errores de evaluacion.$q$, $q$el derecho de la docente a no explicar sus decisiones.$q$),
   0, $q$El manejo reservado permite revisar el caso sin exponer innecesariamente a la estudiante.$q$,
   jsonb_build_array($q$Correcta: prioriza cuidado y responsabilidad.$q$, $q$Incorrecta: revisar evidencias no implica ocultar.$q$, $q$Incorrecta: la docente si debe explicar criterios.$q$)),
  (58, 'comp-bland-08', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-02', '6-10', 'Competencias comportamentales docentes',
   $q$Situacion 2. Un padre de familia llega alterado porque considera injusta la calificacion de su hija. Afirma que la docente no explica los criterios y amenaza con publicar el caso en redes sociales. La docente siente que se esta cuestionando su profesionalismo, pero sabe que debe proteger el dialogo, revisar evidencias y evitar una confrontacion publica que afecte a la estudiante.$q$,
   8, $q$La evidencia mas pertinente para revisar la calificacion seria:$q$,
   jsonb_build_array($q$rubrica, trabajo entregado, retroalimentacion y criterios comunicados previamente.$q$, $q$comentarios informales de otros padres sobre la docente.$q$, $q$numero de publicaciones que tenga el caso en redes.$q$),
   0, $q$La revision debe basarse en criterios y evidencias academicas verificables.$q$,
   jsonb_build_array($q$Correcta: centra el analisis en evidencias pertinentes.$q$, $q$Incorrecta: son opiniones externas al desempeno evaluado.$q$, $q$Incorrecta: popularidad no define justicia evaluativa.$q$)),
  (59, 'comp-bland-09', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-02', '6-10', 'Competencias comportamentales docentes',
   $q$Situacion 2. Un padre de familia llega alterado porque considera injusta la calificacion de su hija. Afirma que la docente no explica los criterios y amenaza con publicar el caso en redes sociales. La docente siente que se esta cuestionando su profesionalismo, pero sabe que debe proteger el dialogo, revisar evidencias y evitar una confrontacion publica que afecte a la estudiante.$q$,
   9, $q$Si se identifica que los criterios no fueron suficientemente claros, la docente deberia:$q$,
   jsonb_build_array($q$reconocer la dificultad, aclarar criterios y definir una accion de mejora justa para el grupo.$q$, $q$mantener la nota sin explicaciones para no perder autoridad.$q$, $q$cambiar solo la nota de la estudiante que hizo el reclamo.$q$),
   0, $q$La orientacion al logro y la transparencia exigen corregir procesos, no respuestas arbitrarias.$q$,
   jsonb_build_array($q$Correcta: combina responsabilidad y mejora.$q$, $q$Incorrecta: confunde autoridad con cierre al dialogo.$q$, $q$Incorrecta: puede generar trato desigual.$q$)),
  (60, 'comp-bland-10', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-02', '6-10', 'Competencias comportamentales docentes',
   $q$Situacion 2. Un padre de familia llega alterado porque considera injusta la calificacion de su hija. Afirma que la docente no explica los criterios y amenaza con publicar el caso en redes sociales. La docente siente que se esta cuestionando su profesionalismo, pero sabe que debe proteger el dialogo, revisar evidencias y evitar una confrontacion publica que afecte a la estudiante.$q$,
   10, $q$La competencia blanda mas visible en la actuacion esperada es:$q$,
   jsonb_build_array($q$comunicacion asertiva con manejo responsable del conflicto.$q$, $q$competencia financiera para administrar recursos.$q$, $q$dominio de contenidos disciplinares especializados.$q$),
   0, $q$El caso exige dialogar, escuchar, explicar y mediar una tension.$q$,
   jsonb_build_array($q$Correcta: corresponde al nucleo de la situacion.$q$, $q$Incorrecta: no se trata de presupuesto.$q$, $q$Incorrecta: no es un problema disciplinar de contenidos.$q$)),

  (61, 'comp-bland-11', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-03', '11-15', 'Competencias comportamentales docentes',
   $q$Situacion 3. Una docente nueva llega a una sede multigrado. Nota que algunos companeros usan expresiones despectivas sobre las familias rurales y que varios estudiantes evitan participar. La docente quiere promover cambios sin descalificar al equipo. Decide recoger evidencias, dialogar con sus colegas y proponer estrategias para reconocer saberes comunitarios en las clases.$q$,
   11, $q$La actuacion mas pertinente de la docente nueva es:$q$,
   jsonb_build_array($q$promover una conversacion profesional basada en evidencias y respeto por la comunidad.$q$, $q$denunciar publicamente a sus colegas sin intentar dialogo institucional.$q$, $q$ignorar las expresiones porque es nueva en la sede.$q$),
   0, $q$El compromiso social requiere actuar frente a prejuicios con respeto, evidencia y proposito formativo.$q$,
   jsonb_build_array($q$Correcta: equilibra firmeza y cuidado del equipo.$q$, $q$Incorrecta: puede romper canales institucionales necesarios.$q$, $q$Incorrecta: normaliza una practica excluyente.$q$)),
  (62, 'comp-bland-12', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-03', '11-15', 'Competencias comportamentales docentes',
   $q$Situacion 3. Una docente nueva llega a una sede multigrado. Nota que algunos companeros usan expresiones despectivas sobre las familias rurales y que varios estudiantes evitan participar. La docente quiere promover cambios sin descalificar al equipo. Decide recoger evidencias, dialogar con sus colegas y proponer estrategias para reconocer saberes comunitarios en las clases.$q$,
   12, $q$Reconocer saberes comunitarios contribuye principalmente a:$q$,
   jsonb_build_array($q$fortalecer pertenencia, participacion y pertinencia pedagogica.$q$, $q$reemplazar todos los contenidos escolares por costumbres locales.$q$, $q$evitar cualquier exigencia academica a los estudiantes.$q$),
   0, $q$La valoracion del contexto puede aumentar participacion sin abandonar aprendizajes.$q$,
   jsonb_build_array($q$Correcta: conecta comunidad y aprendizaje.$q$, $q$Incorrecta: no se propone sustituir el curriculo.$q$, $q$Incorrecta: pertinencia no significa baja exigencia.$q$)),
  (63, 'comp-bland-13', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-03', '11-15', 'Competencias comportamentales docentes',
   $q$Situacion 3. Una docente nueva llega a una sede multigrado. Nota que algunos companeros usan expresiones despectivas sobre las familias rurales y que varios estudiantes evitan participar. La docente quiere promover cambios sin descalificar al equipo. Decide recoger evidencias, dialogar con sus colegas y proponer estrategias para reconocer saberes comunitarios en las clases.$q$,
   13, $q$La decision de no descalificar al equipo muestra:$q$,
   jsonb_build_array($q$habilidad para promover cambio cuidando las relaciones profesionales.$q$, $q$falta de compromiso con la comunidad educativa.$q$, $q$renuncia a intervenir frente a una situacion problematica.$q$),
   0, $q$La docente actua, pero evita formas que bloqueen el dialogo.$q$,
   jsonb_build_array($q$Correcta: evidencia tacto profesional y liderazgo.$q$, $q$Incorrecta: si hay compromiso con el cambio.$q$, $q$Incorrecta: propone acciones concretas.$q$)),
  (64, 'comp-bland-14', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-03', '11-15', 'Competencias comportamentales docentes',
   $q$Situacion 3. Una docente nueva llega a una sede multigrado. Nota que algunos companeros usan expresiones despectivas sobre las familias rurales y que varios estudiantes evitan participar. La docente quiere promover cambios sin descalificar al equipo. Decide recoger evidencias, dialogar con sus colegas y proponer estrategias para reconocer saberes comunitarios en las clases.$q$,
   14, $q$La evidencia mas util para iniciar la conversacion con colegas seria:$q$,
   jsonb_build_array($q$ejemplos de baja participacion y percepciones recogidas con respeto.$q$, $q$rumores sobre la vida privada de los docentes.$q$, $q$comparaciones ofensivas entre sedes urbanas y rurales.$q$),
   0, $q$Las evidencias pertinentes se relacionan con efectos pedagogicos y clima escolar.$q$,
   jsonb_build_array($q$Correcta: orienta el dialogo a hechos y mejora.$q$, $q$Incorrecta: vulnera la confianza y no aporta al problema.$q$, $q$Incorrecta: reproduce el sesgo que se quiere superar.$q$)),
  (65, 'comp-bland-15', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-03', '11-15', 'Competencias comportamentales docentes',
   $q$Situacion 3. Una docente nueva llega a una sede multigrado. Nota que algunos companeros usan expresiones despectivas sobre las familias rurales y que varios estudiantes evitan participar. La docente quiere promover cambios sin descalificar al equipo. Decide recoger evidencias, dialogar con sus colegas y proponer estrategias para reconocer saberes comunitarios en las clases.$q$,
   15, $q$La competencia de compromiso social se evidencia mejor cuando la docente:$q$,
   jsonb_build_array($q$defiende la dignidad de las familias y vincula su contexto al aprendizaje.$q$, $q$acepta expresiones discriminatorias para conservar tranquilidad.$q$, $q$trabaja solo con estudiantes que ya participan activamente.$q$),
   0, $q$El compromiso social implica respeto por la comunidad y accion pedagogica incluyente.$q$,
   jsonb_build_array($q$Correcta: integra dignidad y practica educativa.$q$, $q$Incorrecta: normaliza discriminacion.$q$, $q$Incorrecta: excluye a quienes mas necesitan apoyo.$q$)),

  (66, 'comp-bland-16', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-04', '16-20', 'Competencias comportamentales docentes',
   $q$Situacion 4. Un equipo docente recibe bajos resultados en una prueba interna. Algunos proponen culpar a los estudiantes por falta de habitos; otros quieren revisar planeaciones, estrategias de retroalimentacion y seguimiento. La jefatura de area pide construir un plan realista para el siguiente periodo, con metas medibles y apoyo entre pares.$q$,
   16, $q$La respuesta que mejor muestra orientacion al logro es:$q$,
   jsonb_build_array($q$analizar causas, definir metas medibles y hacer seguimiento periodico.$q$, $q$atribuir el resultado a las familias sin modificar practicas.$q$, $q$esperar la siguiente prueba para ver si mejora espontaneamente.$q$),
   0, $q$La orientacion al logro implica actuar con metas, seguimiento y mejora continua.$q$,
   jsonb_build_array($q$Correcta: convierte el resultado en plan de mejora.$q$, $q$Incorrecta: evade responsabilidad profesional.$q$, $q$Incorrecta: no plantea accion concreta.$q$)),
  (67, 'comp-bland-17', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-04', '16-20', 'Competencias comportamentales docentes',
   $q$Situacion 4. Un equipo docente recibe bajos resultados en una prueba interna. Algunos proponen culpar a los estudiantes por falta de habitos; otros quieren revisar planeaciones, estrategias de retroalimentacion y seguimiento. La jefatura de area pide construir un plan realista para el siguiente periodo, con metas medibles y apoyo entre pares.$q$,
   17, $q$El apoyo entre pares resulta valioso porque:$q$,
   jsonb_build_array($q$permite compartir estrategias, observar practicas y aprender colectivamente.$q$, $q$evita que cada docente revise su propia practica.$q$, $q$sirve para identificar culpables del bajo resultado.$q$),
   0, $q$El aprendizaje profesional colaborativo fortalece la mejora pedagogica.$q$,
   jsonb_build_array($q$Correcta: reconoce el valor formativo del equipo.$q$, $q$Incorrecta: tambien requiere reflexion individual.$q$, $q$Incorrecta: no busca culpabilizar.$q$)),
  (68, 'comp-bland-18', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-04', '16-20', 'Competencias comportamentales docentes',
   $q$Situacion 4. Un equipo docente recibe bajos resultados en una prueba interna. Algunos proponen culpar a los estudiantes por falta de habitos; otros quieren revisar planeaciones, estrategias de retroalimentacion y seguimiento. La jefatura de area pide construir un plan realista para el siguiente periodo, con metas medibles y apoyo entre pares.$q$,
   18, $q$Una meta medible estaria formulada como:$q$,
   jsonb_build_array($q$aumentar del 45% al 60% los estudiantes que justifican respuestas con evidencia en ocho semanas.$q$, $q$mejorar bastante la calidad de las respuestas cuando sea posible.$q$, $q$hacer actividades agradables para que todos se sientan mejor.$q$),
   0, $q$La meta incluye linea base, valor esperado, habilidad y plazo.$q$,
   jsonb_build_array($q$Correcta: permite seguimiento verificable.$q$, $q$Incorrecta: es vaga.$q$, $q$Incorrecta: no define indicador de aprendizaje.$q$)),
  (69, 'comp-bland-19', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-04', '16-20', 'Competencias comportamentales docentes',
   $q$Situacion 4. Un equipo docente recibe bajos resultados en una prueba interna. Algunos proponen culpar a los estudiantes por falta de habitos; otros quieren revisar planeaciones, estrategias de retroalimentacion y seguimiento. La jefatura de area pide construir un plan realista para el siguiente periodo, con metas medibles y apoyo entre pares.$q$,
   19, $q$Culpar exclusivamente a los estudiantes es poco profesional porque:$q$,
   jsonb_build_array($q$impide revisar practicas docentes y condiciones de aprendizaje modificables.$q$, $q$demuestra una evaluacion objetiva de todos los factores.$q$, $q$garantiza que las familias asuman todo el proceso escolar.$q$),
   0, $q$La mejora exige reconocer factores sobre los que la escuela puede actuar.$q$,
   jsonb_build_array($q$Correcta: cuestiona una explicacion unica y defensiva.$q$, $q$Incorrecta: no analiza todos los factores.$q$, $q$Incorrecta: desplaza indebidamente la responsabilidad.$q$)),
  (70, 'comp-bland-20', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-04', '16-20', 'Competencias comportamentales docentes',
   $q$Situacion 4. Un equipo docente recibe bajos resultados en una prueba interna. Algunos proponen culpar a los estudiantes por falta de habitos; otros quieren revisar planeaciones, estrategias de retroalimentacion y seguimiento. La jefatura de area pide construir un plan realista para el siguiente periodo, con metas medibles y apoyo entre pares.$q$,
   20, $q$La jefatura de area favorece el liderazgo cuando:$q$,
   jsonb_build_array($q$convoca al equipo a construir un plan compartido con responsabilidades claras.$q$, $q$impone una solucion sin escuchar a los docentes.$q$, $q$archiva los resultados para evitar tensiones.$q$),
   0, $q$El liderazgo moviliza al equipo hacia metas comunes y seguimiento.$q$,
   jsonb_build_array($q$Correcta: promueve accion colectiva.$q$, $q$Incorrecta: reduce participacion y compromiso.$q$, $q$Incorrecta: evita el mejoramiento.$q$)),

  (71, 'comp-bland-21', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-05', '21-25', 'Competencias comportamentales docentes',
   $q$Situacion 5. Durante una salida pedagogica, empieza una lluvia intensa y el transporte de regreso se retrasa. Algunos estudiantes se inquietan, una familia llama molesta y dos docentes discuten sobre quien debio revisar el pronostico. La docente responsable debe tomar decisiones rapidas, proteger a los estudiantes, informar con claridad y luego evaluar lo ocurrido para mejorar el protocolo.$q$,
   21, $q$La primera prioridad de la docente responsable debe ser:$q$,
   jsonb_build_array($q$garantizar seguridad de los estudiantes y comunicar informacion clara a la institucion y familias.$q$, $q$buscar de inmediato quien tuvo la culpa del retraso.$q$, $q$continuar la actividad planeada para no perder tiempo academico.$q$),
   0, $q$Ante una contingencia, la seguridad y la comunicacion son prioritarias.$q$,
   jsonb_build_array($q$Correcta: responde a la urgencia del caso.$q$, $q$Incorrecta: la evaluacion de responsabilidades viene despues.$q$, $q$Incorrecta: ignora el riesgo inmediato.$q$)),
  (72, 'comp-bland-22', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-05', '21-25', 'Competencias comportamentales docentes',
   $q$Situacion 5. Durante una salida pedagogica, empieza una lluvia intensa y el transporte de regreso se retrasa. Algunos estudiantes se inquietan, una familia llama molesta y dos docentes discuten sobre quien debio revisar el pronostico. La docente responsable debe tomar decisiones rapidas, proteger a los estudiantes, informar con claridad y luego evaluar lo ocurrido para mejorar el protocolo.$q$,
   22, $q$Frente a la llamada de la familia molesta, la comunicacion mas adecuada es:$q$,
   jsonb_build_array($q$informar hechos, medidas tomadas y canal de actualizacion sin entrar en discusiones.$q$, $q$responder que la familia debe esperar sin hacer preguntas.$q$, $q$culpar al transporte para cerrar la conversacion rapidamente.$q$),
   0, $q$La comunicacion en crisis debe ser clara, respetuosa y verificable.$q$,
   jsonb_build_array($q$Correcta: reduce incertidumbre y mantiene confianza.$q$, $q$Incorrecta: desconoce la preocupacion legitima.$q$, $q$Incorrecta: desplaza culpa sin resolver la situacion.$q$)),
  (73, 'comp-bland-23', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-05', '21-25', 'Competencias comportamentales docentes',
   $q$Situacion 5. Durante una salida pedagogica, empieza una lluvia intensa y el transporte de regreso se retrasa. Algunos estudiantes se inquietan, una familia llama molesta y dos docentes discuten sobre quien debio revisar el pronostico. La docente responsable debe tomar decisiones rapidas, proteger a los estudiantes, informar con claridad y luego evaluar lo ocurrido para mejorar el protocolo.$q$,
   23, $q$La discusion entre docentes debe manejarse inicialmente mediante:$q$,
   jsonb_build_array($q$una indicacion breve para concentrarse en la seguridad y dejar la evaluacion para despues.$q$, $q$un debate completo frente a los estudiantes para aclarar responsabilidades.$q$, $q$la exclusion inmediata de uno de los docentes de la salida.$q$),
   0, $q$En emergencia se prioriza la respuesta coordinada; el analisis posterior se hace con calma.$q$,
   jsonb_build_array($q$Correcta: organiza la accion bajo presion.$q$, $q$Incorrecta: expone conflicto y distrae del cuidado.$q$, $q$Incorrecta: puede agravar la situacion sin analisis.$q$)),
  (74, 'comp-bland-24', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-05', '21-25', 'Competencias comportamentales docentes',
   $q$Situacion 5. Durante una salida pedagogica, empieza una lluvia intensa y el transporte de regreso se retrasa. Algunos estudiantes se inquietan, una familia llama molesta y dos docentes discuten sobre quien debio revisar el pronostico. La docente responsable debe tomar decisiones rapidas, proteger a los estudiantes, informar con claridad y luego evaluar lo ocurrido para mejorar el protocolo.$q$,
   24, $q$Despues de la salida, la evaluacion mas util seria:$q$,
   jsonb_build_array($q$revisar decisiones, tiempos de comunicacion y ajustes necesarios al protocolo.$q$, $q$redactar un comunicado que oculte los retrasos para cuidar la imagen.$q$, $q$prohibir todas las salidas pedagogicas sin analizar alternativas.$q$),
   0, $q$La mejora continua exige analizar lo ocurrido y ajustar el procedimiento.$q$,
   jsonb_build_array($q$Correcta: convierte la contingencia en aprendizaje institucional.$q$, $q$Incorrecta: afecta transparencia y aprendizaje.$q$, $q$Incorrecta: es una respuesta extrema sin analisis.$q$)),
  (75, 'comp-bland-25', 'competencias-blandas-01', 'Simulacro #1 - Competencias blandas', 'pedagogica', 'blandas-contexto-05', '21-25', 'Competencias comportamentales docentes',
   $q$Situacion 5. Durante una salida pedagogica, empieza una lluvia intensa y el transporte de regreso se retrasa. Algunos estudiantes se inquietan, una familia llama molesta y dos docentes discuten sobre quien debio revisar el pronostico. La docente responsable debe tomar decisiones rapidas, proteger a los estudiantes, informar con claridad y luego evaluar lo ocurrido para mejorar el protocolo.$q$,
   25, $q$La competencia comportamental que integra mejor la situacion es:$q$,
   jsonb_build_array($q$iniciativa y manejo responsable de situaciones imprevistas.$q$, $q$memorizacion de normas sin aplicacion contextual.$q$, $q$competencia disciplinar en un area especifica.$q$),
   0, $q$La docente debe actuar oportunamente, coordinar y aprender de la experiencia.$q$,
   jsonb_build_array($q$Correcta: resume la respuesta profesional esperada.$q$, $q$Incorrecta: no basta conocer normas de memoria.$q$, $q$Incorrecta: el problema es comportamental y de gestion.$q$))
)
insert into public.quiz_questions (
  external_id, test_id, test_title, category, block_id, block_range, topic, situation,
  question_number, prompt, options, correct_answer, explanation, option_feedback, sequence, active
)
select
  external_id,
  test_id,
  test_title,
  category,
  block_id,
  block_range,
  topic,
  situation,
  question_number,
  prompt,
  options,
  correct_answer,
  explanation,
  option_feedback,
  base_sequence.value + position,
  true
from new_questions
cross join base_sequence
on conflict (external_id) do update
set test_id = excluded.test_id,
    test_title = excluded.test_title,
    category = excluded.category,
    block_id = excluded.block_id,
    block_range = excluded.block_range,
    topic = excluded.topic,
    situation = excluded.situation,
    question_number = excluded.question_number,
    prompt = excluded.prompt,
    options = excluded.options,
    correct_answer = excluded.correct_answer,
    explanation = excluded.explanation,
    option_feedback = excluded.option_feedback,
    sequence = excluded.sequence,
    active = true;
